### PR TITLE
Add tool for exporting and visualizing model architectures and SP decompositions

### PR DESCRIPTION
**Pull request by lockshaw**
**Description of changes:**

- Add tool in `bin/` for exporting and visualizing model architectures (`export-model-arch`)
- Add `utils/cli` library to make a nice interface for the above
- Fix bug in SP decomposition due to not checking in `get_cbc_decomposition` that the complete bipartite components were actually complete
- Fix bug in and optimize `transitive_reduction`, add optimized `transitive_closure` implementation
- Add infrastructure for generating, manipulating, and exporting binary SP decomposition trees
- Rename `serial-parallel` to `series-parallel` to match literature
- Add input/weight all-to-all insertion preprocessing for computation graphs to prevent inputs and weights from making graphs non-SP 
- Move `doctest` formatting out of `utils/fmt` and into `test/utils/doctest/fmt`, as having it in `utils` required adding a `doctest` dependency to `utils` which prevented binaries from getting built due to https://github.com/doctest/doctest/issues/609

To run `export-model-arch` (from the root of the repository):
```
$ proj build
$ ./build/normal/bin/export-model-arch/export-model-arch -h
```
should print a help message.

**Related Issues:**

Linked Issues:
- Issue #942 

Issues closed by this PR:
- Closes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1490)

### CODE REVIEW

**Review by wmdi — CHANGES_REQUESTED** [review]
> Reviewed 232 of 437 files at r1, 18 of 36 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1490)* status: 250 of 441 files reviewed, 2 unresolved discussions (waiting on @lockshaw and @Marsella8)

___
*[`lib/compiler/include/compiler/series_parallel/computation_graph_binary_sp_decomposition.struct.toml` line 22 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1490#-O6h3y2CBbSjen4iJXNh:-O6h3y2CBbSjen4iJXNi:bjsbo5p) ([raw file](https://github.com/flexflow/FlexFlow/blob/59d906856b9d756c0f43dcfcbb9edc0f40fd6842/lib/compiler/include/compiler/series_parallel/computation_graph_binary_sp_decomposition.struct.toml#L22)):*
> ```TOML
> [[fields]]
> name = "raw_tree"
> type = "::FlexFlow::GenericBinarySPDecompositionTree<::FlexFlow::layer_guid_t>"
> ```

Then how do we apply SPD for PCGs? Shouldn't we implement SPD for PCGs, and apply SPD for CGs by first converting CGs to PCGs?
___
*[`lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h` line 15 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1490#-O6hAGNQ6a8-B56uWiIl:-O6hAGNQ6a8-B56uWiIm:b-89eame) ([raw file](https://github.com/flexflow/FlexFlow/blob/59d906856b9d756c0f43dcfcbb9edc0f40fd6842/lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h#L15)):*
> ```objc
>     to_final_ast(std::variant<IntermediateSpDecompositionTree, Node> const &);
> 
> std::unordered_multiset<Node> get_nodes(SeriesParallelDecomposition const &sp);
> ```

Why is it multiset?

**Review by wmdi — COMMENTED** [review]
> Reviewed 173 of 437 files at r1, 18 of 36 files at r2.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1490)* status: all files reviewed, 2 unresolved discussions (waiting on @lockshaw and @Marsella8)

**Review by lockshaw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1490)* status: all files reviewed, 2 unresolved discussions (waiting on @Marsella8 and @wmdi)

___
*[`lib/compiler/include/compiler/series_parallel/computation_graph_binary_sp_decomposition.struct.toml` line 22 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1490#-O6h3y2CBbSjen4iJXNh:-O6hIR9sBs8lfuDJH-yW:bsj0apj) ([raw file](https://github.com/flexflow/FlexFlow/blob/59d906856b9d756c0f43dcfcbb9edc0f40fd6842/lib/compiler/include/compiler/series_parallel/computation_graph_binary_sp_decomposition.struct.toml#L22)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Then how do we apply SPD for PCGs? Shouldn't we implement SPD for PCGs, and apply SPD for CGs by first converting CGs to PCGs?
</blockquote></details>

This PR doesn't add SPD for PCGs (SPD for PCGs is more complex due to potential parallel ops being inserted on the weight nodes). Doing CG SPD by converting a CG to a PCG and then doing SPD would be fine, but that would require having PCG SPD implemented, which I'd rather not fold into this already large PR.
___
*[`lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h` line 15 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1490#-O6hAGNQ6a8-B56uWiIl:-O6hICDf6RaYlBXNzccY:bl3qx3y) ([raw file](https://github.com/flexflow/FlexFlow/blob/59d906856b9d756c0f43dcfcbb9edc0f40fd6842/lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.h#L15)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Why is it multiset?
</blockquote></details>

Because in approximate sp-decomposition (i.e., @Marsella8's stuff) node duplication can result in having the same node id in multiple places in the SP-decomposition I believe (@Marsella8 is this correct?)

**Review by wmdi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1490)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marsella8)

**Pull request merged**
