### PR TITLE
[Reduce] support reduce_mean

### PR DESCRIPTION
**Pull request by jiazhihao**
**Description of changes:**

1. Supporting reduce_mean operator.
2. Update Legion version

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [x] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

### CODE REVIEW

**Comment by reyna-abhyankar** [comment]
This implementation looks good to me. I can add this implementation to the repo refactor directly to save a merge. This also means we can remove all `mean` files, right?

**Comment by jiazhihao** [comment]
Right, we can directly merge this into the repo-refactor PR. All `mean` files can be removed.

**Comment by lockshaw** [comment]
@reyna-abhyankar Did this already get merged into repo refactor or does that still need to be done?

**Comment by reyna-abhyankar** [comment]
> @reyna-abhyankar Did this already get merged into repo refactor or does that still need to be done?

Yes, this has already been merged into the repo refactor.

**Pull request closed without merging**
