### PR TITLE
Fix tensor shapes for elementwise binary operations with broadcasting

### LINKED ISSUE #617: Investigate possible issues in output shape computation in keras/layers/merge.py
I suspect that enabling broadcasting in causing issues in the output shape computation in keras merge layers. I had not changed the output shape computation which I believe should have been changed. Or it could be something else since the CI tests should have caught this.

Eg: The following code should not be correct when inputs could be broadcasted.
https://github.com/flexflow/FlexFlow/blob/711eec0d5d3573235306221b543b78d7dc536f10/python/flexflow/keras/layers/merge.py#L130

cc: @lockshaw

### PR DESCRIPTION
**Pull request by soumyac1999**
**Description of changes:**

Example: `[16, 1, 2] + [16, 1552, 1]` has output shape of `[16, 1552, 2]` but the existing code was setting the size to `[16, 1, 2]`.

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #617

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/738)

### CODE REVIEW

**Review by jiazhihao — APPROVED** [review]

**Comment by jiazhihao** [comment]
The PR lgtm. However, it seems the changes do not pass the following test 
```
$EXE "$FF_HOME"/examples/python/keras/elementwise_mul_broadcast.py -ll:py 1 -ll:gpu "$GPUS" -ll:fsize "$FSIZE" -ll:zsize "$ZSIZE" -b ${BATCHSIZE} --only-data-parallel
```

**Comment by soumyac1999** [comment]
Closing since I messed something up in this PR. Adding changes in a new PR

**Comment by soumyac1999** [comment]
> The PR lgtm. However, it seems the changes do not pass the following test
> 
> ```
> $EXE "$FF_HOME"/examples/python/keras/elementwise_mul_broadcast.py -ll:py 1 -ll:gpu "$GPUS" -ll:fsize "$FSIZE" -ll:zsize "$ZSIZE" -b ${BATCHSIZE} --only-data-parallel
> ```

@jiazhihao, similar fixes were needed in Keras to correctly compute the output shapes. This test now passes (alteast locally, waiting for the CI checks).

**Comment by soumyac1999** [comment]
Moved to #1234

**Pull request closed without merging**
