### PR TITLE
No Op Op

### LINKED ISSUE #1059: Update NoOp operator

### PR DESCRIPTION
**Pull request by KateUnger**
**Description of changes:**

- Update No Op operator (btw no op has no kernels files)

**Related Issues:**

Linked Issues:
- Issue #1059 

Issues closed by this PR:
- Closes #1059

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1139)

### CODE REVIEW

**Review by reyna-abhyankar — DISMISSED** [review]

**Review by wmdi — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1139)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lockshaw)

**Review by wmdi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1139)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lockshaw)

**Comment by lockshaw** [comment]
@reyna-abhyankar @wmdi Is there a reason this hasn't been merged?

**Review by wmdi — DISMISSED** [review]
What are the conditions of auto-merge?

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1139#-:-NflhPv6Ag1yp-y6E8wF:buc9r6a)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lockshaw)

**Review by reyna-abhyankar — APPROVED** [review]

**Pull request merged**
