### PR TITLE
Add `ParallelComputationGraphBuilder`

### PR DESCRIPTION
**Pull request by lockshaw**
**Description of changes:**

- Add interface for building PCGs using parallel shape inference, analogous to `ParallelComputationGraphBuilder`.
- Modify `dtgen` to set `struct` constructors to be `explicit`, both for clarity and to remove a bug in string conversion.

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1411)

### CODE REVIEW

**Review by reyna-abhyankar — CHANGES_REQUESTED** [review]
> Reviewed 283 of 285 files at r1.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1411)* status: 283 of 285 files reviewed, 8 unresolved discussions (waiting on @lockshaw)

___
*[`lib/op-attrs/include/op-attrs/get_output_shapes.h` line 119 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9HtIYCoAOayTHGoZP:-O-9HtIYCoAOayTHGoZQ:b-oyzzd) ([raw file](https://github.com/flexflow/FlexFlow/blob/86339457770e6405745df7a1605a4bff86726e68/lib/op-attrs/include/op-attrs/get_output_shapes.h#L119)):*
> ```objc
> ParallelTensorShape get_output_shape(ConcatAttrs const &,
>                                      std::vector<ParallelTensorShape> const &);
> ParallelTensorShape get_output_shape(Conv2DAttrs const &,
> ```

Why delete?
___
*[`lib/op-attrs/include/op-attrs/ops/cast.h` line 14 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9IAIY8SOnOgTb5TU4:-O-9IAIY8SOnOgTb5TU5:b-kasekc) ([raw file](https://github.com/flexflow/FlexFlow/blob/2dbb3b9e4bbf972ff920a0a7032855eeaf019d68/lib/op-attrs/include/op-attrs/ops/cast.h#L14)):*
> ```objc
> CHECK_VALID_OP_ATTR(CastAttrs);
> 
> tl::expected<TensorShape, std::string> get_output_shape(CastAttrs const &,
> ```

Why is this moved over from the other file?
___
*[`lib/pcg/include/pcg/computation_graph_builder.h` line 285 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9KA3I4vI9mUcEA5ho:-O-9KA3I4vI9mUcEA5hp:b-oyzzd) ([raw file](https://github.com/flexflow/FlexFlow/blob/86339457770e6405745df7a1605a4bff86726e68/lib/pcg/include/pcg/computation_graph_builder.h#L285)):*
> ```objc
>       std::optional<std::string> const &name = std::nullopt);
>   tensor_guid_t
>       element_unary(ElementUnaryAttrs const &,
> ```

Why delete?
___
*[`lib/pcg/include/pcg/file_format/v1/graphs/v1_operator_graph.struct.toml` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9Ks6R7C4NgEJfzNK8:-O-9Ks6R7C4NgEJfzNK9:b-pyulao) ([raw file](https://github.com/flexflow/FlexFlow/blob/2dbb3b9e4bbf972ff920a0a7032855eeaf019d68/lib/pcg/include/pcg/file_format/v1/graphs/v1_operator_graph.struct.toml#L15)):*
> ```TOML
>   "<vector>",
>   "<unordered_set>",
>   "pcg/file_format/v1/graphs/v1_graph_edge.dtg.h",
> ```

Why is there a v1? 
___
*[`lib/pcg/include/pcg/parallel_computation_graph/parallel_computation_graph.h` line 9 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9M0VY6bXW43W-yyEu:-O-9M0VY6bXW43W-yyEv:b6dq2y9) ([raw file](https://github.com/flexflow/FlexFlow/blob/2dbb3b9e4bbf972ff920a0a7032855eeaf019d68/lib/pcg/include/pcg/parallel_computation_graph/parallel_computation_graph.h#L9)):*
> ```objc
> 
> namespace FlexFlow {
> ```

I think an interface here for getting the topological / reverse topological ordering would be nice since thats what the eventual legion backing will use
___
*[`lib/pcg/include/pcg/parallel_computation_graph/parallel_computation_graph_builder.h` line 10 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9McTC9LimjUZ3ci0R:-O-9McTC9LimjUZ3ci0S:b-sw57fu) ([raw file](https://github.com/flexflow/FlexFlow/blob/2dbb3b9e4bbf972ff920a0a7032855eeaf019d68/lib/pcg/include/pcg/parallel_computation_graph/parallel_computation_graph_builder.h#L10)):*
> ```objc
> namespace FlexFlow {
> 
> struct ParallelComputationGraphBuilder {
> ```

What about the rest of the operators? Is that a future todo
___
*[`lib/utils/include/utils/fmt.h` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9Pz831WVr83ULqO0u:-O-9Pz831WVr83ULqO0v:b-b277qm) ([raw file](https://github.com/flexflow/FlexFlow/blob/86339457770e6405745df7a1605a4bff86726e68/lib/utils/include/utils/fmt.h#L15)):*
> ```objc
> namespace fmt {
> 
> template <typename T, typename Char>
> ```

Why are these chunks deleted / moved over?
___
*[`lib/op-attrs/src/op-attrs/datatype.cc` line 24 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9J6gm9CE6g6ev7aBY:-O-9J6gm9CE6g6ev7aBZ:b-v0v9oy) ([raw file](https://github.com/flexflow/FlexFlow/blob/2dbb3b9e4bbf972ff920a0a7032855eeaf019d68/lib/op-attrs/src/op-attrs/datatype.cc#L24)):*
> ```cpp
> }
> 
> bool can_strictly_promote_datatype_from_to(DataType src, DataType dst) {
> ```

Can we do this more explicitly? If someone changes the ordering of datatypes in the original enum, this can be wrong.

**Review by lockshaw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1411)* status: 269 of 307 files reviewed, 8 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/op-attrs/include/op-attrs/get_output_shapes.h` line 119 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9HtIYCoAOayTHGoZP:-O-9TcWe5Bs2haD9gPxD:b6de3hj) ([raw file](https://github.com/flexflow/FlexFlow/blob/86339457770e6405745df7a1605a4bff86726e68/lib/op-attrs/include/op-attrs/get_output_shapes.h#L119)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Why delete?
</blockquote></details>

They're now declared in the corresponding header in `op-attrs/ops/` (e.g., `get_output_shape(CastAttrs const &, ParallelTensorShape const &` is now declared in `op-attrs/ops/cast.h`)
___
*[`lib/op-attrs/include/op-attrs/ops/cast.h` line 14 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9IAIY8SOnOgTb5TU4:-O-9TuNY33sFqW1AmEPj:b-kh1bxc) ([raw file](https://github.com/flexflow/FlexFlow/blob/2dbb3b9e4bbf972ff920a0a7032855eeaf019d68/lib/op-attrs/include/op-attrs/ops/cast.h#L14)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Why is this moved over from the other file?
</blockquote></details>

To me it seemed to make more sense to define these per-operator (so that all of the functions for a single operator type are grouped together) rather than define these per-capability (so that all of parallel shape inference is together) since each operator has a lot of shared stuff between the functions and may have extra functions (`get_kernel_shape`, `get_bias_shape`, etc.). If we need a common interface to them all that can always be added later by wrapping all of the per-operator functions (it's actually not unlikely this will get added later, but I'd prefer to wait until the use-case is clear)
___
*[`lib/pcg/include/pcg/computation_graph_builder.h` line 285 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9KA3I4vI9mUcEA5ho:-O-9V3cADeSxBdOtfzZS:byddbuu) ([raw file](https://github.com/flexflow/FlexFlow/blob/86339457770e6405745df7a1605a4bff86726e68/lib/pcg/include/pcg/computation_graph_builder.h#L285)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Why delete?
</blockquote></details>

With the `ElementScalarUnary` and `ElementUnaryAttrs` combined the additional functions felt necessary. I actually should have probably deleted `ComputationGraphBuilder::element_scalar_unary` too, which I will do unless you object 
___
*[`lib/pcg/include/pcg/file_format/v1/graphs/v1_operator_graph.struct.toml` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9Ks6R7C4NgEJfzNK8:-O-9VJcfDniHBXm6DDgk:b6so8s0) ([raw file](https://github.com/flexflow/FlexFlow/blob/2dbb3b9e4bbf972ff920a0a7032855eeaf019d68/lib/pcg/include/pcg/file_format/v1/graphs/v1_operator_graph.struct.toml#L15)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Why is there a v1?
</blockquote></details>

`V1` refers to the actual json file format--there's separate `V1` types for most of PCG to try to make the file format more explicit
___
*[`lib/pcg/include/pcg/parallel_computation_graph/parallel_computation_graph.h` line 9 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9M0VY6bXW43W-yyEu:-O-ZbdIz6ZYTFBdhL1jF:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2dbb3b9e4bbf972ff920a0a7032855eeaf019d68/lib/pcg/include/pcg/parallel_computation_graph/parallel_computation_graph.h#L9)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

I think an interface here for getting the topological / reverse topological ordering would be nice since thats what the eventual legion backing will use
</blockquote></details>

Done.
___
*[`lib/pcg/include/pcg/parallel_computation_graph/parallel_computation_graph_builder.h` line 10 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9McTC9LimjUZ3ci0R:-O-9VaPT7HO_BryD30Q1:b-gbivvm) ([raw file](https://github.com/flexflow/FlexFlow/blob/2dbb3b9e4bbf972ff920a0a7032855eeaf019d68/lib/pcg/include/pcg/parallel_computation_graph/parallel_computation_graph_builder.h#L10)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

What about the rest of the operators? Is that a future todo
</blockquote></details>

Yeah, this is just the list of operators we have shape inference for at the moment
___
*[`lib/utils/include/utils/fmt.h` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9Pz831WVr83ULqO0u:-O-9VfLa6EOPgDQpxNhf:b-kdvr3a) ([raw file](https://github.com/flexflow/FlexFlow/blob/86339457770e6405745df7a1605a4bff86726e68/lib/utils/include/utils/fmt.h#L15)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Why are these chunks deleted / moved over?
</blockquote></details>

The problem with grouping everything into a single `fmt.h` file is it means that anything that uses a single of these implementations gets rebuilt anytime any of them change. Having them per-file is a bit less convenient (as users have to choose which types they want to format in the includes) but leads to a lot less "rebuild the world" behavior. If this becomes too impractical I can move it back or add a wrapper header that just pulls the rest in (which may be the best solution), but for now I think `utils` could use more divided up headers rather than less
___
*[`lib/op-attrs/src/op-attrs/datatype.cc` line 24 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9J6gm9CE6g6ev7aBY:-O-9UTPxC2nuU-gap6VF:b-wuo4ca) ([raw file](https://github.com/flexflow/FlexFlow/blob/2dbb3b9e4bbf972ff920a0a7032855eeaf019d68/lib/op-attrs/src/op-attrs/datatype.cc#L24)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Can we do this more explicitly? If someone changes the ordering of datatypes in the original enum, this can be wrong.
</blockquote></details>

The best I can come up with is to added wrapper types for the arguments (i.e., `SrcDataType` and `DstDataType`), but I'm not sure the extra code is worth it as the whole "from, to" order is explicitly in the function name. The real answer here is to use a language with named arguments. If you think it's worth the extra code I'm happy to add it, but taking that approach might get pretty crazy pretty fast

**Review by reyna-abhyankar — CHANGES_REQUESTED** [review]
> Reviewed 2 of 285 files at r1, 36 of 36 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1411)* status: all files reviewed, 4 unresolved discussions (waiting on @lockshaw)

___
*[`lib/op-attrs/include/op-attrs/get_output_shapes.h` line 119 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9HtIYCoAOayTHGoZP:-O-ftHOF7YXRRY1Uw-JX:b-3vsu7n) ([raw file](https://github.com/flexflow/FlexFlow/blob/86339457770e6405745df7a1605a4bff86726e68/lib/op-attrs/include/op-attrs/get_output_shapes.h#L119)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

They're now declared in the corresponding header in `op-attrs/ops/` (e.g., `get_output_shape(CastAttrs const &, ParallelTensorShape const &` is now declared in `op-attrs/ops/cast.h`)
</blockquote></details>

Should that also happen for other operators?
___
*[`lib/op-attrs/include/op-attrs/ops/cast.h` line 14 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9IAIY8SOnOgTb5TU4:-O-ftNeE9bOt6k77rqRP:b8wskv9) ([raw file](https://github.com/flexflow/FlexFlow/blob/2dbb3b9e4bbf972ff920a0a7032855eeaf019d68/lib/op-attrs/include/op-attrs/ops/cast.h#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

To me it seemed to make more sense to define these per-operator (so that all of the functions for a single operator type are grouped together) rather than define these per-capability (so that all of parallel shape inference is together) since each operator has a lot of shared stuff between the functions and may have extra functions (`get_kernel_shape`, `get_bias_shape`, etc.). If we need a common interface to them all that can always be added later by wrapping all of the per-operator functions (it's actually not unlikely this will get added later, but I'd prefer to wait until the use-case is clear)
</blockquote></details>

Then we should do this for the rest of the operators (that can be a future todo, along with some of the other operator-specific changes made in this PR)
___
*[`lib/pcg/include/pcg/computation_graph_builder.h` line 285 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9KA3I4vI9mUcEA5ho:-O-fvFn68DTlvdD3tfCJ:b-bk5ip0) ([raw file](https://github.com/flexflow/FlexFlow/blob/86339457770e6405745df7a1605a4bff86726e68/lib/pcg/include/pcg/computation_graph_builder.h#L285)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

With the `ElementScalarUnary` and `ElementUnaryAttrs` combined the additional functions felt necessary. I actually should have probably deleted `ComputationGraphBuilder::element_scalar_unary` too, which I will do unless you object
</blockquote></details>

Works for me.
___
*[`lib/pcg/test/src/pcg/parallel_computation_graph/parallel_computation_graph.cc` line 5 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-fsxJS9S_Yl_BfOFsI:-O-fsxJTDWo3vK8HnhhN:b-w559y9) ([raw file](https://github.com/flexflow/FlexFlow/blob/bdc24d947d4ce8b727d675c9ac90ae23b9c3f1c8/lib/pcg/test/src/pcg/parallel_computation_graph/parallel_computation_graph.cc#L5)):*
> ```cpp
> 
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("topological_ordering") {
> ```

What is the difference between this test and the test above?
___
*[`lib/op-attrs/src/op-attrs/datatype.cc` line 24 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9J6gm9CE6g6ev7aBY:-O-ftnDv72ah5WdGVLWG:bhyrams) ([raw file](https://github.com/flexflow/FlexFlow/blob/2dbb3b9e4bbf972ff920a0a7032855eeaf019d68/lib/op-attrs/src/op-attrs/datatype.cc#L24)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

The best I can come up with is to added wrapper types for the arguments (i.e., `SrcDataType` and `DstDataType`), but I'm not sure the extra code is worth it as the whole "from, to" order is explicitly in the function name. The real answer here is to use a language with named arguments. If you think it's worth the extra code I'm happy to add it, but taking that approach might get pretty crazy pretty fast
</blockquote></details>

Instead of doing that, you can just manually compare each possibility. There's only 6 of them so it shouldn't be that much code
```
...
} else if (src == DataType::INT32) {
    return dst == DataType::INT32 || dst == DataType::INT64 ...
} ...
```
And you can assert if the datatype is not one of the listed options (so this breaks if a new datatype is added a new datatype). Where is this function used btw?
___
*[`lib/pcg/test/src/pcg/dataflow_graph/algorithms.cc` line 49 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-fsgAn-nWGQfq_FDow:-O-fsgAn-nWGQfq_FDox:bs5sk0n) ([raw file](https://github.com/flexflow/FlexFlow/blob/bdc24d947d4ce8b727d675c9ac90ae23b9c3f1c8/lib/pcg/test/src/pcg/dataflow_graph/algorithms.cc#L49)):*
> ```cpp
>   }
> 
>   TEST_CASE("topological_ordering") {
> ```

Should this PR test more complex cases or leave that for a future PR?

**Review by lockshaw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1411)* status: 304 of 307 files reviewed, 4 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/op-attrs/include/op-attrs/get_output_shapes.h` line 119 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9HtIYCoAOayTHGoZP:-O-fwtmi5Qh1l-1igdYc:b-jmi7au) ([raw file](https://github.com/flexflow/FlexFlow/blob/86339457770e6405745df7a1605a4bff86726e68/lib/op-attrs/include/op-attrs/get_output_shapes.h#L119)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Should that also happen for other operators?
</blockquote></details>

Eventually--this is being done incrementally as shape inference gets added for various operators
___
*[`lib/op-attrs/include/op-attrs/ops/cast.h` line 14 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9IAIY8SOnOgTb5TU4:-O-fx3p_AZ1Ev_wxsE_k:b-mywqxi) ([raw file](https://github.com/flexflow/FlexFlow/blob/2dbb3b9e4bbf972ff920a0a7032855eeaf019d68/lib/op-attrs/include/op-attrs/ops/cast.h#L14)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Then we should do this for the rest of the operators (that can be a future todo, along with some of the other operator-specific changes made in this PR)
</blockquote></details>

Yeah it's being incrementally done--each PR that adds shape inference moves the corresponding functions
___
*[`lib/pcg/include/pcg/computation_graph_builder.h` line 285 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9KA3I4vI9mUcEA5ho:-O-fxaX63RIij0xFoIsI:bb6un1j) ([raw file](https://github.com/flexflow/FlexFlow/blob/86339457770e6405745df7a1605a4bff86726e68/lib/pcg/include/pcg/computation_graph_builder.h#L285)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Works for me.
</blockquote></details>

Done
___
*[`lib/pcg/test/src/pcg/parallel_computation_graph/parallel_computation_graph.cc` line 5 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-fsxJS9S_Yl_BfOFsI:-O-fxwvJ1vBWaAB65pkE:b3kxjnr) ([raw file](https://github.com/flexflow/FlexFlow/blob/bdc24d947d4ce8b727d675c9ac90ae23b9c3f1c8/lib/pcg/test/src/pcg/parallel_computation_graph/parallel_computation_graph.cc#L5)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

What is the difference between this test and the test above?
</blockquote></details>

This is for `ParallelComputationGraph`, not `DataflowGraph`
___
*[`lib/op-attrs/src/op-attrs/datatype.cc` line 24 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9J6gm9CE6g6ev7aBY:-O-g-JyjBp8YXI-h2rr7:bsl9asn) ([raw file](https://github.com/flexflow/FlexFlow/blob/2dbb3b9e4bbf972ff920a0a7032855eeaf019d68/lib/op-attrs/src/op-attrs/datatype.cc#L24)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Instead of doing that, you can just manually compare each possibility. There's only 6 of them so it shouldn't be that much code
```
...
} else if (src == DataType::INT32) {
    return dst == DataType::INT32 || dst == DataType::INT64 ...
} ...
```
And you can assert if the datatype is not one of the listed options (so this breaks if a new datatype is added a new datatype). Where is this function used btw?
</blockquote></details>

In `ParallelComputationGraphBuilder::as_type` and in shape inference for `Cast`: https://github.com/lockshaw/FlexFlow/blob/a9cee72c2d317c1dd36c63b0bb66880530f5691a/lib/pcg/src/pcg/parallel_computation_graph/parallel_computation_graph_builder.cc#L425-L427
___
*[`lib/pcg/test/src/pcg/dataflow_graph/algorithms.cc` line 49 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-fsgAn-nWGQfq_FDow:-O-fxjW6EdXKzTdDS_8q:bma3apy) ([raw file](https://github.com/flexflow/FlexFlow/blob/bdc24d947d4ce8b727d675c9ac90ae23b9c3f1c8/lib/pcg/test/src/pcg/dataflow_graph/algorithms.cc#L49)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Should this PR test more complex cases or leave that for a future PR?
</blockquote></details>

Leave it for now, `DataflowGraph` is getting moved into `utils/graph` and there is currently work on improving unit testing there, so this can get dealt with then

**Comment by lockshaw** [comment]
*[`lib/op-attrs/src/op-attrs/datatype.cc` line 24 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-9J6gm9CE6g6ev7aBY:-O-g0LVQBtqjY796XLXl:b-wbynon) ([raw file](https://github.com/flexflow/FlexFlow/blob/2dbb3b9e4bbf972ff920a0a7032855eeaf019d68/lib/op-attrs/src/op-attrs/datatype.cc#L24)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

In `ParallelComputationGraphBuilder::as_type` and in shape inference for `Cast`: https://github.com/lockshaw/FlexFlow/blob/a9cee72c2d317c1dd36c63b0bb66880530f5691a/lib/pcg/src/pcg/parallel_computation_graph/parallel_computation_graph_builder.cc#L425-L427
</blockquote></details>

I misread your initial comment, this is now done

**Review by reyna-abhyankar — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1411)* status: all files reviewed, 2 unresolved discussions (waiting on @lockshaw)

___
*[`lib/op-attrs/test/src/datatype.cc` line 30 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-g35au1bxBI5pQGnJE:-O-g35au1bxBI5pQGnJF:bavoqrc) ([raw file](https://github.com/flexflow/FlexFlow/blob/a9cee72c2d317c1dd36c63b0bb66880530f5691a/lib/op-attrs/test/src/datatype.cc#L30)):*
> ```cpp
>         RC_PRE(can_strictly_promote_datatype_from_to(d1, d2));
>         RC_PRE(can_strictly_promote_datatype_from_to(d2, d3));
>         RC_ASSERT(!can_strictly_promote_datatype_from_to(d1, d3));
> ```

Maybe I don't know the exact syntax here, but shouldn't this be
`RC_ASSERT(can_strictly_promote_datatype_from_to(d1, d3));`?
___
*[`lib/op-attrs/src/op-attrs/datatype.cc` line 31 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-g28rZ68Ofqm2l6QwV:-O-g28rZ68Ofqm2l6QwW:b-m59emz) ([raw file](https://github.com/flexflow/FlexFlow/blob/a9cee72c2d317c1dd36c63b0bb66880530f5691a/lib/op-attrs/src/op-attrs/datatype.cc#L31)):*
> ```cpp
>       break;
>     case DataType::INT32:
>       allowed = {DataType::INT64};
> ```

why not float or double for ints? or are we only allowing exact precision

**Review by lockshaw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1411)* status: 301 of 319 files reviewed, 2 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/op-attrs/test/src/datatype.cc` line 30 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-g35au1bxBI5pQGnJE:-O-hGZ9dAj0IbKCKl31f:b-abqnru) ([raw file](https://github.com/flexflow/FlexFlow/blob/a9cee72c2d317c1dd36c63b0bb66880530f5691a/lib/op-attrs/test/src/datatype.cc#L30)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Maybe I don't know the exact syntax here, but shouldn't this be
`RC_ASSERT(can_strictly_promote_datatype_from_to(d1, d3));`?
</blockquote></details>

Yup! Fixed
___
*[`lib/op-attrs/src/op-attrs/datatype.cc` line 31 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-g28rZ68Ofqm2l6QwV:-O-hGNKU7LXSMoIbIBku:b-ldiwda) ([raw file](https://github.com/flexflow/FlexFlow/blob/a9cee72c2d317c1dd36c63b0bb66880530f5691a/lib/op-attrs/src/op-attrs/datatype.cc#L31)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

why not float or double for ints? or are we only allowing exact precision
</blockquote></details>

That's what I'm currently doing. Tbh I don't have a super clear idea of exactly what the correct behavior here is, so I'm starting with this and I'll figure it out later :slightly_smiling_face:

**Review by reyna-abhyankar — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1411)* status: all files reviewed, 2 unresolved discussions (waiting on @lockshaw)

___
*[`lib/op-attrs/test/src/datatype.cc` line 30 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-g35au1bxBI5pQGnJE:-O-hduWf0Utp00CbbAmr:b-rqq7id) ([raw file](https://github.com/flexflow/FlexFlow/blob/a9cee72c2d317c1dd36c63b0bb66880530f5691a/lib/op-attrs/test/src/datatype.cc#L30)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Yup! Fixed
</blockquote></details>

And did you figure out why it was passing before?
___
*[`lib/op-attrs/src/op-attrs/datatype.cc` line 31 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-g28rZ68Ofqm2l6QwV:-O-hdj5C0R8LOpgICC31:b-yfjl59) ([raw file](https://github.com/flexflow/FlexFlow/blob/a9cee72c2d317c1dd36c63b0bb66880530f5691a/lib/op-attrs/src/op-attrs/datatype.cc#L31)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

That's what I'm currently doing. Tbh I don't have a super clear idea of exactly what the correct behavior here is, so I'm starting with this and I'll figure it out later :slightly_smiling_face:
</blockquote></details>

Fair enough. Though if bool can be promoted to anything, then shouldn't int32 also be promotable to everything except bool?

**Comment by lockshaw** [comment]
*[`lib/op-attrs/src/op-attrs/datatype.cc` line 31 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-g28rZ68Ofqm2l6QwV:-O-hjSWY5jzHOL-N6elW:b-t84fjw) ([raw file](https://github.com/flexflow/FlexFlow/blob/a9cee72c2d317c1dd36c63b0bb66880530f5691a/lib/op-attrs/src/op-attrs/datatype.cc#L31)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Fair enough. Though if bool can be promoted to anything, then shouldn't int32 also be promotable to everything except bool?
</blockquote></details>

Why should it?

**Review by reyna-abhyankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1411)* status: all files reviewed, 1 unresolved discussion (waiting on @lockshaw)

___
*[`lib/op-attrs/src/op-attrs/datatype.cc` line 31 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-g28rZ68Ofqm2l6QwV:-O-hjyIM1em5Y8pJIsmh:bb64r3j) ([raw file](https://github.com/flexflow/FlexFlow/blob/a9cee72c2d317c1dd36c63b0bb66880530f5691a/lib/op-attrs/src/op-attrs/datatype.cc#L31)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why should it?
</blockquote></details>

I guess if you're going for exact precision then it's fine as is.

**Review by lockshaw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1411)* status: all files reviewed, 1 unresolved discussion (waiting on @reyna-abhyankar)

___
*[`lib/op-attrs/test/src/datatype.cc` line 30 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-g35au1bxBI5pQGnJE:-O-hj3AQ7uohX00OPsxb:b-ly33lu) ([raw file](https://github.com/flexflow/FlexFlow/blob/a9cee72c2d317c1dd36c63b0bb66880530f5691a/lib/op-attrs/test/src/datatype.cc#L30)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

And did you figure out why it was passing before?
</blockquote></details>

Yes, that's why stuff is now using `RC_SUBCASE`--the error wasn't getting properly handed over to doctest
___
*[`lib/op-attrs/src/op-attrs/datatype.cc` line 31 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1411#-O-g28rZ68Ofqm2l6QwV:-O-hkYOkAwawcoxJ398X:bkpnuya) ([raw file](https://github.com/flexflow/FlexFlow/blob/a9cee72c2d317c1dd36c63b0bb66880530f5691a/lib/op-attrs/src/op-attrs/datatype.cc#L31)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

I guess if you're going for exact precision then it's fine as is.
</blockquote></details>

I'm not entirely sure what the right answer here is, so I figured I'd err on the side of of being too conservative about the behavior and we can tweak if it ends up being unnecessarily restrictive

**Review by reyna-abhyankar — APPROVED** [review]

**Pull request merged**
