### PR TITLE
Kernel build

### PR DESCRIPTION
**Pull request by reyna-abhyankar**
**Description of changes:**

Build all operator `.cu` files in `lib/kernels`

Note: there is an issue with `embedding.cu` with the `half` datatype. All other operators are building.

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1366)

### CODE REVIEW

**Comment by lockshaw** [comment]
@reyna-abhyankar Can you add the cuda part of `kernels` to CI as part of this PR? Otherwise it'll just break immediately

**Comment by lockshaw** [comment]
*[`lib/op-attrs/include/op-attrs/activation.h` line 8 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-NvVx1ujCDEnICXmnbLw:-NvVx1ukDpYT2F3J7knO:bppk7ex) ([raw file](https://github.com/flexflow/FlexFlow/blob/8758c87481d4999ebce1241c207dee6bd5d4b2fb/lib/op-attrs/include/op-attrs/activation.h#L8)):*
> ```objc
> namespace FlexFlow {
> 
> enum class Activation { RELU, SIGMOID, TANH, GELU, NONE };
> ```

Why not just use `std::optional<Activation>` where you need this behavior?

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 67 of 75 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1366)* status: all files reviewed, 9 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/allocation.h` line 21 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-Nvd1CcQ-JEQoIPDZbRf:-Nvd1CcQ-JEQoIPDZbRg:b-9us82b) ([raw file](https://github.com/flexflow/FlexFlow/blob/24c3d6847cd96b3ed03b24d38aeee21ce5089add/lib/kernels/include/kernels/allocation.h#L21)):*
> ```objc
> 
>   void *allocate(size_t mem_size) {
>     return this->i_allocator->allocate(mem_size);
> ```

Should be moved to `.cc` file
___
*[`lib/kernels/include/kernels/conv_2d_kernels.h` line 4 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-Nvd1TwqCmwgarzN_rz2:-Nvd1TwqCmwgarzN_rz3:b6u84gw) ([raw file](https://github.com/flexflow/FlexFlow/blob/24c3d6847cd96b3ed03b24d38aeee21ce5089add/lib/kernels/include/kernels/conv_2d_kernels.h#L4)):*
> ```objc
> #define _FLEXFLOW_OPS_KERNELS_CONV_2D_KERNELS_H
> 
> #include "device.h"
> ```

Are you sure this change is doing something? I'm pretty sure they should resolve to the same file
___
*[`lib/kernels/include/kernels/reverse_kernels.h` line 8 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-Nvd1woeA8MH74sre359:-Nvd1woeA8MH74sre35A:b-m37ykd) ([raw file](https://github.com/flexflow/FlexFlow/blob/24c3d6847cd96b3ed03b24d38aeee21ce5089add/lib/kernels/include/kernels/reverse_kernels.h#L8)):*
> ```objc
> namespace FlexFlow {
> 
> using coord_t = long long;
> ```

If this is going to be used across multiple files move the definition to a single location
___
*[`lib/op-attrs/include/op-attrs/ops/embedding.h` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-NvVx98884FMUOyUGZI2:-NvVx98884FMUOyUGZI3:b-u7eldl) ([raw file](https://github.com/flexflow/FlexFlow/blob/8758c87481d4999ebce1241c207dee6bd5d4b2fb/lib/op-attrs/include/op-attrs/ops/embedding.h#L13)):*
> ```objc
> namespace FlexFlow {
> 
> enum class AggregateOp { SUM, AVG, NONE };
> ```

Why not just use `std::optional<AggregateOp>` where you need this behavior?
___
*[`lib/kernels/src/cuda/ops/batch_norm_kernels.cu` line 54 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-Nvd2RSQ3ZqaL82m4VlU:-Nvd2RSQ3ZqaL82m4VlV:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/24c3d6847cd96b3ed03b24d38aeee21ce5089add/lib/kernels/src/cuda/ops/batch_norm_kernels.cu#L54)):*
> ```Cuda
> 
> void backward_kernel(cudaStream_t stream,
>                      BatchNormPerDeviceState &m,
> ```





_Suggestion:_
```Cuda
                     BatchNormPerDeviceState const &m,
```
___
*[`lib/kernels/src/cuda/ops/linear_kernels.cu` line 77 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-Nvd2gXq-g_AaZe_R783:-Nvd2gXq-g_AaZe_R784:b-lh3soo) ([raw file](https://github.com/flexflow/FlexFlow/blob/24c3d6847cd96b3ed03b24d38aeee21ce5089add/lib/kernels/src/cuda/ops/linear_kernels.cu#L77)):*
> ```Cuda
>         break;
>       case Activation::GELU:
>         // mode = CUDNN_ACTIVATION_GELU; //cudnnActivationMode_t does not have
> ```

Throw some type of error 
___
*[`lib/kernels/src/cuda/ops/linear_kernels.cu` line 187 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-Nvd2sjI9zVFnz2z8Z1n:-Nvd2sjI9zVFnz2z8Z1o:b3smr55) ([raw file](https://github.com/flexflow/FlexFlow/blob/24c3d6847cd96b3ed03b24d38aeee21ce5089add/lib/kernels/src/cuda/ops/linear_kernels.cu#L187)):*
> ```Cuda
>         elements, B, C, (float *)output_ptr);
>   } else {
>     // Do nothing
> ```

Probably should do some error handling
___
*[`lib/kernels/src/cuda/ops/reshape_kernels.cu` line 54 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-Nvd3BfqEm0fVNNn_85t:-Nvd3BfqEm0fVNNn_85u:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/24c3d6847cd96b3ed03b24d38aeee21ce5089add/lib/kernels/src/cuda/ops/reshape_kernels.cu#L54)):*
> ```Cuda
>                                                    output.get<T>(),
>                                                    input.shape.num_elements(),
>                                                    (real_type<T>)alpha);
> ```





_Suggestion:_
```Cuda
                                                   static_cast<real_type<T>>(alpha));
```
___
*[`lib/kernels/src/cuda/ops/transpose_kernels.cu` line 39 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-Nvd3Q_a36gpHgqIg9sr:-Nvd3Q_a36gpHgqIg9ss:b2gvptq) ([raw file](https://github.com/flexflow/FlexFlow/blob/24c3d6847cd96b3ed03b24d38aeee21ce5089add/lib/kernels/src/cuda/ops/transpose_kernels.cu#L39)):*
> ```Cuda
> 
>   std::vector<int> perm_vector;
>   for (int i = 0; i < std::min(length, MAX_TENSOR_DIM); ++i) {
> ```

Probably better to throw an error if the dimension is too large?

**Comment by lockshaw** [comment]
@reyna-abhyankar Ignore the above, it was already added.

**Review by reyna-abhyankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1366)* status: 59 of 78 files reviewed, 9 unresolved discussions (waiting on @lockshaw)

___
*[`lib/kernels/include/kernels/allocation.h` line 21 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-Nvd1CcQ-JEQoIPDZbRf:-Nve4CqxC2B7xxD09XG4:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/24c3d6847cd96b3ed03b24d38aeee21ce5089add/lib/kernels/include/kernels/allocation.h#L21)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should be moved to `.cc` file
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/conv_2d_kernels.h` line 4 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-Nvd1TwqCmwgarzN_rz2:-NveCY8eBxBMXVsuuGHw:b-lsj4rk) ([raw file](https://github.com/flexflow/FlexFlow/blob/24c3d6847cd96b3ed03b24d38aeee21ce5089add/lib/kernels/include/kernels/conv_2d_kernels.h#L4)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Are you sure this change is doing something? I'm pretty sure they should resolve to the same file
</blockquote></details>

Yup I verified this.
___
*[`lib/kernels/include/kernels/reverse_kernels.h` line 8 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-Nvd1woeA8MH74sre359:-Nve4bUVB5HzqD8vcBwN:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/24c3d6847cd96b3ed03b24d38aeee21ce5089add/lib/kernels/include/kernels/reverse_kernels.h#L8)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

If this is going to be used across multiple files move the definition to a single location
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/embedding.h` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-NvVx98884FMUOyUGZI2:-Nve89iJ9BdtyIEAtYHM:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/8758c87481d4999ebce1241c207dee6bd5d4b2fb/lib/op-attrs/include/op-attrs/ops/embedding.h#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not just use `std::optional<AggregateOp>` where you need this behavior?
</blockquote></details>

Done.
___
*[`lib/kernels/src/cuda/ops/batch_norm_kernels.cu` line 54 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-Nvd2RSQ3ZqaL82m4VlU:-Nve4n0u8TpmsvA6CxIp:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/24c3d6847cd96b3ed03b24d38aeee21ce5089add/lib/kernels/src/cuda/ops/batch_norm_kernels.cu#L54)):*
> ```Cuda
> 
> void backward_kernel(cudaStream_t stream,
>                      BatchNormPerDeviceState &m,
> ```

Done.
___
*[`lib/kernels/src/cuda/ops/linear_kernels.cu` line 77 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-Nvd2gXq-g_AaZe_R783:-Nve4sygDpgT36tdR5iv:brttvaj) ([raw file](https://github.com/flexflow/FlexFlow/blob/24c3d6847cd96b3ed03b24d38aeee21ce5089add/lib/kernels/src/cuda/ops/linear_kernels.cu#L77)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Throw some type of error
</blockquote></details>

The usage of different activations is quite inconsistent in this kernel, so I'm going to just file this as an issue and link it (i.e. in `forward_kernel()` there's support for GELU but not in `backward_kernel()`).
___
*[`lib/kernels/src/cuda/ops/linear_kernels.cu` line 187 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-Nvd2sjI9zVFnz2z8Z1n:-Nve5MVeBAiGXk5-iEfe:bvk7c68) ([raw file](https://github.com/flexflow/FlexFlow/blob/24c3d6847cd96b3ed03b24d38aeee21ce5089add/lib/kernels/src/cuda/ops/linear_kernels.cu#L187)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably should do some error handling
</blockquote></details>

Not an error because there is no activation.
___
*[`lib/kernels/src/cuda/ops/reshape_kernels.cu` line 54 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-Nvd3BfqEm0fVNNn_85t:-Nve729wCjpIpPI2Rh2b:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/24c3d6847cd96b3ed03b24d38aeee21ce5089add/lib/kernels/src/cuda/ops/reshape_kernels.cu#L54)):*
> ```Cuda
>                                                    output.get<T>(),
>                                                    input.shape.num_elements(),
>                                                    (real_type<T>)alpha);
> ```

Done.
___
*[`lib/kernels/src/cuda/ops/transpose_kernels.cu` line 39 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1366#-Nvd3Q_a36gpHgqIg9sr:-Nve5ldpENdIbXI6KFoA:b-nx46br) ([raw file](https://github.com/flexflow/FlexFlow/blob/24c3d6847cd96b3ed03b24d38aeee21ce5089add/lib/kernels/src/cuda/ops/transpose_kernels.cu#L39)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably better to throw an error if the dimension is too large?
</blockquote></details>

Done. I don't have the intuition for why it was `min(length, MAX_TENSOR_DIM)` so I think it's better to make the change you suggested.

**Review by lockshaw — APPROVED** [review]
> Reviewed 19 of 19 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1366)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @reyna-abhyankar)

**Pull request merged**
