### PR TITLE
[Python] make pybind11 default python bindings

### PR DESCRIPTION
**Pull request by msbaines**
Now that March release is done, make pybind11 the default.

### CODE REVIEW

**Comment by eddy16112** [comment]
@msbaines I think your changes will always compile pybind even if using cffi, so I made a minor change to the Makefile. I am not sure what is the best way for CMake. I think we can do something like if (not FF_USE_CFFI), what do you think?

Another way is to keep the original code and set FF_USE_PYBIND=ON by default.

**Comment by msbaines** [comment]
> @msbaines I think your changes will always compile pybind even if using cffi, so I made a minor change to the Makefile. I am not sure what is the best way for CMake. I think we can do something like if (not FF_USE_CFFI), what do you think?
> 
> Another way is to keep the original code and set FF_USE_PYBIND=ON by default.

Currently, I am compiling both with FF_USE_CFFI environment variable controlling which binding will be used at runtime. That way users can switch between bindings very quickly if they run into problems.

**Comment by eddy16112** [comment]
> > @msbaines I think your changes will always compile pybind even if using cffi, so I made a minor change to the Makefile. I am not sure what is the best way for CMake. I think we can do something like if (not FF_USE_CFFI), what do you think?
> > Another way is to keep the original code and set FF_USE_PYBIND=ON by default.
> 
> Currently, I am compiling both with FF_USE_CFFI environment variable controlling which binding will be used at runtime. That way users can switch between bindings very quickly if they run into problems.

That makes sense to me, then I will delete my last commit.

**Comment by msbaines** [comment]
OK to merge?

**Pull request merged**
