### PR TITLE
Cast Op

### LINKED ISSUE #1046: Update Cast operator

### PR DESCRIPTION
**Pull request by KateUnger**
**Description of changes:**
- Updates Cast operation

TODO: Change `cast_kernels.cpp` and c`ast_kernels.cu`

**Related Issues:**

Linked Issues:
- Issue #1046

Issues closed by this PR:
- Closes #1046, #1167

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1111)

### CODE REVIEW

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1111)* status: 1 of 4 files reviewed, 9 unresolved discussions (waiting on @KateUnger)

___
*[`lib/kernels/include/kernels/cast_kernels.h` line 10 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-NeyfVsE1iyCGcqA47Nb:-NeyfVsE1iyCGcqA47Nc:bfh9svb) ([raw file](https://github.com/flexflow/FlexFlow/blob/951222e7b4188adaafa8ac44b30e4998c4eda6e6/lib/kernels/include/kernels/cast_kernels.h#L10)):*
> ```objc
> 
> struct CastPerDeviceState {
>   PerDeviceFFHandle handle;
> ```

Is there a reason this is being placed in the per device state rather than getting passed in as a function argument?
___
*[`lib/kernels/src/cuda/cast_kernels.cu` line 64 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-NeyflD-C4aX4n13VUKL:-NeyflD-C4aX4n13VUKM:bedp8jx) ([raw file](https://github.com/flexflow/FlexFlow/blob/a1bb222338ad4b5bcdc58c3af6d738ec970ce335/lib/kernels/src/cuda/cast_kernels.cu#L64)):*
> ```Cuda
> };
> 
> CastPerDeviceState init_kernel(PerDeviceFFHandle const &handle) {
> ```

Where'd the data type arguments go?
___
*[`lib/kernels/src/cuda/cast_kernels.cu` line 69 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-Neyfnw3-pMbN0z4LD3a:-Neyfnw3-pMbN0z4LD3b:b-fyo54x) ([raw file](https://github.com/flexflow/FlexFlow/blob/a1bb222338ad4b5bcdc58c3af6d738ec970ce335/lib/kernels/src/cuda/cast_kernels.cu#L69)):*
> ```Cuda
> 
> void forward_kernel(ffStream_t stream,
>                     CastPerDeviceState const *m,
> ```

Pass by const reference not pointer
___
*[`lib/runtime/src/ops/cast.h` line 45 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-Neyfssw7uODiSo0TZtD:-Neyfssx4r4mfDSiHhuE:bs2dogg) ([raw file](https://github.com/flexflow/FlexFlow/blob/951222e7b4188adaafa8ac44b30e4998c4eda6e6/lib/runtime/src/ops/cast.h#L45)):*
> ```objc
> #endif
> 
> // template <typename IDT>
> ```

Delete
___
*[`lib/runtime/src/ops/cast.h` line 126 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-NeyfvQb83HyP5etUlth:-NeyfvQb83HyP5etUlti:bs2dogg) ([raw file](https://github.com/flexflow/FlexFlow/blob/951222e7b4188adaafa8ac44b30e4998c4eda6e6/lib/runtime/src/ops/cast.h#L126)):*
> ```objc
> /* }; */
> 
> // void Cast::backward(FFModel const &ff) {
> ```

Delete
___
*[`lib/runtime/src/ops/cast.cc` line 32 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-Neyg-qT-xR_3sPpo4gO:-Neyg-qT-xR_3sPpo4gP:bs2dogg) ([raw file](https://github.com/flexflow/FlexFlow/blob/951222e7b4188adaafa8ac44b30e4998c4eda6e6/lib/runtime/src/ops/cast.cc#L32)):*
> ```cpp
> enum Slots { INPUT, OUTPUT, ATTRS, PROFILING, PER_DEVICE_STATE, HANDLE };
> 
> // declare Legion names
> ```

Delete
___
*[`lib/runtime/src/ops/cast.cc` line 110 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-NeygEPNBAzN3ks--fmL:-NeygEPNBAzN3ks--fmM:ba8i1mj) ([raw file](https://github.com/flexflow/FlexFlow/blob/951222e7b4188adaafa8ac44b30e4998c4eda6e6/lib/runtime/src/ops/cast.cc#L110)):*
> ```cpp
>                  profiling,
>                  "[Cast] forward_time = %.2lfms\n",
>                  &per_device_state,
> ```

Should be passed as a reference not a ptr
___
*[`lib/runtime/src/ops/cast.cc` line 134 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-NeygL2JAXghrNr819gv:-NeygL2JAXghrNr819gw:bhldq13) ([raw file](https://github.com/flexflow/FlexFlow/blob/951222e7b4188adaafa8ac44b30e4998c4eda6e6/lib/runtime/src/ops/cast.cc#L134)):*
> ```cpp
>                  profiling,
>                  "[Cast] forward_time = %.2lfms\n",
>                  &per_device_state,
> ```

Pass as reference
___
*[`lib/runtime/src/ops/cast.cc` line 154 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-NeygOcW4E2ESRZBUBOg:-NeygOcW4E2ESRZBUBOh:b-a7mc7h) ([raw file](https://github.com/flexflow/FlexFlow/blob/951222e7b4188adaafa8ac44b30e4998c4eda6e6/lib/runtime/src/ops/cast.cc#L154)):*
> ```cpp
>   auto env = sim.new_environment();
> 
>   // Assume cast has no cost
> ```

This isn't necessarily true--can you create an issue to track fixing this?

**Review by KateUnger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1111)* status: 1 of 4 files reviewed, 9 unresolved discussions (waiting on @lockshaw)

___
*[`lib/kernels/include/kernels/cast_kernels.h` line 10 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-NeyfVsE1iyCGcqA47Nb:-NfsFvYI7PsVD-qnLsuT:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/951222e7b4188adaafa8ac44b30e4998c4eda6e6/lib/kernels/include/kernels/cast_kernels.h#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Is there a reason this is being placed in the per device state rather than getting passed in as a function argument?
</blockquote></details>

Done.
___
*[`lib/kernels/src/cuda/cast_kernels.cu` line 64 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-NeyflD-C4aX4n13VUKL:-NfsCMVd8fG4D2RymWc1:b-xhqe3h) ([raw file](https://github.com/flexflow/FlexFlow/blob/a1bb222338ad4b5bcdc58c3af6d738ec970ce335/lib/kernels/src/cuda/cast_kernels.cu#L64)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Where'd the data type arguments go?
</blockquote></details>

They're passed in with forward and backward
___
*[`lib/kernels/src/cuda/cast_kernels.cu` line 69 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-Neyfnw3-pMbN0z4LD3a:-NfsCRZo90hY6HcPRg8S:bwjzp4a) ([raw file](https://github.com/flexflow/FlexFlow/blob/a1bb222338ad4b5bcdc58c3af6d738ec970ce335/lib/kernels/src/cuda/cast_kernels.cu#L69)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Pass by const reference not pointer
</blockquote></details>

Deleted PerDeviceState
___
*[`lib/runtime/src/ops/cast.h` line 45 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-Neyfssw7uODiSo0TZtD:-NfsDzFTEj4YwtzUWbRk:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/951222e7b4188adaafa8ac44b30e4998c4eda6e6/lib/runtime/src/ops/cast.h#L45)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/cast.h` line 126 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-NeyfvQb83HyP5etUlth:-NfsDzTL7s3g8CPT6V1K:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/951222e7b4188adaafa8ac44b30e4998c4eda6e6/lib/runtime/src/ops/cast.h#L126)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/cast.cc` line 32 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-Neyg-qT-xR_3sPpo4gO:-NfsE4Pb6kaaQyo8KqHj:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/951222e7b4188adaafa8ac44b30e4998c4eda6e6/lib/runtime/src/ops/cast.cc#L32)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/cast.cc` line 110 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-NeygEPNBAzN3ks--fmL:-NfsE7A48G-_T2PWPAVU:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/951222e7b4188adaafa8ac44b30e4998c4eda6e6/lib/runtime/src/ops/cast.cc#L110)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should be passed as a reference not a ptr
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/cast.cc` line 134 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-NeygL2JAXghrNr819gv:-NfsE7cSEEb0ztknUcDC:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/951222e7b4188adaafa8ac44b30e4998c4eda6e6/lib/runtime/src/ops/cast.cc#L134)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Pass as reference
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/cast.cc` line 154 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-NeygOcW4E2ESRZBUBOg:-NfsGkhsCzxPZTGbuu7o:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/951222e7b4188adaafa8ac44b30e4998c4eda6e6/lib/runtime/src/ops/cast.cc#L154)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This isn't necessarily true--can you create an issue to track fixing this?
</blockquote></details>

Done.

**Review by reyna-abhyankar — APPROVED** [review]

**Review by reyna-abhyankar — APPROVED** [review]

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1111)* status: all files reviewed, 1 unresolved discussion (waiting on @KateUnger)

___
*[`lib/kernels/src/hip/cast_kernels.cpp` line 82 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1111#-NgLdzi74AgQNUkfRYQG:-NgLdzi74AgQNUkfRYQH:b-8jl0i) ([raw file](https://github.com/flexflow/FlexFlow/blob/0ed0ed3fe5a152e8d80839c59e300fa0e441ecc8/lib/kernels/src/hip/cast_kernels.cpp#L82)):*
> ```cpp
>                     DataType input_type,
>                     DataType output_type,
>                     PerDeviceFFHandle handle) {
> ```

Why pass as value vs as `const &`?

**Review by reyna-abhyankar — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1111)* status: all files reviewed, 1 unresolved discussion (waiting on @KateUnger)

**Review by lockshaw — COMMENTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1111)* status: all files reviewed, 1 unresolved discussion (waiting on @KateUnger)

**Review by lockshaw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1111)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KateUnger)

**Pull request merged**
