### PR TITLE
Add a RequestManager to manage all requests and set BatchConfig for each inference batch

### PR DESCRIPTION
**Pull request by jiazhihao**
**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

### CODE REVIEW

**Comment by xinhaoc** [comment]
it looks great for me.
do you think we should add a task for loading data from cpu? like loading the weights/prompts, make the weights part code in a different file and get rid of the dataloader.
and do we need add a variable in request manager to remember how many requests we have finished,

**Comment by jiazhihao** [comment]
> like loading the weights/prompts, make the weights part code in a different file and get rid of the dataloader.

I like this idea. 

> do we need add a variable in request manager to remember how many requests we have finished,

I think we can easily add this functionality in RequestManager

**Comment by xinhaoc** [comment]
alright! I can make the update in a new branch

**Comment by jiazhihao** [comment]
That sounds good to me. I will then merge this PR to the inference branch.

**Comment by gabrieleoliaro** [comment]
@jiazhihao The CI tests shows the following assertion error: 
```
inference_moe: /__w/FlexFlow/FlexFlow/src/runtime/batch_config.cc:73: bool FlexFlow::BatchConfig::register_new_request(size_t, int, int): Assertion `false' failed.
./tests/cpp_gpu_tests.sh: line 60: 130529 Aborted                 (core dumped) inference_moe -ll:gpu "$GPUS" -ll:util 8 -ll:fsize "$FSIZE" -ll:zsize "$ZSIZE" --only-data-parallel
init linear (input): in_dim(78
```
Should we fix this before merging?

**Comment by jiazhihao** [comment]
`FlexFlow::BatchConfig::register_new_request` will be deprecated after the merge. I have only updated LLAMA to use ReuqestManager. I think we can do the merge and update the MoE and Transformers examples later.

**Pull request merged**
