### PR TITLE
Replicate OP 

### PR DESCRIPTION
**Pull request by lambda7xx**
**Description of changes:**
- update the reshape operator

**Related Issues:**

Linked Issues:
- Issue #1076 

Issues closed by this PR:
- Closes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1101)

### CODE REVIEW

**Review by wmdi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1101)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @KateUnger, @lambda7xx, @lockshaw, and @reyna-abhyankar)

___
*[`lib/runtime/src/ops/replicate.cc` line 45 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1101#-NfNXM75-dhwxPPAtB8z:-NfNXM75-dhwxPPAtB9-:b-8cn7ih) ([raw file](https://github.com/flexflow/FlexFlow/blob/fc35175cafff7a5e24120c818d34efc044cabb84/lib/runtime/src/ops/replicate.cc#L45)):*
> ```cpp
> using namespace FlexFlow::Kernels::Replicate;
> 
> enum Slots { INPUT, OUTPUT, ATTRS, PROFILING };
> ```

I don't see any reference of `ATTRS`

**Comment by lambda7xx** [comment]
*[`lib/runtime/src/ops/replicate.cc` line 45 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1101#-NfNXM75-dhwxPPAtB8z:-NfNaqJj1uQFx8T2ti-k:bw8inp) ([raw file](https://github.com/flexflow/FlexFlow/blob/fc35175cafff7a5e24120c818d34efc044cabb84/lib/runtime/src/ops/replicate.cc#L45)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I don't see any reference of `ATTRS`
</blockquote></details>

remove the init because it doesn't need perdevicestate.

**Comment by reyna-abhyankar** [comment]
> > Reviewed 2 of 3 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1101)_ status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @KateUnger, @lambda7xx, @lockshaw, and @reyna-abhyankar)
> 
> _[`lib/runtime/src/ops/replicate.cc` line 45 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1101#-NfNXM75-dhwxPPAtB8z:-NfNXM75-dhwxPPAtB9-:b-8cn7ih) ([raw file](https://github.com/flexflow/FlexFlow/blob/fc35175cafff7a5e24120c818d34efc044cabb84/lib/runtime/src/ops/replicate.cc#L45)):_
> 
> > ```c++
> > using namespace FlexFlow::Kernels::Replicate;
> > 
> > enum Slots { INPUT, OUTPUT, ATTRS, PROFILING };
> > ```
> 
> I don't see any reference of `ATTRS`

`ReshapeAttrs` has one field: `TensorShape shape`. If this is necessary to call the kernel, then we should bind to `ATTRS`.

**Review by reyna-abhyankar — DISMISSED** [review]

**Review by wmdi — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1101)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lockshaw)

**Pull request merged**
