### PR TITLE
PCG serialization, rapidcheck, dtgen, and shape inference

### LINKED ISSUE #1276: Implement reduction-based `ParallelDim`
This refactors `ParallelDim` from the Unity replica-dim version to the improved model based on specific operators that relate to the non-parallel semantics

### PR DESCRIPTION
**Pull request by lockshaw**
**Description of changes:**

- Move many visitable types over to `dtgen`
- Add new-style reduction dims and parallel tensor shape
- Add parallel shape inference for a subset of operators
  - `Add`
  - `ReLU`
  - `Linear`
  - `Conv2D`
  - `BatchMM`
  - `Embedding`
  - `Repartition`
  - `Combine`
  - `Replicate`
  - `Reduction`
- De-template `substitutions`
- Refactor `PCG`, `ComputationGraph`, etc. do be serializable and based on new `DataflowGraph` abstraction
- Add rapidcheck `Arbitrary` instances for many types, primarily through moving many types over to `dtgen`

Note: this PR temporarily breaks `substitutions`, which will be moved to a follow-up PR to prevent this PR from growing too large

**Related Issues:**

Supersedes #988 

Linked Issues:
- Issue #919

Issues closed by this PR:
- Closes #1276

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1394)

### CODE REVIEW

**Review by wmdi — COMMENTED** [review]
> Reviewed 679 of 701 files at r1, 38 of 38 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1394)* status: all files reviewed, 3 unresolved discussions (waiting on @lockshaw)

___
*[`lib/op-attrs/include/op-attrs/operator_attrs.h` line 41 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1394#-NzG7NIs4jGgmojuQExR:-NzG7NIs4jGgmojuQExS:beccm5y) ([raw file](https://github.com/flexflow/FlexFlow/blob/1a6d1f8d9de10f1d9159686c61b13e07b71671b6/lib/op-attrs/include/op-attrs/operator_attrs.h#L41)):*
> ```objc
> namespace FlexFlow {
> 
> /* using SharedOperatorAttrs = std::variant<BatchMatmulAttrs, */
> ```

Just remove them?
___
*[`lib/op-attrs/include/op-attrs/parallel_tensor_shape.h` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1394#-NzG8jGoABHcZGsgfV_f:-NzG8jGoABHcZGsgfV_g:b7fwuf1) ([raw file](https://github.com/flexflow/FlexFlow/blob/1a6d1f8d9de10f1d9159686c61b13e07b71671b6/lib/op-attrs/include/op-attrs/parallel_tensor_shape.h#L15)):*
> ```objc
> 
> ParallelTensorShape lift_to_parallel(TensorShape const &);
> ParallelTensorShape lift_to_parallel_with_degrees(TensorShape const &, SumDegree sum_degree, DiscardCopyDegree discard_copy_degree, FFOrdered<int> const &shard_degrees);
> ```

What is `DiscardCopyDegree`?
___
*[`lib/op-attrs/src/operator_attrs.cc` line 196 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1394#-NzJ91CHDs0RU1t_rzWx:-NzJ91CI5MMnymRwC7Eq:bwrqym0) ([raw file](https://github.com/flexflow/FlexFlow/blob/cb2c862b77b9707335868a12c90ca6c18fd67863/lib/op-attrs/src/operator_attrs.cc#L196)):*
> ```cpp
> bool is_valid(PCGOperatorAttrs const &attrs,
>               std::vector<ParallelTensorShape> const &input_shapes) {
>   NOT_IMPLEMENTED();
> ```

What should this function do?

**Review by lockshaw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1394)* status: 709 of 710 files reviewed, 3 unresolved discussions (waiting on @wmdi)

___
*[`lib/op-attrs/include/op-attrs/operator_attrs.h` line 41 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1394#-NzG7NIs4jGgmojuQExR:-NzMJO-qDdoSxTWHVWtO:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/1a6d1f8d9de10f1d9159686c61b13e07b71671b6/lib/op-attrs/include/op-attrs/operator_attrs.h#L41)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Just remove them?
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/parallel_tensor_shape.h` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1394#-NzG8jGoABHcZGsgfV_f:-NzMHr9H7vg3fDW92cxv:bqq8ast) ([raw file](https://github.com/flexflow/FlexFlow/blob/1a6d1f8d9de10f1d9159686c61b13e07b71671b6/lib/op-attrs/include/op-attrs/parallel_tensor_shape.h#L15)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

What is `DiscardCopyDegree`?
</blockquote></details>

It's what is created by Replicate. `SumDegree` turns from a bunch of shards into the un-parallel tensor via getting summed together, `DiscardCopyDegree` takes a bunch of identical tensors and recovers the un-parallel tensor by discarding all but one of the shards
___
*[`lib/op-attrs/src/operator_attrs.cc` line 196 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1394#-NzJ91CHDs0RU1t_rzWx:-NzMIIQF-_KKWcODwJ0h:b-1mppdl) ([raw file](https://github.com/flexflow/FlexFlow/blob/cb2c862b77b9707335868a12c90ca6c18fd67863/lib/op-attrs/src/operator_attrs.cc#L196)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

What should this function do?
</blockquote></details>

I'm divided as to whether parallel shape inference should be done via one function, or via two, where one checks whether the usage is valid and then the other actually does the inference. The reason for the second is that otherwise the 'is valid' code gets duplicated for each of `get_output_shape`, `get_weights_shape`, etc. This function would provide a common entry point to the 'is valid' code in the second design, but I haven't decided whether to go with that design or not

**Review by wmdi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1394)* status: all files reviewed, 2 unresolved discussions (waiting on @lockshaw)

___
*[`lib/op-attrs/include/op-attrs/parallel_tensor_shape.h` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1394#-NzG8jGoABHcZGsgfV_f:-NzRPJbB5OQhuxBVQdak:b-z1cp9m) ([raw file](https://github.com/flexflow/FlexFlow/blob/1a6d1f8d9de10f1d9159686c61b13e07b71671b6/lib/op-attrs/include/op-attrs/parallel_tensor_shape.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

It's what is created by Replicate. `SumDegree` turns from a bunch of shards into the un-parallel tensor via getting summed together, `DiscardCopyDegree` takes a bunch of identical tensors and recovers the un-parallel tensor by discarding all but one of the shards
</blockquote></details>

In this case, should `shard_degrees` be `combine_degrees` or `gather_degrees`? And I think it is better to redefine `FFOrdered<int>` as `xxDegree`.
___
*[`lib/op-attrs/src/operator_attrs.cc` line 196 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1394#-NzJ91CHDs0RU1t_rzWx:-NzRE3KvCmTUC0up7Wbs:b3fmxvu) ([raw file](https://github.com/flexflow/FlexFlow/blob/cb2c862b77b9707335868a12c90ca6c18fd67863/lib/op-attrs/src/operator_attrs.cc#L196)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I'm divided as to whether parallel shape inference should be done via one function, or via two, where one checks whether the usage is valid and then the other actually does the inference. The reason for the second is that otherwise the 'is valid' code gets duplicated for each of `get_output_shape`, `get_weights_shape`, etc. This function would provide a common entry point to the 'is valid' code in the second design, but I haven't decided whether to go with that design or not
</blockquote></details>

I think it is good to do so.

**Review by lockshaw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1394)* status: 676 of 712 files reviewed, 2 unresolved discussions (waiting on @lockshaw, @reyna-abhyankar, and @wmdi)

___
*[`lib/op-attrs/include/op-attrs/parallel_tensor_shape.h` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1394#-NzG8jGoABHcZGsgfV_f:-NzRZjoW3zoROQ4SvNEp:bg8iqyk) ([raw file](https://github.com/flexflow/FlexFlow/blob/1a6d1f8d9de10f1d9159686c61b13e07b71671b6/lib/op-attrs/include/op-attrs/parallel_tensor_shape.h#L15)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

In this case, should `shard_degrees` be `combine_degrees` or `gather_degrees`? And I think it is better to redefine `FFOrdered<int>` as `xxDegree`.
</blockquote></details>

I think "sharding" is actually the right name for the operation, I probably used it incorrectly above (maybe "instances" would be better for sharding+replicas? not sure). `CombineParallelDim` and `PartitionParallelDim` both sound more like actions than a type of dim (as `Combine` and `Partition` are both verbs, and `Combine` isn't a great name anyway), and `ConcatParallelDim` is even more confusing as we have a non-parallel concat operator. I agree there's room for improved naming, but at least until I get around to renaming a bunch of other stuff to be less ambiguous I think "shard" is the best I can think of? (the main contender I can think of is `PartitionParallelDim`, but I'm not sure that's any better than `ShardParallelDim`, and I'm not sure we want to explicitly tie the concept of their being multiple disjoint shards exactly to the `Partition` operator). @reyna-abhyankar do you have any thoughts on this?
___
*[`lib/op-attrs/src/operator_attrs.cc` line 196 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1394#-NzJ91CHDs0RU1t_rzWx:-NzR_ski2kXkLfrWjHMT:boqqwdg) ([raw file](https://github.com/flexflow/FlexFlow/blob/cb2c862b77b9707335868a12c90ca6c18fd67863/lib/op-attrs/src/operator_attrs.cc#L196)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I think it is good to do so.
</blockquote></details>

Either way it won't be introduced in this PR, as I want to get shape inference defined for more operators before trying to generalize things a bunch. To make sure it doesn't get forgotten I've added an issue: https://github.com/flexflow/FlexFlow/issues/1405

**Review by wmdi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 82 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1394)* status: 633 of 713 files reviewed, 1 unresolved discussion (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/op-attrs/include/op-attrs/parallel_tensor_shape.h` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1394#-NzG8jGoABHcZGsgfV_f:-NzSViPk0BYmDUHv5OiJ:b-y0nbsw) ([raw file](https://github.com/flexflow/FlexFlow/blob/1a6d1f8d9de10f1d9159686c61b13e07b71671b6/lib/op-attrs/include/op-attrs/parallel_tensor_shape.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I think "sharding" is actually the right name for the operation, I probably used it incorrectly above (maybe "instances" would be better for sharding+replicas? not sure). `CombineParallelDim` and `PartitionParallelDim` both sound more like actions than a type of dim (as `Combine` and `Partition` are both verbs, and `Combine` isn't a great name anyway), and `ConcatParallelDim` is even more confusing as we have a non-parallel concat operator. I agree there's room for improved naming, but at least until I get around to renaming a bunch of other stuff to be less ambiguous I think "shard" is the best I can think of? (the main contender I can think of is `PartitionParallelDim`, but I'm not sure that's any better than `ShardParallelDim`, and I'm not sure we want to explicitly tie the concept of their being multiple disjoint shards exactly to the `Partition` operator). @reyna-abhyankar do you have any thoughts on this?
</blockquote></details>

I think it is fine to keep it and find a better name later.

**Review by wmdi — COMMENTED** [review]
> Reviewed 80 of 82 files at r4.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1394)* status: all files reviewed, 1 unresolved discussion (waiting on @reyna-abhyankar)

**Review by lockshaw — COMMENTED** [review]
> Dismissed @wmdi from a discussion.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1394)* status: 700 of 736 files reviewed, all discussions resolved (waiting on @wmdi)

**Pull request merged**
