### PR TITLE
Contributing Legion Triton backend from NVIDIA

### PR DESCRIPTION
**Pull request by lightsighter**
**Description of changes:**
This pull request is a contribution of the Legion Triton backend from NVIDIA in the `triton` top-level directory.

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

### CODE REVIEW

**Comment by jiazhihao** [comment]
@lightsighter can you update the PR to push changes to the `triton` branch of FlexFlow? I will then fix format issues before merging the files to the master branch. Thanks!

**Comment by lightsighter** [comment]
@jiazhihao I think you'll need to create a `triton` branch in the Flexflow repository since I can't do that. Once there is one though, then I can change the pull request to target it.

**Comment by jiazhihao** [comment]
@lightsighter I have created a triton branch under the FlexFlow repo.

**Comment by lightsighter** [comment]
Updated.

**Pull request merged**
