### PR TITLE
Add missing import to fix broken Keras API on master 

### PR DESCRIPTION
**Pull request by soumyac1999**
**Description of changes:** Adds missing import in `python/flexflow/keras/models/base_model.py`

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

### CODE REVIEW

**Comment by lockshaw** [comment]
@soumyac1999 Happy to merge this now as I assume it can't break the code worse than it is already, but we should add tests to prevent this from happening in the future. Is that being done as part of #568 or is it going to need to be done separately?

**Review by lockshaw — APPROVED** [review]

**Comment by lockshaw** [comment]
> @soumyac1999 Happy to merge this now as I assume it can't break the code worse than it is already, but we should add tests to prevent this from happening in the future. Is that being done as part of #568 or is it going to need to be done separately?

Doesn't need to be anything fancy for now, even just a python script that imports all of the keras operators would work, as long as it fails CI if they go missing :slightly_smiling_face:

**Comment by soumyac1999** [comment]
@lockshaw, I am not entirely sure why this wasn't caught in the CI though. If I understand correctly, https://github.com/flexflow/FlexFlow/blob/master/tests/multi_gpu_tests.sh is run in the CI and it tests out keras examples which should have failed. Will investigate.
And yes, I am adding some simple tests in #568.

**Comment by lockshaw** [comment]
> @lockshaw, I am not entirely sure why this wasn't caught in the CI though. If I understand correctly, https://github.com/flexflow/FlexFlow/blob/master/tests/multi_gpu_tests.sh is run in the CI and it tests out keras examples which should have failed. Will investigate.e

Sounds good, just update #567 when you figure out why the issue wasn't caught

**Pull request merged**
