### PR TITLE
Refactor config.linux into python and fix conda cuda build issues

### PR DESCRIPTION
**Pull request by lockshaw**
**Description of changes:**

Translate `config.linux` and `config.inc` into Python and add a fix for building with conda-supplied cuda (essentially, the nvidia cuda-toolkit places `libcuda.so` under `lib/stubs` instead of `lib64/stubs`).

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

### CODE REVIEW

**Review by gabrieleoliaro — CHANGES_REQUESTED** [review]
Looks good, thanks for updating the configuration scripts! I like the idea, using python instead of bash makes it easier to use for the user. I find the new version of the scripts a bit less intuitive though, so I wonder if it'd be possible to make the code a bit more concise? We should also update the docs (should be in INSTALL.md) with instructions on how to use and an explanation of the main parameters

**Comment by lockshaw** [comment]
> I find the new version of the scripts a bit less intuitive though, so I wonder if it'd be possible to make the code a bit more concise?

Any specific parts you find less intuitive?

**Comment by gabrieleoliaro** [comment]
> > I find the new version of the scripts a bit less intuitive though, so I wonder if it'd be possible to make the code a bit more concise?
> 
> Any specific parts you find less intuitive?

I'm thinking mainly about the part where we use a different class in `config/ff_cmake.py` to define the type of each argparse argument, and we also set/get values from the corresponding environment variables. I know this mechanism is elegant, but if we just let argparse take strings for each parameter (setting the allowed values with the `choices` argument and the default option with the `default` argument), we could shorten the code by a lot and make it easier to understand. Also, less conversions would be needed to pass the values to the environment and/or cmake

**Comment by lockshaw** [comment]
The environment variable support was added to maintain backwards compatibility with the previous script. I have no strong desire to keep it in, the decision just needs to be made to break compatibility with the previous script.

You're right about the validation classes, I can get rid of those I think.

**Review by gabrieleoliaro — CHANGES_REQUESTED** [review]
Also, let's make sure to update the docs (INSTALL.md)

**Comment by lockshaw** [comment]
@gabrieleoliaro IIRC you were finishing off this PR--is that still the case or should I take it back over?

**Pull request closed without merging**
