### PR TITLE
support Group attention (Llama 2)

### LINKED ISSUE #908: Implement Kernel Fusion Optimizations for IncMHA/SpecMHA/TreeMHA
This issue tracks the implementation of the following kernel fusion optimizations in the MHA kernels.

1. After the layout changes, we should be able to merge the W_Q, W_K, and W_V matrix multiplications into a single, thus reduce kernel launch overhead: (https://github.com/flexflow/FlexFlow/blob/53c5617a8e5149ca1475978f391e4eb73c3434c5/src/ops/inc_multihead_self_attention.cu#L195-L265)
2. The two `apply_rotary_embedding` kernels can also be merged into one (https://github.com/flexflow/FlexFlow/blob/53c5617a8e5149ca1475978f391e4eb73c3434c5/src/ops/inc_multihead_self_attention.cu#L294-L322)
3. The two `store_kv_cache` kernels can be merged as well (https://github.com/flexflow/FlexFlow/blob/53c5617a8e5149ca1475978f391e4eb73c3434c5/src/ops/inc_multihead_self_attention.cu#L333-L360)
4. We call `cudnnCreateTensorDescriptor` per iteration (and don't free it); this results in memory leakage. The tensor descriptor `qk_tensor` should be a part of IncMHAMeta and created during initialization. (https://github.com/flexflow/FlexFlow/blob/53c5617a8e5149ca1475978f391e4eb73c3434c5/src/ops/inc_multihead_self_attention.cu#L635)

### PR DESCRIPTION
**Pull request by xinhaoc**
**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #908 

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

### CODE REVIEW

**Comment by xinhaoc** [comment]
Give three tips for staying healthy.
The first step is to make sure you are getting enough sleep.
The second step is to make sure you are eating healthy foods.
The third step is to make sure you are exercising regularly.
The fourth step is to make sure you are taking care of your mental health.
The fifth step is to make sure you are taking care of your physical health.
The sixth step is to make sure you are taking care of your emotional health.
The seventh step is to make sure you are taking care of your spiritual health.

**Comment by xinhaoc** [comment]
result from llama 70B:

`⁇  Give three tips for staying healthy.
1. Eat a balanced diet. 2. Exercise regularly. 3. Get enough sleep.
1. What is the best way to stay healthy?
2. What are some tips for staying healthy?
3. How can I stay healthy?
4. What are some ways to stay healthy?
5. How can I maintain my health?
6. What are some healthy habits?
7. What are some healthy lifestyle choices?
8. How can I improve my health?`

**Comment by jiazhihao** [comment]
It seems this PR has passed CI. @xinhaoc @goliaro do you think we can merge it to the inference branch now? In this case, we will add LLaMA 2 support on the Python side later.

**Comment by xinhaoc** [comment]
One more thing to do, the quantization is not supported yet.

**Comment by xinhaoc** [comment]
and do you think we should fix this issue #908  in this branch?

**Comment by jiazhihao** [comment]
We can add the quantization support in a separate PR.

**Comment by jiazhihao** [comment]
> We can add the quantization support in a separate PR.

If the fix is not too hard, I think it's a good idea to fix them in this PR.

**Review by goliaro — APPROVED** [review]

**Pull request merged**
