### PR TITLE
Local allocator

### PR DESCRIPTION
**Pull request by reyna-abhyankar**
**Description of changes:**

Local and tracked allocator 

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1386)

### CODE REVIEW

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1386)* status: all files reviewed, 1 unresolved discussion (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/tracked_allocator.h` line 8 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1386#-NxsLYKQD8jYQUGFtGMz:-NxsLYKRCKe0tG9RJAmf:b-zb5p0f) ([raw file](https://github.com/flexflow/FlexFlow/blob/931b47c4bf710c85d3b9fb6cc09e8a3e6a7d1306/lib/local-execution/include/tracked_allocator.h#L8)):*
> ```objc
> namespace FlexFlow {
> 
> struct TrackedAllocator : public Allocator {
> ```

`TrackedAllocator` should inherit from `IAllocator`. The way you have it implemented I think you're not actually overriding `allocate`, `deallocate`, etc. because they're not virtual, and making them virtual creates more problems than it solves. If you inherit from `IAllocator` then you can have an `Allocator` that holds a pointer to a `TrackedAllocator` which has a member which is an `Allocator` which holds a pointer to whatever the underlying allocator type is, which should behave correctly I think

**Review by reyna-abhyankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1386)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @lockshaw)

___
*[`lib/local-execution/include/tracked_allocator.h` line 8 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1386#-NxsLYKQD8jYQUGFtGMz:-NyWtWdO7OwGUULYqrf3:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/931b47c4bf710c85d3b9fb6cc09e8a3e6a7d1306/lib/local-execution/include/tracked_allocator.h#L8)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`TrackedAllocator` should inherit from `IAllocator`. The way you have it implemented I think you're not actually overriding `allocate`, `deallocate`, etc. because they're not virtual, and making them virtual creates more problems than it solves. If you inherit from `IAllocator` then you can have an `Allocator` that holds a pointer to a `TrackedAllocator` which has a member which is an `Allocator` which holds a pointer to whatever the underlying allocator type is, which should behave correctly I think
</blockquote></details>

Done.

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1386)* status: all files reviewed, 1 unresolved discussion (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/tracked_allocator.h` line 8 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1386#-NxsLYKQD8jYQUGFtGMz:-NyfTwxJ6FHrL3DL01Dg:bli1f49) ([raw file](https://github.com/flexflow/FlexFlow/blob/931b47c4bf710c85d3b9fb6cc09e8a3e6a7d1306/lib/local-execution/include/tracked_allocator.h#L8)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`TrackedAllocator` should wrap another allocator, rather than hardcoding in its own allocation logic, i.e., `TrackedAllocator` should have a field of type `Allocator`

**Review by reyna-abhyankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1386)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @lockshaw)

___
*[`lib/local-execution/include/tracked_allocator.h` line 8 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1386#-NxsLYKQD8jYQUGFtGMz:-NyxUL6c9zAv6LfHA-Ee:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/931b47c4bf710c85d3b9fb6cc09e8a3e6a7d1306/lib/local-execution/include/tracked_allocator.h#L8)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`TrackedAllocator` should wrap another allocator, rather than hardcoding in its own allocation logic, i.e., `TrackedAllocator` should have a field of type `Allocator`
</blockquote></details>

Done.

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1386)* status: all files reviewed, 1 unresolved discussion (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/tracked_allocator.h` line 25 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1386#-NyxV5hZ0dXIpN09yb4r:-NyxV5hZ0dXIpN09yb4s:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/44f2386d419bb02c53e08bf7d952a9a194383d9a/lib/local-execution/include/tracked_allocator.h#L25)):*
> ```objc
> CHECK_RC_COPY_VIRTUAL_COMPLIANT(TrackedAllocator);
> 
> Allocator get_tracked_memory_allocator(Allocator base_allocator);
> ```





_Suggestion:_
```objc
Allocator get_tracked_memory_allocator(Allocator const &base_allocator);
```

**Review by reyna-abhyankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1386)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @lockshaw)

___
*[`lib/local-execution/include/tracked_allocator.h` line 25 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1386#-NyxV5hZ0dXIpN09yb4r:-NyxarMcBsO8vO09RgB2:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/44f2386d419bb02c53e08bf7d952a9a194383d9a/lib/local-execution/include/tracked_allocator.h#L25)):*
> ```objc
> CHECK_RC_COPY_VIRTUAL_COMPLIANT(TrackedAllocator);
> 
> Allocator get_tracked_memory_allocator(Allocator base_allocator);
> ```

Done.

**Review by lockshaw — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1386)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @reyna-abhyankar)

**Pull request merged**
