### PR TITLE
[Inference] Prepare batch for speculative inference

### PR DESCRIPTION
**Pull request by zwang86**
**Description of changes:**
Add three prepare batch functions:
```
  BeamSearchBatchConfig
      prepare_next_batch_beam(BeamSearchBatchConfig const &old_bc,
                              BeamInferenceResult const &result);

  BeamSearchBatchConfig
      prepare_next_batch_init(TreeVerifyBatchConfig const &old_bc,
                              InferenceResult const &result);

  TreeVerifyBatchConfig
      prepare_next_batch_verify(BeamSearchBatchConfig const &old_bc);
```

Add two tree traverse helper:
```
  std::vector<std::pair<BatchConfig::TokenId, int>>
      traverse_beam_tree(BeamSearchBatchConfig const &old_bc, 
                          int request_index);

  std::vector<std::pair<BatchConfig::TokenId, int>> 
      traverse_verify_tree(std::vector<std::pair<BatchConfig::TokenId, int>> &inputSerializedTree,
                           std::vector<std::pair<BatchConfig::TokenId, int>> &outputSerializedTree);
```

**Related Issues:**
ToDos:
- [X] Split verified results for each result from InferenceResult (we need to distinguish prompt tokens from Beam Tree Tokens)
- [ ] Store Beam Search Setting (width, max_depth) during VerifyTree Phase
- [X] Store committed tokens info during the Speculation Phase
- [X] Handle prompt tokens in the first iteration with Tree Verify Batch Config
- [ ] Testing with updated inference task
- [ ] Clean up code

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

### CODE REVIEW

**Comment by zwang86** [comment]
Prompt:
```
[Token] Request Index: 0, Abs Depth: 0, Token Id: 1
[Token] Request Index: 0, Abs Depth: 1, Token Id: 306
[Token] Request Index: 0, Abs Depth: 2, Token Id: 4658
[Token] Request Index: 0, Abs Depth: 3, Token Id: 278
[Token] Request Index: 0, Abs Depth: 4, Token Id: 6593
[Token] Request Index: 0, Abs Depth: 5, Token Id: 310
[Token] Request Index: 0, Abs Depth: 6, Token Id: 2834
[Token] Request Index: 0, Abs Depth: 7, Token Id: 338
```

DFS Tree to verify:
```
[Token] Request Index: 0, Abs Depth: 8, Token Id: 593
[Token] Request Index: 0, Abs Depth: 9, Token Id: 595
[Token] Request Index: 0, Abs Depth: 10, Token Id: 17252
[Token] Request Index: 0, Abs Depth: 11, Token Id: 5031
[Token] Request Index: 0, Abs Depth: 12, Token Id: 993
[Token] Request Index: 0, Abs Depth: 13, Token Id: 616
[Token] Request Index: 0, Abs Depth: 14, Token Id: 368
[Token] Request Index: 0, Abs Depth: 15, Token Id: 2302
```

Verify Result:
```
Index with old_bacth: 7
  Input: [7] 338 ---> [8] 593 
Index with old_bacth: 8
  Input: [8] 593 ---> [9] 595 
Index with old_bacth: 9
  Input: [9] 595 ---> [10] 17252 
Index with old_bacth: 10
  Input: [10] 17252 ---> [11] 19924 
Index with old_bacth: 11
  Input: [11] 5031 ---> [12] 10070 
Index with old_bacth: 12
  Input: [12] 993 ---> [13] 616 
Index with old_bacth: 13
  Input: [13] 616 ---> [14] 368 
Index with old_bacth: 14
  Input: [14] 368 ---> [15] 8071 
Index with old_bacth: 15
  Input: [15] 2302 ---> [16] 3204 
```

Verified Results
```
(338, 7)
(593, 8)
(595, 9)
(17252, 10)
(19924, 11)
```

Committed Results Depth (abs_depth_in_request, in_batch_offset)
```
(7, 7)
(8, 8)
(9, 9)
(10, 10)
```

**Comment by zwang86** [comment]
**Second Iteration**

Verify Result:
```
Index with old_bacth: 0
  Input: [11] 19924 ---> [12] 8612 
Index with old_bacth: 1
  Input: [12] 5970 ---> [13] 2222 
Index with old_bacth: 2
  Input: [13] 2222 ---> [14] 2264 
Index with old_bacth: 3
  Input: [14] 2264 ---> [15] 267 
Index with old_bacth: 4
  Input: [15] 267 ---> [16] 25009 
Index with old_bacth: 5
  Input: [16] 24510 ---> [17] 1230 
Index with old_bacth: 6
  Input: [17] 1230 ---> [18] 19550 
Index with old_bacth: 7
  Input: [18] 21487 ---> [19] 719 
Index with old_bacth: 8
  Input: [19] 3011 ---> [20] 6997 
```

Verified Results (Token ID, Abs Depth)
```
(8612, 12)
```

Committed Results Depth (abs_depth_in_request, in_batch_offset)
```
(11, 0)
```

**Comment by zwang86** [comment]
**Third Iteration**

DFS Tree to verify:
```
[Token] Request Index: 0, Abs Depth: 12, Token Id: 8612
[Token] Request Index: 0, Abs Depth: 13, Token Id: 277
[Token] Request Index: 0, Abs Depth: 14, Token Id: 2153
[Token] Request Index: 0, Abs Depth: 15, Token Id: 7787
[Token] Request Index: 0, Abs Depth: 16, Token Id: 1259
[Token] Request Index: 0, Abs Depth: 17, Token Id: 3129
[Token] Request Index: 0, Abs Depth: 18, Token Id: 2708
[Token] Request Index: 0, Abs Depth: 19, Token Id: 6463
[Token] Request Index: 0, Abs Depth: 20, Token Id: 3669
```

Verify Result:
```
Index with old_bacth: 0
  Input: [12] 8612 ---> [13] 16217 
Index with old_bacth: 1
  Input: [13] 277 ---> [14] 2153 
Index with old_bacth: 2
  Input: [14] 2153 ---> [15] 28765 
Index with old_bacth: 3
  Input: [15] 7787 ---> [16] 1259 
Index with old_bacth: 4
  Input: [16] 1259 ---> [17] 3391 
Index with old_bacth: 5
  Input: [17] 3129 ---> [18] 15931 
Index with old_bacth: 6
  Input: [18] 2708 ---> [19] 3095 
Index with old_bacth: 7
  Input: [19] 6463 ---> [20] 292 
Index with old_bacth: 8
  Input: [20] 3669 ---> [21] 15470 
```

Verified Results (Token ID, Abs Depth)
```
(16217, 13)
```

Committed Results Depth (abs_depth_in_request, in_batch_offset)
```
(12, 0)
```

**Comment by zwang86** [comment]
**Decoding for first 25 tokens (without prompt token)**
Matches with Beam Search
```
decoding_tokens[7] = 593
decoding_tokens[8] = 595
decoding_tokens[9] = 17252
decoding_tokens[10] = 5031
decoding_tokens[11] = 993
decoding_tokens[12] = 616
decoding_tokens[13] = 368
decoding_tokens[14] = 2302
decoding_tokens[15] = 3204
decoding_tokens[16] = 29131
decoding_tokens[17] = 2976
decoding_tokens[18] = 11285
decoding_tokens[19] = 8930
decoding_tokens[20] = 635
decoding_tokens[21] = 8519
decoding_tokens[22] = 593
decoding_tokens[23] = 595
decoding_tokens[24] = 17252
```

**Comment by zwang86** [comment]
@jiazhihao @gabrieleoliaro  
It seems like that after the second iteration, the tree verification produces mismatched results. But if we init all tokens and feed them to the TreeModel, the results are aligned.
decoding_ tokens  o  = 917
verifytokens ol

So I guess it's probably that the committed token part went wrong.

For the first iteration:
We have prompt tokens:
```
[Token] Request Index: 0, Abs Depth: 0, Token Id: 1
[Token] Request Index: 0, Abs Depth: 1, Token Id: 306
[Token] Request Index: 0, Abs Depth: 2, Token Id: 4658
[Token] Request Index: 0, Abs Depth: 3, Token Id: 278
[Token] Request Index: 0, Abs Depth: 4, Token Id: 6593
[Token] Request Index: 0, Abs Depth: 5, Token Id: 310
[Token] Request Index: 0, Abs Depth: 6, Token Id: 2834
[Token] Request Index: 0, Abs Depth: 7, Token Id: 338
```
And Beam Speculation Tokens:
```
[Token] Request Index: 0, Abs Depth: 8, Token Id: 593
[Token] Request Index: 0, Abs Depth: 9, Token Id: 595
[Token] Request Index: 0, Abs Depth: 10, Token Id: 17252
[Token] Request Index: 0, Abs Depth: 11, Token Id: 5031
[Token] Request Index: 0, Abs Depth: 12, Token Id: 993
[Token] Request Index: 0, Abs Depth: 13, Token Id: 616
[Token] Request Index: 0, Abs Depth: 14, Token Id: 368
[Token] Request Index: 0, Abs Depth: 15, Token Id: 2302
```

The tokens we send to the first TreeVerify Batch as inputs are:
```[Token] Request Index: 0, Abs Depth: 0, Token Id: 1
[Token] Request Index: 0, Abs Depth: 1, Token Id: 306
[Token] Request Index: 0, Abs Depth: 2, Token Id: 4658
[Token] Request Index: 0, Abs Depth: 3, Token Id: 278
[Token] Request Index: 0, Abs Depth: 4, Token Id: 6593
[Token] Request Index: 0, Abs Depth: 5, Token Id: 310
[Token] Request Index: 0, Abs Depth: 6, Token Id: 2834
[Token] Request Index: 0, Abs Depth: 7, Token Id: 338
[Token] Request Index: 0, Abs Depth: 8, Token Id: 593
[Token] Request Index: 0, Abs Depth: 9, Token Id: 595
[Token] Request Index: 0, Abs Depth: 10, Token Id: 17252
[Token] Request Index: 0, Abs Depth: 11, Token Id: 5031
[Token] Request Index: 0, Abs Depth: 12, Token Id: 993
[Token] Request Index: 0, Abs Depth: 13, Token Id: 616
[Token] Request Index: 0, Abs Depth: 14, Token Id: 368
[Token] Request Index: 0, Abs Depth: 15, Token Id: 2302```

I tried three sets of different committed tokens: 
1. one includes the prompt, so we have all 16 tokens in `committed_tokens`:
```
[Commit] Request Index: 0, Abs Depth: 0, Token Index in batch: 0
[Commit] Request Index: 0, Abs Depth: 1, Token Index in batch: 1
[Commit] Request Index: 0, Abs Depth: 2, Token Index in batch: 2
[Commit] Request Index: 0, Abs Depth: 3, Token Index in batch: 3
[Commit] Request Index: 0, Abs Depth: 4, Token Index in batch: 4
[Commit] Request Index: 0, Abs Depth: 5, Token Index in batch: 5
[Commit] Request Index: 0, Abs Depth: 6, Token Index in batch: 6
[Commit] Request Index: 0, Abs Depth: 7, Token Index in batch: 7
[Commit] Request Index: 0, Abs Depth: 8, Token Index in batch: 8
[Commit] Request Index: 0, Abs Depth: 9, Token Index in batch: 9
[Commit] Request Index: 0, Abs Depth: 10, Token Index in batch: 10
[Commit] Request Index: 0, Abs Depth: 11, Token Index in batch: 11
[Commit] Request Index: 0, Abs Depth: 12, Token Index in batch: 12
[Commit] Request Index: 0, Abs Depth: 13, Token Index in batch: 13
[Commit] Request Index: 0, Abs Depth: 14, Token Index in batch: 14
[Commit] Request Index: 0, Abs Depth: 15, Token Index in batch: 15

new_bc.num_tokens_to_commit: 16
```
<img width="255" alt="Index with old bacth 0" src="https://github.com/flexflow/FlexFlow/assets/46699021/dc201ba0-e849-4fd8-86d4-e6fb094f2f79">

2. The other only includes the beam tree tokens in `committed_tokens`:
```
[Commit] Request Index: 0, Abs Depth: 8, Token Index in batch: 8
[Commit] Request Index: 0, Abs Depth: 9, Token Index in batch: 9
[Commit] Request Index: 0, Abs Depth: 10, Token Index in batch: 10
[Commit] Request Index: 0, Abs Depth: 11, Token Index in batch: 11
[Commit] Request Index: 0, Abs Depth: 12, Token Index in batch: 12
[Commit] Request Index: 0, Abs Depth: 13, Token Index in batch: 13
[Commit] Request Index: 0, Abs Depth: 14, Token Index in batch: 14
[Commit] Request Index: 0, Abs Depth: 15, Token Index in batch: 15

new_bc.num_tokens_to_commit: 8
```
<img width="268" alt="Index with old bacth 0" src="https://github.com/flexflow/FlexFlow/assets/46699021/f8c680ab-3f4d-4ee6-ae9e-e1343aeb5e54">


3. Include root (last prompt) and all tree tokens:
```
[Commit] Request Index: 0, Abs Depth: 7, Token Index in batch: 7
[Commit] Request Index: 0, Abs Depth: 8, Token Index in batch: 8
[Commit] Request Index: 0, Abs Depth: 9, Token Index in batch: 9
[Commit] Request Index: 0, Abs Depth: 10, Token Index in batch: 10
[Commit] Request Index: 0, Abs Depth: 11, Token Index in batch: 11
[Commit] Request Index: 0, Abs Depth: 12, Token Index in batch: 12
[Commit] Request Index: 0, Abs Depth: 13, Token Index in batch: 13
[Commit] Request Index: 0, Abs Depth: 14, Token Index in batch: 14
[Commit] Request Index: 0, Abs Depth: 15, Token Index in batch: 15

new_bc.num_tokens_to_commit: 9
```
<img width="321" alt="Index with old bacth" src="https://github.com/flexflow/FlexFlow/assets/46699021/d0ca2948-cf19-4d8d-9a5f-3bd346d3056d">


But all of them produce the exact same result:
The only mismatch occurs in depth 19, all other tokens are matched.  Any idea of what might go wrong? Is there a way to test committed tokens only?

**Comment by jiazhihao** [comment]
This seems like a bug in the TreeVerifyMHA. We can first merge this PR if we don't see any issues with RequestManager at this point.

**Pull request merged**
