### PR TITLE
Support multiple FFModels in inference

### PR DESCRIPTION
**Pull request by jiazhihao**
**Description of changes:**

* The SPEC_LLAMA/llama.cc example can now support multiple FFModels
* I have also moved the model constructor to models/llama.h to allow reuse across different examples
* @zwang86 The `RequestManager::convert_beam_to_tree_batch_config` function in request_manager.cc is to test alignment between beam_search and tree_verify models; it cannot be directly used in our pipeline. Feel free to remove it if needed.

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

### CODE REVIEW

**Comment by jiazhihao** [comment]
@zwang86 @xinhaoc I encountered a misalignment when testing the beam_search and tree_verify versions of the LLAMA example, you can reproduce the result using 
```
./examples/cpp/inference/SPEC_LLAMA/SPEC_LLAMA -ll:gpu 1 -ll:fsize 14000 -ll:zsize 12000 --only-data-parallel --weights ../examples/cpp/inference/LLAMA/weights/
```

In this example, the prompt is `{1,  306, 4658,  278, 6593,  310, 2834,  338}`. When performing speculative inference with a beam width of 1 and beam depth of 8, the speculated tokens are `{593, 595, 17252, 5031, 993, 616, 368, 2302}`. I concatenated these two token sequences and send `{1,  306, 4658,  278, 6593,  310, 2834,  338, 593, 595, 17252, 5031, 993, 616, 368, 2302}` to both the tree_verify and inc_decoding LLAMA for verification, the corresponding outputs are 
```
decoding_tokens[0] = 17345
decoding_tokens[1] = 18513
decoding_tokens[2] = 5208
decoding_tokens[3] = 31766
decoding_tokens[4] = 1319
decoding_tokens[5] = 31017
decoding_tokens[6] = 2149
decoding_tokens[7] = 593
decoding_tokens[8] = 595
decoding_tokens[9] = 17252
decoding_tokens[10] = 19924
decoding_tokens[11] = 10070
decoding_tokens[12] = 616
decoding_tokens[13] = 368
decoding_tokens[14] = 8071
decoding_tokens[15] = 3204
```
This is the token sequence generated by the original IncMultiHeadAttention operator. The TreeIncMultiHeadAttention-based LLAMA generates the exact same result. However, only the first three tokens match the beam search result:
```
decoding_tokens[7] = 593
decoding_tokens[8] = 595
decoding_tokens[9] = 17252
```

Do you think you have enough information to investigate why this happens?

**Comment by xinhaoc** [comment]
oh sorry, I missed it. there is an unresolved thing inside the attention kernel. the difference is in 
[normal attention](https://github.com/flexflow/FlexFlow/blob/inference/src/ops/inc_multihead_self_attention.cu#LL37C3-L38C35)
and [spec attention](https://github.com/flexflow/FlexFlow/blob/inference/src/ops/spec_inc_multihead_self_attention.cu#L37-L39)
I can only achieve alignment with llama using the later version.

**Comment by jiazhihao** [comment]
@xinhaoc Can you elaborate the issue more? The bug is in the normal attention?

**Comment by xinhaoc** [comment]
Before I talked this with Gabriele, But haven't got an agreement. I can't achieve alignment with the normal code. 
I saw the attention weights shape is 32 * (4096 * 128 * 4), so there seems no problem with the "shape", just see it as a single dimension array? @gabrieleoliaro

**Comment by jiazhihao** [comment]
Interesting. Note that the three variants of IncMHA currently use different code path. Could it be the case that we have fixed the issue in SpecInfMHA but haven't pushed the fix to the other two operators?

**Comment by xinhaoc** [comment]
I am not very sure about that, In my opinion the SpecInfMHA version make sense. But I may misunderstand something. Would you like first try the three kernels with same implementation? I can find a time to discuss it with Gabriele

**Comment by gabrieleoliaro** [comment]
@xinhaoc what is the data layout of the attention weights (and, in particular, the output projection weights) in the LLAMA checkpoint file?

**Comment by xinhaoc** [comment]
it is in column major, when I load the weights, just like visiting a single dimension array.

**Comment by gabrieleoliaro** [comment]
I think the problem might be that the output projection weight is stored with layout `oProjSize x vProjSize` in the checkpoint, but we store it in `vProjSize x oProjSize` in our combined attention weight

**Pull request merged**
