### PR TITLE
Add `DataflowGraph` and fix part of `substitutions`

### LINKED ISSUE #1341: proj support for local doxygen rendering
Add a flag/subcommand to https://github.com/lockshaw/proj render (and an additional flag to optionally view) doxygen docs locally. `doxygen` should also be added to https://github.com/flexflow/FlexFlow/blob/6e520bbafd93564b0643472f6930211b57b107b5/flake.nix#L112 so it's included in the developer (i.e., `default`) shell for those following https://github.com/flexflow/sapling-guide.

### PR DESCRIPTION
**Pull request by lockshaw**
**Description of changes:**

Also adds `proj doxygen` support.

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #1341

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1449)

### CODE REVIEW

**Review by wmdi — CHANGES_REQUESTED** [review]
> Reviewed 304 of 493 files at r1, 263 of 445 files at r2, 170 of 181 files at r3, 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1449)* status: all files reviewed, 1 unresolved discussion (waiting on @lockshaw and @Marsella8)

___
*[`lib/substitutions/include/substitutions/substitution.h` line 12 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1449#-O347PTS6s62Go1Vf0OO:-O347PTT5mLcfc1u5SiZ:b5u1feo) ([raw file](https://github.com/flexflow/FlexFlow/blob/ce0234dfaf503206b22523bdcf44b21e61b696ab/lib/substitutions/include/substitutions/substitution.h#L12)):*
> ```objc
> bool is_valid_substitution(Substitution const &);
> 
> SubParallelComputationGraph
> ```

Could you also add simple descriptions for the main functions? I feel like each time I need to recall their definition for a while.

**Review by lockshaw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1449)* status: 750 of 760 files reviewed, 1 unresolved discussion (waiting on @Marsella8, @reyna-abhyankar, and @wmdi)

___
*[`lib/substitutions/include/substitutions/substitution.h` line 12 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1449#-O347PTS6s62Go1Vf0OO:-O36PQw6AI4yO5pjGvSx:bqmjwcm) ([raw file](https://github.com/flexflow/FlexFlow/blob/ce0234dfaf503206b22523bdcf44b21e61b696ab/lib/substitutions/include/substitutions/substitution.h#L12)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Could you also add simple descriptions for the main functions? I feel like each time I need to recall their definition for a while.
</blockquote></details>

Added!

**Review by wmdi — COMMENTED** [review]
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1449)* status: all files reviewed, 1 unresolved discussion (waiting on @Marsella8 and @reyna-abhyankar)

**Review by wmdi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1449)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marsella8 and @reyna-abhyankar)

**Pull request merged**
