### PR TITLE
Graph Documentation

### PR DESCRIPTION
**Pull request by Marsella8**
**Description of changes:**

Added graph inheritance diagram, updated README.md

**Related Issues:**

Linked Issues:
- Issue #1383 

Issues closed by this PR:
- Closes #

Issues closed by this PR:
- Closes #1383

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1391)

### CODE REVIEW

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1391)* status: all files reviewed, 4 unresolved discussions (waiting on @Marsella8 and @wmdi)

___
*[`lib/utils/include/utils/graph/README.md` line 190 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1391#-NyhrZ-u-ZecLwq0Rn6D:-NyhrZ-v3hsH5U14vR-X:bez4ojm) ([raw file](https://github.com/flexflow/FlexFlow/blob/1b6846a61b2ef3050110583b0269fa6b8a91acb1/lib/utils/include/utils/graph/README.md#L190)):*
> ```Markdown
> Open graphs inheritance diagram
> 
> Arrows with pointed tips indicate inheritance, while arrows with square tips indicate that the pointing class has a 'cow_ptr' of the type of the pointed class. (for more info on `cow_ptr`, see below).
> ```

FYI I think you can actually do section references in markdown, e.g., see [below](#cow_ptr-and-interfaces) or something like that



_Code quote:_
```Markdown
see below).
```
___
*[`lib/utils/include/utils/graph/README.md` line 244 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1391#-NyhsNpcC347cqOQCSMw:-NyhsNpcC347cqOQCSMx:b-319vv9) ([raw file](https://github.com/flexflow/FlexFlow/blob/1b6846a61b2ef3050110583b0269fa6b8a91acb1/lib/utils/include/utils/graph/README.md#L244)):*
> ```Markdown
> 
> 
> ### Virtual Inheritance (Possibly superflous)
> ```

No this is useful, I would just add an example of the diamond inheritance that shows up rather than just claiming that "diamond-style inheritance patterns emerge"--if they emerge it should be easy to add a quick example



_Code quote:_
```Markdown
 (Possibly superflous)
```
___
*[`lib/utils/include/utils/graph/README.md` line 248 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1391#-NyhsEzs6j-0-8lQmC3e:-NyhsEzs6j-0-8lQmC3f:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/1b6846a61b2ef3050110583b0269fa6b8a91acb1/lib/utils/include/utils/graph/README.md#L248)):*
> ```Markdown
> In the case of a diamond inheritance pattern C++ will instantiate multiple copies of the base class whenever we instantiate a derived class.
> To address this issue, we employ [Virtual Inheritance](https://en.wikipedia.org/wiki/Virtual_inheritance), which removes the ambiguity associated with the multiple copies.
> Furthermore, the use of virtual functions allows for runtime polymorphism, allowing for a single function defined on some superclass to also work correctly on it's subclasses.
> ```





_Suggestion:_
```Markdown
its 
```
___
*[`lib/utils/include/utils/graph/README.md` line 252 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1391#-NyhsH_A3kXprwpDJdNr:-NyhsH_A3kXprwpDJdNs:b16pqhq) ([raw file](https://github.com/flexflow/FlexFlow/blob/1b6846a61b2ef3050110583b0269fa6b8a91acb1/lib/utils/include/utils/graph/README.md#L252)):*
> ```Markdown
> ### strong_typedef
> `Node` inherits from `strong_typedef`: this is in order to ensure that distinct types that alias the same type are still considered distinct (and thus using one in place of the other will result in a compiler error).  
> For more info, see https://www.foonathan.net/2016/10/strong-typedefs/.
> ```

Probably delete this, we're going to remove `strong_typedef` soon



_Code quote:_
```Markdown
### strong_typedef
`Node` inherits from `strong_typedef`: this is in order to ensure that distinct types that alias the same type are still considered distinct (and thus using one in place of the other will result in a compiler error).
For more info, see https://www.foonathan.net/2016/10/strong-typedefs/.
```
___
*[`lib/utils/include/utils/graph/docs/generate_diagram.py` line 79 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1391#-Nyht9I_0FvsXRsr5wU8:-Nyht9I_0FvsXRsr5wU9:btl30pg) ([raw file](https://github.com/flexflow/FlexFlow/blob/1b6846a61b2ef3050110583b0269fa6b8a91acb1/lib/utils/include/utils/graph/docs/generate_diagram.py#L79)):*
> ```Python
> 
> if __name__=='__main__':
>     cmd = 'hpp2plantuml -i "../labelled/*.h"'
> ```

I don't think `hpp2plantuml` is in the nix environment. It should be added to the `flake.nix` alongside a brief explanation of how to run this script

**Review by Marsella8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1391)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/utils/include/utils/graph/README.md` line 244 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1391#-NyhsNpcC347cqOQCSMw:-NzBxb3q6H46qSBRGC11:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/1b6846a61b2ef3050110583b0269fa6b8a91acb1/lib/utils/include/utils/graph/README.md#L244)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

No this is useful, I would just add an example of the diamond inheritance that shows up rather than just claiming that "diamond-style inheritance patterns emerge"--if they emerge it should be easy to add a quick example
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/README.md` line 248 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1391#-NyhsEzs6j-0-8lQmC3e:-NzBxhKJ8CSVKu6lATvz:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/1b6846a61b2ef3050110583b0269fa6b8a91acb1/lib/utils/include/utils/graph/README.md#L248)):*
> ```Markdown
> In the case of a diamond inheritance pattern C++ will instantiate multiple copies of the base class whenever we instantiate a derived class.
> To address this issue, we employ [Virtual Inheritance](https://en.wikipedia.org/wiki/Virtual_inheritance), which removes the ambiguity associated with the multiple copies.
> Furthermore, the use of virtual functions allows for runtime polymorphism, allowing for a single function defined on some superclass to also work correctly on it's subclasses.
> ```

Done.
___
*[`lib/utils/include/utils/graph/README.md` line 252 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1391#-NyhsH_A3kXprwpDJdNr:-NzBxidl9u7DGT0rUbX_:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/1b6846a61b2ef3050110583b0269fa6b8a91acb1/lib/utils/include/utils/graph/README.md#L252)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably delete this, we're going to remove `strong_typedef` soon
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/docs/generate_diagram.py` line 79 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1391#-Nyht9I_0FvsXRsr5wU8:-NzCc4L23ZcmMAnmC9Pb:b-u7fatg) ([raw file](https://github.com/flexflow/FlexFlow/blob/1b6846a61b2ef3050110583b0269fa6b8a91acb1/lib/utils/include/utils/graph/docs/generate_diagram.py#L79)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't think `hpp2plantuml` is in the nix environment. It should be added to the `flake.nix` alongside a brief explanation of how to run this script
</blockquote></details>

I've ended up retooling the script to make it use hpp2plantuml as a python module instead of calling it through the command line so that it's easier to setup within nix, but I was unable to set it up (it's not present in nixpkgs, and had tried some other methods but was unsuccesful), let me know how to proceed.

**Review by Marsella8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1391)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/utils/include/utils/graph/README.md` line 244 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1391#-NyhsNpcC347cqOQCSMw:-NzCcxzR27Gh91RD9w6j:b-vrgewi) ([raw file](https://github.com/flexflow/FlexFlow/blob/1b6846a61b2ef3050110583b0269fa6b8a91acb1/lib/utils/include/utils/graph/README.md#L244)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I've looked around the Graph Library and was surprisingly there are actually no diamond-style inheritance patterns present (at least in the strict sense, so without considering a given class having a cow_ptr to another class as inheritance).
The reason virtual inheritance is still needed however is because we still want to keep a single copy of the superclasses, since while we don't access them using inheritance we still access them using cow_ptrs right? I've currently added this as an explanation to the graph docs, but I'm unsure on whether it is correct, lmk if I'm wrong and if so what is the purpose of virtual inheritance within the library.

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1391)* status: all files reviewed, 2 unresolved discussions (waiting on @Bob-Chen222, @Marsella8, and @wmdi)

___
*[`lib/utils/include/utils/graph/README.md` line 244 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1391#-NyhsNpcC347cqOQCSMw:-NzEimY95PlyieuUzNSl:b-6i2t1x) ([raw file](https://github.com/flexflow/FlexFlow/blob/1b6846a61b2ef3050110583b0269fa6b8a91acb1/lib/utils/include/utils/graph/README.md#L244)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

I've looked around the Graph Library and was surprisingly there are actually no diamond-style inheritance patterns present (at least in the strict sense, so without considering a given class having a cow_ptr to another class as inheritance).
The reason virtual inheritance is still needed however is because we still want to keep a single copy of the superclasses, since while we don't access them using inheritance we still access them using cow_ptrs right? I've currently added this as an explanation to the graph docs, but I'm unsure on whether it is correct, lmk if I'm wrong and if so what is the purpose of virtual inheritance within the library.
</blockquote></details>

I believe there are some, e.g., https://github.com/flexflow/FlexFlow/blob/411bc12dd47a8fe6fff3c434061cfae28f88dd88/lib/utils/include/utils/graph/labelled/output_labelled_open.h#L11-L12 (which both inherit eventually from `NodeLabelledMultiDiGraphView`, among others)

Also, I'm not sure I'd describe holding a `cow_ptr` as inheritance--describing the non-I classes as `handle`s might be better? 
___
*[`lib/utils/include/utils/graph/docs/generate_diagram.py` line 79 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1391#-Nyht9I_0FvsXRsr5wU8:-NzEhZdA4GEJogfehAIr:bxih0dv) ([raw file](https://github.com/flexflow/FlexFlow/blob/1b6846a61b2ef3050110583b0269fa6b8a91acb1/lib/utils/include/utils/graph/docs/generate_diagram.py#L79)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

I've ended up retooling the script to make it use hpp2plantuml as a python module instead of calling it through the command line so that it's easier to setup within nix, but I was unable to set it up (it's not present in nixpkgs, and had tried some other methods but was unsuccesful), let me know how to proceed.
</blockquote></details>

@Bob-Chen222 Can you add a nix derivation for https://github.com/thibaultmarin/hpp2plantuml to the flake as part of this PR, similar to what we do with legion since legion isn't in `nixpkgs`? It's installable through pypi, so this should be pretty trivial--you can find examples in https://github.com/lockshaw/sp/blob/790e63952a06080ce9c4a888c5a5080dbd50f429/flake.nix#L20-L50

**Review by Marsella8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1391)* status: all files reviewed, 2 unresolved discussions (waiting on @Bob-Chen222, @lockshaw, and @wmdi)

___
*[`lib/utils/include/utils/graph/README.md` line 244 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1391#-NyhsNpcC347cqOQCSMw:-NzFySDG8oWYWpbrWPCW:b-404aco) ([raw file](https://github.com/flexflow/FlexFlow/blob/1b6846a61b2ef3050110583b0269fa6b8a91acb1/lib/utils/include/utils/graph/README.md#L244)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I believe there are some, e.g., https://github.com/flexflow/FlexFlow/blob/411bc12dd47a8fe6fff3c434061cfae28f88dd88/lib/utils/include/utils/graph/labelled/output_labelled_open.h#L11-L12 (which both inherit eventually from `NodeLabelledMultiDiGraphView`, among others)

Also, I'm not sure I'd describe holding a `cow_ptr` as inheritance--describing the non-I classes as `handle`s might be better?
</blockquote></details>

Ah yes, thanks for the catch, I'll update the docs acccordingly

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1391)* status: all files reviewed, 1 unresolved discussion (waiting on @Bob-Chen222 and @wmdi)

**Review by lockshaw — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1391)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wmdi)

**Pull request merged**
