### PR TITLE
Initial draft of operator docs

### LINKED ISSUE #1310: Add high-level new developer docs for repo-refactor operator interface

### PR DESCRIPTION
**Pull request by abisatish**
**Description of changes:**
Documented the main functions in operators

**Related Issues:**

Linked Issues:
- Issue # 

Issues closed by this PR:
- Closes #1310

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1311)

### CODE REVIEW

**Review by lockshaw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1311)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @abisatish and @reyna-abhyankar)

___
*[`lib/runtime/src/ops/README.md` line 8 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1311#-NrOTUTJ8xsWL8a90b6R:-NrOTUTJ8xsWL8a90b6S:b-2zi805) ([raw file](https://github.com/flexflow/FlexFlow/blob/df749cd6cdb1c9d9cdd7b5fd77e09d906171915c/lib/runtime/src/ops/README.md#L8)):*
> ```Markdown
> ## Slots
> 
> The Operator takes tensor inputs and outputs other tensors. The input tensors’ attributes and type need to be specified in the form of Slots, which has traits distinguished by an enumerator.
> ```

Great first PR! :slightly_smiling_face:

**Review by abisatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1311)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/runtime/src/ops/README.md` line 8 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1311#-NrOTUTJ8xsWL8a90b6R:-NrOU1Ee89Mf8GD93_ru:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/df749cd6cdb1c9d9cdd7b5fd77e09d906171915c/lib/runtime/src/ops/README.md#L8)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Great first PR! :slightly_smiling_face:
</blockquote></details>

Done.

**Review by lockshaw — CHANGES_REQUESTED** [review]
I think it would help to walk the reader through implementing a new operator rather than just including excerpts of existing operators. I would recommend using a simpler operation, for example walk the programmer through implementing a new operator that takes in three tensors and adds them all together. In addition, there's a lot of conceptual framing that's currently missing--what are "slots"? What are signatures and invocations? In the construction of the bindings, there aren't actually any tensors used, just enums--why? A lot of these are analogues of function declarations, signatures, calls, etc. but that currently isn't covered--the terms are just dropped in without giving the reader an intuition for them. Same with "returns the device specific state"--that is clearly true (just from the type names), but it doesn't tell the reader anything about what should be included in that state and what shouldn't, or why it exists at all. Some of this can probably be divided between a couple different documents (for example this document probably doesn't need to cover all of the reasoning for the current design rather than just explaining how to use it) but currently it seems a bit heavy on verbatim code excerpts and a little light on "holding the reader's hand and helping them understand how to do simple things". Try to cover things that wouldn't be easily figured out by the reader just looking at the code along with a couple docstrings.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1311#-:-NrdOGLy98xqvGOdGyqC:b7q2g86)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @abisatish and @reyna-abhyankar)

___
*[`lib/runtime/src/ops/README.md` line 35 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1311#-NrdNuqXCp5vuQhqqogu:-NrdNuqXCp5vuQhqqogv:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/3659cda59fe1aa9785be6a0e071427141e2cd740/lib/runtime/src/ops/README.md#L35)):*
> ```Markdown
> ## Register Task
> 
> For the backing to use the operator, the operator needs to register its tasks with the backing. Generally, three tasks need to be registered using register_task. 
> ```





_Suggestion:_
```Markdown
For the backing to use the operator, the operator needs to register its tasks with the backing. Generally, three tasks need to be registered using register\_task.
```

**Review by reyna-abhyankar — CHANGES_REQUESTED** [review]
Agree with Colin's summary above. We don't want a user to implement an operator through mimicry rather through understanding, but this is a good first start. 

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1311#-:-Nrrgf27E5hkzHfdkmyy:blyk7zl)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @abisatish and @lockshaw)

___
*[`lib/runtime/src/ops/README.md` line 94 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1311#-NrrfmT85fcrJkKIP93u:-NrrfmT85fcrJkKIP93v:b8n2jr0) ([raw file](https://github.com/flexflow/FlexFlow/blob/3659cda59fe1aa9785be6a0e071427141e2cd740/lib/runtime/src/ops/README.md#L94)):*
> ```Markdown
> ## bind vs. bind_arg
> 
> A quick note on the difference between bind vs. bind_arg: The bind method is used to associate a specific task or computation with an initial tensor. On the other hand, bind_arg has the same use, but for non-tensor values.
> ```

Some args that are necessary for all operators are profiling and attrs.
___
*[`lib/runtime/src/ops/README.md` line 118 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1311#-Nrrg0cU5_JJcT9Aptuy:-Nrrg0cU5_JJcT9Aptuz:b-psr00k) ([raw file](https://github.com/flexflow/FlexFlow/blob/3659cda59fe1aa9785be6a0e071427141e2cd740/lib/runtime/src/ops/README.md#L118)):*
> ```Markdown
> ```
> 
> Inside the implementation function (impl), all the parameters are extracted from the accessor, and the operator kernel is launched, along with all of its required tensors.
> ```

I think this could use more detail. The return type of `get_tensor`, the fact that we can specify permissions. Also in this example, if you're including the full call, explain why everything is wrapped in this `profile` call and add the missing arguments for `profiling` and `per_device_state`
___
*[`lib/runtime/src/ops/README.md` line 164 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1311#-NrrgUby28TLy1OyJPFO:-NrrgUby28TLy1OyJPFP:b-706kfm) ([raw file](https://github.com/flexflow/FlexFlow/blob/3659cda59fe1aa9785be6a0e071427141e2cd740/lib/runtime/src/ops/README.md#L164)):*
> ```Markdown
> ## X_INIT_TASK
> 
> This is a wrapper, which bundles all the tensor inputs, weights, and outputs & initializes the init kernel. It returns the device specific state.
> ```

This example is pretty unique to attention, so maybe make it clear that the init task can do anything an operator requires at initialization, including allocating memory, setting per-device state.

**Review by lockshaw — COMMENTED** [review]
> Agree with Colin's summary above. We don't want a user to implement an operator through mimicry rather through understanding, but this is a good first start.

To clarify: I'm okay with *some* mimicry (this is often unavoidable when entering a new codebase, and we don't want this document to turn into a super lengthy explanation of the whole system's design), but ideally not *all* mimcry :slightly_smiling_face: 

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1311#-:-NrrjdR4CaGbLedLWq45:bhwczll)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @abisatish and @reyna-abhyankar)

**Comment by abisatish** [comment]
Made a new commit with most of the revisions we talked about. I tried to follow a more checklist-like approach.

**Pull request closed without merging**
