### PR TITLE
Make BatchConfig and InferenceResult Legion futures

### PR DESCRIPTION
**Pull request by jiazhihao**
**Description of changes:**

In this PR, we make BatchConfig and InferenceResult Legion futures so that the top_level_task don't have to wait for a task's completion before launching new tasks. This can eliminate Legion task launch overheads. 

**Related Issues:**

Linked Issues:
- Issue #884

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

### CODE REVIEW

**Review by goliaro — APPROVED** [review]
LGTM! I'm looking into the `--fusion` error, which should be independent from this PR, since I have seen the same bug in the `inference` branch.

**Comment by zwang86** [comment]
There is still one broken change with prompt `inital_len` greater than `MAX_NUM_TOKENS` in batch. I am looking into it now.

**Comment by zwang86** [comment]
@jiazhihao Should we just discard any prompt that's longer than the `MAX_NUM_TOKENS`?

**Comment by jiazhihao** [comment]
@zwang86 We can use this as a temporary solution.

**Comment by zwang86** [comment]
I made a temporary solution that truncates the prompt to `MAX_PROMPT_LENTH`, which should be `MAX_NUM_TOKENS - 1` (the first verify phase will load the prompt tokens plus at least 1 token generated by SSM).
We can discuss that later if we need to load the prompt tokens in separate batches.

**Comment by zwang86** [comment]
Seem the change might cause misalignment between SpecInfer and incre_decoding since incre_decoding can take all 64 prompt tokens, but SpecInfer takes only 63. Let me roll back the changes and see if simply discarding long prompt requests can resolve this.
We can have a separate PR later to support long prompt request.

**Pull request merged**
