### PR TITLE
Add interface for differentiating inputs and weights in CG & PCG

### PR DESCRIPTION
**Pull request by lockshaw**
**Description of changes:**

- Also do some `PCG` and `op-attrs` test suite organizing
- Fix a bug in the `transformer` implementation (MHAs should not use `bias`) 

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1493)

### CODE REVIEW

**Review by reyna-abhyankar — CHANGES_REQUESTED** [review]
> Reviewed 75 of 75 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1493)* status: all files reviewed, 6 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/models/src/models/transformer.cc` line 93 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1493#-O6UT68H0iIPLU-2tpkF:-O6UT68H0iIPLU-2tpkG:b-uy4uf) ([raw file](https://github.com/flexflow/FlexFlow/blob/3440b3e669943b69320b092fdd1e2975dbbf5496/lib/models/src/models/transformer.cc#L93)):*
> ```cpp
>                                                          vdim,
>                                                          config.dropout,
>                                                          /*bias=*/false);
> ```

Should we make `bias` false by default?
___
*[`lib/op-attrs/include/op-attrs/ops/batch_matmul.h` line 12 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1493#-O6UTyS_8D7PcjqlqiB4:-O6UTyS_8D7PcjqlqiB5:bygv0tm) ([raw file](https://github.com/flexflow/FlexFlow/blob/3440b3e669943b69320b092fdd1e2975dbbf5496/lib/op-attrs/include/op-attrs/ops/batch_matmul.h#L12)):*
> ```objc
> namespace FlexFlow {
> 
> CHECK_VALID_OP_ATTR(BatchMatmulAttrs);
> ```

What does this do / was there any reason it wasn't there before?
___
*[`lib/pcg/include/pcg/computation_graph_builder.h` line 166 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1493#-O6UVfTk8CqARIr-WYgQ:-O6UVfTk8CqARIr-WYgR:b-touw1b) ([raw file](https://github.com/flexflow/FlexFlow/blob/3440b3e669943b69320b092fdd1e2975dbbf5496/lib/pcg/include/pcg/computation_graph_builder.h#L166)):*
> ```objc
>       std::optional<InitializerAttrs> const &bias_initializer = std::nullopt,
>       std::optional<std::string> const &name = std::nullopt,
>       std::optional<std::string> const &projection_name = std::nullopt,
> ```

why are names necessary?
___
*[`lib/pcg/src/pcg/computation_graph.cc` line 25 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1493#-O6UWhuE4dBtsKeGcSI9:-O6UWhuE4dBtsKeGcSIA:b-je69j2) ([raw file](https://github.com/flexflow/FlexFlow/blob/3440b3e669943b69320b092fdd1e2975dbbf5496/lib/pcg/src/pcg/computation_graph.cc#L25)):*
> ```cpp
> }
> 
> LayerAddedResult add_layer(ComputationGraph &computation_graph,
> ```

Why a new interface?
___
*[`lib/op-attrs/test/src/op-attrs/ops/conv_2d.cc` line 23 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1493#-O6UVPTnEqo0O6M5kuuR:-O6UVPTnEqo0O6M5kuuS:b45h) ([raw file](https://github.com/flexflow/FlexFlow/blob/3440b3e669943b69320b092fdd1e2975dbbf5496/lib/op-attrs/test/src/op-attrs/ops/conv_2d.cc#L23)):*
> ```cpp
> 
>     SUBCASE("with bias") {
>       Conv2DAttrs attrs = make_attrs(true);
> ```





_Suggestion:_
```cpp
make_attrs(/*use_bias=*/true)
```
___
*[`lib/op-attrs/test/src/op-attrs/ops/conv_2d.cc` line 37 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1493#-O6UVTBw-ewqM0kjGeWL:-O6UVTBw-ewqM0kjGeWM:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/3440b3e669943b69320b092fdd1e2975dbbf5496/lib/op-attrs/test/src/op-attrs/ops/conv_2d.cc#L37)):*
> ```cpp
> 
>     SUBCASE("without bias") {
>       Conv2DAttrs attrs = make_attrs(false);
> ```





_Suggestion:_
```cpp
make_attrs(/*use_bias=*/false)
```

**Review by lockshaw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1493)* status: 74 of 75 files reviewed, 6 unresolved discussions (waiting on @reyna-abhyankar and @wmdi)

___
*[`lib/models/src/models/transformer.cc` line 93 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1493#-O6UT68H0iIPLU-2tpkF:-O6bF3SY8O2KTXGRi3Yg:b-8kvz87) ([raw file](https://github.com/flexflow/FlexFlow/blob/3440b3e669943b69320b092fdd1e2975dbbf5496/lib/models/src/models/transformer.cc#L93)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Should we make `bias` false by default?
</blockquote></details>

Probably not, since `bias=true` is the pytorch default: https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html
___
*[`lib/op-attrs/include/op-attrs/ops/batch_matmul.h` line 12 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1493#-O6UTyS_8D7PcjqlqiB4:-O6bF7LR2AUPdBwiZEMR:b-bnnplw) ([raw file](https://github.com/flexflow/FlexFlow/blob/3440b3e669943b69320b092fdd1e2975dbbf5496/lib/op-attrs/include/op-attrs/ops/batch_matmul.h#L12)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

What does this do / was there any reason it wasn't there before?
</blockquote></details>

It just checks a couple basic properties (mainly just value/copy semantics) that honestly probably aren't all that necessary anymore now that we have an actual testing framework in place. I'll leave it in for now for consistency with the other operators, but I've created an issue to eventually go and remove them: https://github.com/flexflow/FlexFlow/issues/1498
___
*[`lib/pcg/include/pcg/computation_graph_builder.h` line 166 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1493#-O6UVfTk8CqARIr-WYgQ:-O6bG5Ks9rjHkDdslTGH:bqfzp5u) ([raw file](https://github.com/flexflow/FlexFlow/blob/3440b3e669943b69320b092fdd1e2975dbbf5496/lib/pcg/include/pcg/computation_graph_builder.h#L166)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

why are names necessary?
</blockquote></details>

For testing--currently names are the way to retrieve `layer_guid_t`s from a `ComputationGraph` built by `ComputationGraphBuilder`--see https://github.com/lockshaw/FlexFlow/blob/3440b3e669943b69320b092fdd1e2975dbbf5496/lib/pcg/test/src/pcg/computation_graph.cc#L155-L204 for an example. 

Currently there's a bit of awkwardness in that `ComputationGraphBuilder` is a bit high-level for a lot of tests (has the ability to auto-insert cast and broadcast operators, auto-create weights, etc. which makes getting `layer_guid_t`s and `tensor_guid_t`s a bit difficult and makes reasoning about what a test actually does a bit more challenging than it should be), but the low-level graph interface is often way too verbose. The solution is likely to add an interface in the middle (between `ComputationGraphBuilder` and the raw graph interface--tracked in https://github.com/flexflow/FlexFlow/issues/1499 and somewhat related to https://github.com/flexflow/FlexFlow/issues/1474), but I'm not yet ready to implement it, so for now we're using a balance of the two interfaces while I figure out a better long-term solution
___
*[`lib/pcg/src/pcg/computation_graph.cc` line 25 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1493#-O6UWhuE4dBtsKeGcSI9:-O6bFv0VC-qUR5qlRCIa:b-sonk2n) ([raw file](https://github.com/flexflow/FlexFlow/blob/3440b3e669943b69320b092fdd1e2975dbbf5496/lib/pcg/src/pcg/computation_graph.cc#L25)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Why a new interface?
</blockquote></details>

This interface actually has been there for a while, it just wasn't implemented. That said, there is good reason for having interfaces between the raw graph interface and `ComputationGraphBuilder`, as outlined in https://reviewable.io/reviews/flexflow/FlexFlow/1493#-O6UVfTk8CqARIr-WYgQ
___
*[`lib/op-attrs/test/src/op-attrs/ops/conv_2d.cc` line 23 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1493#-O6UVPTnEqo0O6M5kuuR:-O6bFsNH01p3dFfazsXP:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3440b3e669943b69320b092fdd1e2975dbbf5496/lib/op-attrs/test/src/op-attrs/ops/conv_2d.cc#L23)):*
> ```cpp
> 
>     SUBCASE("with bias") {
>       Conv2DAttrs attrs = make_attrs(true);
> ```

Done.
___
*[`lib/op-attrs/test/src/op-attrs/ops/conv_2d.cc` line 37 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1493#-O6UVTBw-ewqM0kjGeWL:-O6bFt5S3jvpsIMa1UJD:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3440b3e669943b69320b092fdd1e2975dbbf5496/lib/op-attrs/test/src/op-attrs/ops/conv_2d.cc#L37)):*
> ```cpp
> 
>     SUBCASE("without bias") {
>       Conv2DAttrs attrs = make_attrs(false);
> ```

Done.

**Review by wmdi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1493)* status: all files reviewed, 6 unresolved discussions (waiting on @reyna-abhyankar)

**Review by reyna-abhyankar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1493#-:-O6s4qCq9k4B3CZgsvym:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lockshaw)

___
*[`lib/pcg/include/pcg/computation_graph_builder.h` line 166 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1493#-O6UVfTk8CqARIr-WYgQ:-O6s4cfm4OaQU2l66Yol:bm0nnux) ([raw file](https://github.com/flexflow/FlexFlow/blob/3440b3e669943b69320b092fdd1e2975dbbf5496/lib/pcg/include/pcg/computation_graph_builder.h#L166)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

For testing--currently names are the way to retrieve `layer_guid_t`s from a `ComputationGraph` built by `ComputationGraphBuilder`--see https://github.com/lockshaw/FlexFlow/blob/3440b3e669943b69320b092fdd1e2975dbbf5496/lib/pcg/test/src/pcg/computation_graph.cc#L155-L204 for an example. 

Currently there's a bit of awkwardness in that `ComputationGraphBuilder` is a bit high-level for a lot of tests (has the ability to auto-insert cast and broadcast operators, auto-create weights, etc. which makes getting `layer_guid_t`s and `tensor_guid_t`s a bit difficult and makes reasoning about what a test actually does a bit more challenging than it should be), but the low-level graph interface is often way too verbose. The solution is likely to add an interface in the middle (between `ComputationGraphBuilder` and the raw graph interface--tracked in https://github.com/flexflow/FlexFlow/issues/1499 and somewhat related to https://github.com/flexflow/FlexFlow/issues/1474), but I'm not yet ready to implement it, so for now we're using a balance of the two interfaces while I figure out a better long-term solution
</blockquote></details>

Yeah, that's fair.

**Pull request merged**
