### PR TITLE
Add unit testing to utils

### PR DESCRIPTION
**Pull request by lockshaw**
**Description of changes:**

Combination of #842 and #851

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/940)

### CODE REVIEW

**Comment by lambda7xx** [comment]
*[`lib/utils/src/graph/hashmap_undirected_graph.cc` line 44 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/940#-Ncw5Y9JDUiap_hlIDX8:-Ncw5Y9JDUiap_hlIDX9:b-euko9h) ([raw file](https://github.com/flexflow/FlexFlow/blob/a6ed3b576bb1ee39ea39f5a271da7cc62c4c2284/lib/utils/src/graph/hashmap_undirected_graph.cc#L44)):*
> ```cpp
>   auto iter = m.find(e.smaller);
>   if (iter != m.end()) {
>     m.erase(iter);
> ```

why don't delete the e.smaller? When you add edge, you put e.bigger and e.smaller in this->adjacency



_Code snippet:_
```cpp
void HashmapUndirectedGraph::remove_edge(UndirectedEdge const &e) {
  std::unordered_set<Node> &m = this->adjacency.at(e.bigger);
  auto iter = m.find(e.smaller);
  if (iter != m.end()) {
    m.erase(iter);
  }
    std::unordered_set<Node> &m = this->adjacency.at(e.smaller);
  auto iter = m.find(e.smaller);
  if (iter != m.end()) {
    m.erase(iter);
  }
  
}
```

**Comment by lambda7xx** [comment]
*[`lib/utils/src/graph/internal.cc` line 25 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/940#-Ncw6582C6WYbbXvn_tv:-Ncw6582C6WYbbXvn_tw:b5ynf0v) ([raw file](https://github.com/flexflow/FlexFlow/blob/a6ed3b576bb1ee39ea39f5a271da7cc62c4c2284/lib/utils/src/graph/internal.cc#L25)):*
> ```cpp
>     GraphInternal::create_digraphview(std::shared_ptr<IDiGraphView const> ptr) {
>   return {std::move(ptr)};
> }
> ```

lacks two methods



_Code snippet:_
```cpp
  static MultiDiGraph create_multidigraph(std::shared_ptr<IMultiDiGraph>);
  static MultiDiGraphView
      create_multidigraphview(std::shared_ptr<IMultiDiGraphView const>);
```

**Review by lockshaw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/940)* status: 0 of 122 files reviewed, 4 unresolved discussions (waiting on @lambda7xx and @wmdi)

___
*[`lib/utils/include/utils/graph/labelled/labelled_open.h` line  at r10](https://reviewable.io/reviews/flexflow/FlexFlow/940#-NcvTTIw8nVNLwl6pMGL:-NcxcOnF0Fxfyyj5dadz:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/a6ed3b576bb1ee39ea39f5a271da7cc62c4c2284/lib/utils/include/utils/graph/labelled/labelled_open.h#L)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

miss to implement
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/hashmap_undirected_graph.cc` line 44 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/940#-Ncw5Y9JDUiap_hlIDX8:-Ncx_BjV0jHk_xKJ8lZg:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/a6ed3b576bb1ee39ea39f5a271da7cc62c4c2284/lib/utils/src/graph/hashmap_undirected_graph.cc#L44)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

why don't delete the e.smaller? When you add edge, you put e.bigger and e.smaller in this->adjacency
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/internal.cc` line 25 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/940#-Ncw6582C6WYbbXvn_tv:-Ncx_zQQ0rQ0Z1N3VOFJ:b5e8smj) ([raw file](https://github.com/flexflow/FlexFlow/blob/a6ed3b576bb1ee39ea39f5a271da7cc62c4c2284/lib/utils/src/graph/internal.cc#L25)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

lacks two methods
</blockquote></details>

They're defined a few lines above
___
*[`lib/utils/src/graph/traversal.cc` line 127 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/940#-Ncw71IfC53eXw6HY3ev:-NcxcWp_1jrBD0x9Oybp:b3txnu7) ([raw file](https://github.com/flexflow/FlexFlow/blob/a6ed3b576bb1ee39ea39f5a271da7cc62c4c2284/lib/utils/src/graph/traversal.cc#L127)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

I think we should add test for this method.
</blockquote></details>

It's currently tested by `get_bfs_ordering`. We can add step-by-step iterator specific tests, but I'll leave that to a separate PR. I've created an issue: https://github.com/flexflow/FlexFlow/issues/1039

**Comment by lambda7xx** [comment]
I approve the reivew

**Review by lambda7xx — DISMISSED** [review]
this PR can be merged

**Review by wmdi — CHANGES_REQUESTED** [review]
There are some non-template methods implemented in the head files. Is there any reason to do that way? Otherwise, I think we should implement them in the source files to avoid compilation overhead.

Moreover, in addition to manually designed test cases, it should be better to test a large amount of random and general cases through rapidcheck. We can leave it in a separate PR.

> Reviewed 3 of 26 files at r3, 7 of 64 files at r8, 99 of 112 files at r9, 2 of 2 files at r10, 10 of 10 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/940#-:-Nd27vHF82359mF2fl50:b33rol1)* status: all files reviewed, 8 unresolved discussions (waiting on @lambda7xx and @lockshaw)

___
*[`lib/utils/include/utils/graph/node.h` line 64 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/940#-Nd23rYXEwfMxxUgDQlz:-Nd23rYXEwfMxxUgDQm-:b6ylxng) ([raw file](https://github.com/flexflow/FlexFlow/blob/395df2fef3897351ea1006d83e5cd7bdc241b0b4/lib/utils/include/utils/graph/node.h#L64)):*
> ```objc
> 
> private:
>   GraphView(std::shared_ptr<IGraphView const> ptr) : ptr(ptr) {}
> ```

Why do we implement a non-template method in a head file? Won't it lead to additional compilation overhead?
___
*[`lib/utils/include/utils/graph/open_graphs.h` line 38 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/940#-Nd24VGe7pRCwdk71JYt:-Nd24VGe7pRCwdk71JYu:b-kfjdle) ([raw file](https://github.com/flexflow/FlexFlow/blob/395df2fef3897351ea1006d83e5cd7bdc241b0b4/lib/utils/include/utils/graph/open_graphs.h#L38)):*
> ```objc
> private:
>   OpenMultiDiGraphView(std::shared_ptr<IOpenMultiDiGraphView const> ptr)
>       : ptr(ptr) {}
> ```

Why do we implement a non-template method in a head file?
___
*[`lib/utils/include/utils/graph/open_graphs.h` line 70 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/940#-Nd24oTw2MiIAy3sUfc9:-Nd24oTw2MiIAy3sUfcA:bcid3i3) ([raw file](https://github.com/flexflow/FlexFlow/blob/395df2fef3897351ea1006d83e5cd7bdc241b0b4/lib/utils/include/utils/graph/open_graphs.h#L70)):*
> ```objc
>                                  OpenMultiDiGraph>::type
>       create() {
>     return make_cow_ptr<T>();
> ```

Shouldn't it be



_Code snippet:_
```objc
    return OpenMultiDiGraph(make_cow_ptr<T>());
```

**Review by wmdi — COMMENTED** [review]
> Reviewed 8 of 12 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/940)* status: 121 of 122 files reviewed, 7 unresolved discussions (waiting on @lambda7xx and @lockshaw)

**Review by wmdi — DISMISSED** [review]
> Reviewed 1 of 12 files at r13.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/940)* status: all files reviewed, 5 unresolved discussions (waiting on @lambda7xx and @lockshaw)

**Review by wmdi — APPROVED** [review]
> Reviewed 18 of 18 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/940)* status: all files reviewed, 5 unresolved discussions (waiting on @lambda7xx and @lockshaw)

**Review by wmdi — APPROVED** [review]
> Reviewed 5 of 5 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/940)* status: all files reviewed, 5 unresolved discussions (waiting on @lambda7xx and @lockshaw)

**Pull request merged**
