### PR TITLE
utilize the cuda graph to optimize the kernel overhead

### PR DESCRIPTION
**Pull request by lambda7xx**
**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1313)

### CODE REVIEW

**Comment by lambda7xx** [comment]
[inference_cudagraph_11prompt.csv](https://github.com/flexflow/FlexFlow/files/14420405/inference_cudagraph_11prompt.csv)

**Comment by lambda7xx** [comment]
| prompt | Inference  | CUDA Graph |
|-------------|----------------|-----------------|
| 1 | 1791687 | 1441660 |
|2|2212596 | 1759674 |
|3|  2234401 | 1826213 |
|4|   2315155 |1945389  |
|5| 2334711  |2003040  |
|6| 2141544  | 1767663  |
|7| 2515870  |  2240695 |
|8|  2357604 | 2027083  |
|9| 2523005  | 1863498  |
|10 | 277404  | 1916127  |
|11|  2796161 | 1982790  |

**Comment by lambda7xx** [comment]
my prompt 

[
    "Write a detailed product description for a food chopper tool that lets you chop fruits and vegetables.",
    "Write a short blog post (500 words) about the best dog toys for new dog owners.",
    "ChatGPT is rewriting Genesis.",
    "Please write the evolution of humans by natural selection in the form of a recipe.",
    "List possible Twitter messages from dinosaurs as the asteroid is about to hit the earth. List the account (with dino related puny names) having sent them in markdown bold. Then, the message itself.",
    "5 pick-up lines to say to seduce a large language model in a bar",
    "Talk to me as if you are python programming language and want to sell me yourself",
    "Tell me shortest story in the world",
    "Write podcast about importance to include ChatGPT into the evening routine.",
    "Do you use reinforcement learning?",
    "Tell me a scary four word story."
]

**Comment by jiazhihao** [comment]
@lambda7xx @SpiritedAwayCN What's the status of this PR? Should this be closed?

**Pull request closed without merging**
