### PR TITLE
[Inference] Implement Beam Search for small model speculative inference

### PR DESCRIPTION
**Pull request by zwang86**
**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #673

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

### CODE REVIEW

**Comment by jiazhihao** [comment]
@xinhaoc @zwang86 Do you think we can merge this PR to the inference branch now? Or are there still outstanding todos?

**Comment by xinhaoc** [comment]
I'll still need a few final refactor and update, it can be done before Friday night.

**Comment by zwang86** [comment]
@jiazhihao Do we want to include the trie serialization in this PR? If we want to use multiple small models is that more reasonable to build the trie outside of the beam search part from one single model?

**Comment by xinhaoc** [comment]
some reference testing data of the serializable trees.
print tree, 4
token id: 13, depth: 0
token id: 29908, depth: 1
token id: 8293, depth: 2
token id: 26567, depth: 3
token id: 19836, depth: 3
token id: 12638, depth: 3


print tree, 3
token id: 372, depth: 0
token id: 4983, depth: 1
token id: 653, depth: 2
token id: 28328, depth: 3
token id: 3304, depth: 2
token id: 983, depth: 3
token id: 2185, depth: 3


print tree, 2
token id: 297, depth: 0
token id: 445, depth: 1
token id: 3153, depth: 2
token id: 5617, depth: 3
token id: 590, depth: 1
token id: 1914, depth: 2
token id: 537, depth: 3
token id: 374, depth: 2
token id: 414, depth: 3


print tree, 1
token id: 310, depth: 0
token id: 445, depth: 1
token id: 3153, depth: 2
token id: 537, depth: 3
token id: 1907, depth: 3
token id: 3236, depth: 1
token id: 2519, depth: 2
token id: 449, depth: 3


print tree, 0
token id: 338, depth: 0
token id: 593, depth: 1
token id: 595, depth: 2
token id: 29638, depth: 3
token id: 1683, depth: 3
token id: 1286, depth: 1
token id: 4150, depth: 2
token id: 17252, depth: 3

**Comment by xinhaoc** [comment]
@jiazhihao @zwang86 the beam search result and tree structures are all aligned and tested with beam width=3, depth=3 and request_num = 5. please check, the serialized tree result is like above.

what is modified in this branch:
1.add kernels, speculative inference, beam topk and place holder.
2.modified kernels: softmax
3.request manager: the store_beam_metadata() is for store the result for each batch, the update_beam_metadata() is for slot exchange(for cache in attention kernel), and tranverse_beam_tree() is a serialization function for the tree.

**Comment by jiazhihao** [comment]
@xinhaoc @zwang86 You folks are moving so fast. I am working on a paper deadline today, and will take a look at the changes tomorrow. I think we can merge this to the inference branch if both of you are okay with the changes. Additional modifications can be done in other PRs.

**Comment by xinhaoc** [comment]
I also have a ddl in today's midnight, check it later.

**Comment by xinhaoc** [comment]
something needs to be done is make the beam search run with verification, which can be start after merged this branch.

**Comment by jiazhihao** [comment]
I agree. We will first merge the two PRs and then start building the entire pipeline.

**Comment by zwang86** [comment]
@jiazhihao @xinhaoc Great! We can discuss that tomorrow.

**Pull request merged**
