### PR TITLE
Graph fix

### PR DESCRIPTION
**Pull request by wmdi**
**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1170)

### CODE REVIEW

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 59 of 98 files at r4, 39 of 39 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1170)* status: all files reviewed, 26 unresolved discussions (waiting on @wmdi)

___
*[`lib/utils/graph/include/utils/graph/algorithms.h` line 318 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-ZpeZ2CMnGpcUWYvR:-Ng-ZpeZ2CMnGpcUWYvS:b996bff) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/algorithms.h#L318)):*
> ```objc
>                               std::unordered_set<Node> const &);
> 
> template <typename SubgraphView>
> ```

Why is this necessary? Shouldn't there just be 1 subgraph view?
___
*[`lib/utils/graph/include/utils/graph/diedge.h` line 24 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-_1QF2uPuRCej7pta:-Ng-_1QF2uPuRCej7ptb:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/diedge.h#L24)):*
> ```objc
>   Node src;
>   Node dst;
> };
> ```





_Suggestion:_
```objc
struct DirectedEdge : virtual DiInput, virtual DiOutput { };
```
___
*[`lib/utils/graph/include/utils/graph/digraph_interfaces.h` line 24 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-_UCI5ctrf4OQ8aaB:-Ng-_UCI5ctrf4OQ8aaC:bydo4oa) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/digraph_interfaces.h#L24)):*
> ```objc
> CHECK_RC_COPY_VIRTUAL_COMPLIANT(IDiGraphView);
> 
> struct IDiGraph : virtual public IDiGraphView {
> ```

It is actually safe to inherit `IDiGraph` from `IGraph`, as their node representations are identical
___
*[`lib/utils/graph/include/utils/graph/multidigraph.h` line 72 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-cetg56qkqbu8a5LJ:-Ng-cetg56qkqbu8a5LK:b-w4borf) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/multidigraph.h#L72)):*
> ```objc
> 
> private:
>   cow_ptr_t<IMultiDiGraph> get_ptr() const;
> ```

Might be cleaner to implement this as `IMultiDiGraph &get_ref()`/`IMultiDiGraph const &get_ref() const` just so the pointer type isn't part of the signature (unless this is necessary for some of the implementations--I haven't made it to the implementation files yet)
___
*[`lib/utils/graph/include/utils/graph/multidigraph_interfaces.h` line 28 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-d66HEkZncb8PHW2a:-Ng-d66HEkZncb8PHW2b:b224gay) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/multidigraph_interfaces.h#L28)):*
> ```objc
>   virtual void remove_edge(Edge const &) = 0;
> 
>   virtual std::unordered_set<Node>
> ```

I think this method can be deleted as it's provided by `IGraphView`
___
*[`lib/utils/graph/include/utils/graph/multidigraph_interfaces.h` line 43 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-dFvF5HNgNd6rjVFV:-Ng-dFvF5HNgNd6rjVFW:bt6t80q) ([raw file](https://github.com/flexflow/FlexFlow/blob/31102a8862d6936d323b8bdec0da7d766f4b5af8/lib/utils/graph/include/utils/graph/multidigraph_interfaces.h#L43)):*
> ```objc
> CHECK_RC_COPY_VIRTUAL_COMPLIANT(IMultiDiGraphView);
> 
> struct IMultiDiGraph : public IMultiDiGraphView, public IGraph {
> ```

`IGraph` can remain here--it only needs to be removed for the labelled graphs
___
*[`lib/utils/graph/include/utils/graph/open_graph_interfaces.h` line 54 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-dcvm35fAvFeZhqEX:-Ng-dcvm35fAvFeZhqEY:bv1da9n) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/open_graph_interfaces.h#L54)):*
> ```objc
> 
> struct IUpwardOpenMultiDiGraph : virtual public IUpwardOpenMultiDiGraphView {
>   virtual void add_edge(UpwardOpenMultiDiEdge const &) = 0;
> ```

Is `add_node` necessary here too?
___
*[`lib/utils/graph/include/utils/graph/undirected.h` line 64 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-dwK_8FlM9cXRaUPq:-Ng-dwKaAb5h4W9lGkP1:b7qtnma) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/undirected.h#L64)):*
> ```objc
> 
>   virtual std::unordered_set<Node>
>       query_nodes(NodeQuery const &query) const = 0;
> ```

Remove? (this should be provided by `IUndirectedGraphView`)
___
*[`lib/utils/graph/include/utils/graph/views.h` line 277 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-eETV4VL_zB8-LeZk:-Ng-eETV4VL_zB8-LeZl:b-ozrrng) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/views.h#L277)):*
> ```objc
> private:
>   OpenMultiDiGraphView const &g;
>   std::unordered_set<Node> const &nodes;
> ```

Using refs here prevents `cow_ptr_t` from managing object lifetimes for you 



_Suggestion:_
```objc
struct ClosedMultiDiSubgraphView : public IOpenMultiDiGraphView {
  ClosedMultiDiSubgraphView() = delete;
  ClosedMultiDiSubgraphView(OpenMultiDiGraphView const &, std::unordered_set<Node> const &);

  std::unordered_set<OpenMultiDiEdge>
      query_edges(OpenMultiDiEdgeQuery const &) const override;
  std::unordered_set<Node> query_nodes(NodeQuery const &) const override;

private:
  OpenMultiDiGraphView g;
  std::unordered_set<Node> const &nodes;
```
___
*[`lib/utils/graph/include/utils/graph/labelled/label_interfaces.h` line 7 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-edQ0BMPqdwF6k0vE:-Ng-edQ0BMPqdwF6k0vF:b83i) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/labelled/label_interfaces.h#L7)):*
> ```objc
> 
> template <typename Elem, typename Label>
> struct ILabel {
> ```

I would probably rename to `ILabelling`, as this is a labelling of `Elem`s and not itself a label
___
*[`lib/utils/graph/include/utils/graph/labelled/label_interfaces.h` line 15 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-eSaY9hiMiFx1dr79:-Ng-eSaY9hiMiFx1dr7A:b-ovyhnr) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/labelled/label_interfaces.h#L15)):*
> ```objc
> 
> template <typename Label>
> struct IOutputOpenLabel {
> ```

Why is this not just a specialization of `ILabel`?
___
*[`lib/utils/graph/include/utils/graph/labelled/node_labelled.h` line 10 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-gV_eDYpKo9tJDYrf:-Ng-gV_eDYpKo9tJDYrg:b5fmfu1) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/labelled/node_labelled.h#L10)):*
> ```objc
> 
> template <typename NodeLabel>
> struct INodeLabelledMultiDiGraphView : public IMultiDiGraphView {
> ```

Would doing something like this be a good idea?



_Suggestion:_
```objc
template <typename NodeLabel>
struct INodeLabelledMultiDiGraphView : public IMultiDiGraphView, public INodeLabelling {
```
___
*[`lib/utils/graph/include/utils/graph/labelled/node_labelled.h` line 64 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-ezU5AxcUycm0DXGp:-Ng-ezU5AxcUycm0DXGq:bfu4ved) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/labelled/node_labelled.h#L64)):*
> ```objc
> private:
>   using Interface = IMultiDiGraph<NodeLabel>;
>   using NodeLabelIf = ILabel<Node, NodeLabel>;
> ```

`If` is a rather ambiguous abbreviation



_Suggestion:_
```objc
  using NodeLabelInterface = ILabel<Node, NodeLabel>;
```
___
*[`lib/utils/graph/include/utils/graph/labelled/node_labelled.h` line 79 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-fFSY9oIeiVlFKKZg:-Ng-fFSY9oIeiVlFKKZh:b-o50hlz) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/labelled/node_labelled.h#L79)):*
> ```objc
>   }
> 
>   NodeLabel const &at(Node const &n) const override {
> ```

Should not be override--non I-types should not have any virtual methods
___
*[`lib/utils/graph/include/utils/graph/labelled/node_labelled.h` line 87 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-fNp50O9wLPEbbhVU:-Ng-fNp50O9wLPEbbhVV:buyub7v) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/labelled/node_labelled.h#L87)):*
> ```objc
>   }
> 
>   std::unordered_set<Node> query_nodes(NodeQuery const &q) const {
> ```

Why does this have its own implementation instead of using the one from `NodeLabelledMultiDiGraphView`?
___
*[`lib/utils/graph/include/utils/graph/labelled/node_labelled.h` line 96 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-g40VDz577BGY6n6k:-Ng-g40VDz577BGY6n6l:bhg932m) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/labelled/node_labelled.h#L96)):*
> ```objc
> 
>   Node add_node(NodeLabel const &l) {
>     Node n = MultiDiGraph::add_node();
> ```

Shouldn't this just delegate to the interface?
___
*[`lib/utils/graph/include/utils/graph/labelled/node_labelled.h` line 102 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-gF2PEtmkFu8qd8n1:-Ng-gF2PEtmkFu8qd8n2:b-hbrjpy) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/labelled/node_labelled.h#L102)):*
> ```objc
> 
>   NodePort add_node_port() {
>     get_ptr()->add_node_port();
> ```

return?
___
*[`lib/utils/graph/include/utils/graph/labelled/node_labelled.h` line 109 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-gKOQ26v4LWkG3Qik:-Ng-gKOQ26v4LWkG3Qil:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/labelled/node_labelled.h#L109)):*
> ```objc
>   }
> 
>   template <typename GraphImpl, typename NLImpl>
> ```





_Suggestion:_
```objc
 template <typename GraphImpl, typename NodeLabellingImpl>
```
___
*[`lib/utils/graph/include/utils/graph/labelled/open_views.h` line 16 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng584e6-Gg-wbitXEZ9:-Ng57iOkEPpSktiR9Pr3:b-wicn4h) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/labelled/open_views.h#L16)):*
> ```objc
> namespace FlexFlow {
> 
> template <typename SubgraphView, typename NodeLabel, typename EdgeLabel>
> ```

Why the additional template parameter?
___
*[`lib/utils/graph/include/utils/graph/labelled/open_views.h` line 32 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng58F_GAfl9QDzsNV_h:-Ng58F_HAHcrX6L9txXj:b-ookq7s) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/labelled/open_views.h#L32)):*
> ```objc
> 
>   std::unordered_set<Node> query_nodes(NodeQuery const &q) const override {
>     return SubgraphView(g, nodes).query_nodes(q);
> ```

Why this as opposed to `get_subgraph`?
___
*[`lib/utils/graph/include/utils/graph/labelled/standard_labelled.h` line 9 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng6PLTc-L43K-rqWAoX:-Ng6PLTc-L43K-rqWAoY:b8vouer) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/labelled/standard_labelled.h#L9)):*
> ```objc
> 
> template <typename NodeLabel, typename EdgeLabel>
> struct ILabelledMultiDiGraphView
> ```

Does it make sense to have this class anymore if we're breaking up the hierarchy by separating graphs and labellings? If not, perhaps it would be possible to instead make this
```cpp
template <typename NodeLabel, typename EdgeLabel>
struct ILabelledMultiDiGraphView
  : public IMultiDiGraphView, 
    public ILabellingView<Node, NodeLabel, MultiDiEdge, EdgeLabel> {
...
};
```
and then have 
```cpp
template <typename NodeLabel, typename EdgeLabel>
struct LabelledMultiDiGraphView
  : virtual public MultiDiGraphView,
    virtual public Labelling<Node, NodeLabel, MultiDiEdge, EdgeLabel> {
...
};
```
or even possibly broken down further into 
```cpp
template <typename NodeLabel, typename EdgeLabel>
struct LabelledMultiDiGraphView
  : virtual public MultiDiGraphView,
    virtual public Labelling<Node, NodeLabel>,
    virtual public Labelling<MultiDiEdge, EdgeLabel> {
...
};
```
(using virtual inheritance if necessary--I didn't really think about where it would be necessary in the above code)
___
*[`lib/utils/graph/include/utils/graph/labelled/standard_labelled.h` line 60 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng6Q3ho7y3YX9GoKMkT:-Ng6Q3ho7y3YX9GoKMkU:biczvx1) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/labelled/standard_labelled.h#L60)):*
> ```objc
>   LabelledMultiDiGraphView(cow_ptr_t<Interface const> ptr) : NodeLabelledMultiDiGraphView<NodeLabel>(ptr) {}
>   cow_ptr_t<Interface const> get_ptr() const {
>     return static_assert<cow_ptr_t<Interface const>>(ptr);
> ```

static_assert? Did you mean static_cast?
___
*[`lib/utils/graph/include/utils/graph/labelled/unordered_label.h` line 10 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng6RUctDi9wopNQ1VHh:-Ng6RUctDi9wopNQ1VHi:bdrlv7f) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/labelled/unordered_label.h#L10)):*
> ```objc
> 
> template <typename Elem, typename Label>
> struct UnorderedLabel : virtual public ILabel<Elem, Label> {
> ```

See my comments on `ILabelledMultiDiGraph`--I think it may be possible to merge all of the labelling into a single template class/interface
___
*[`lib/utils/graph/src/utils/graph/node.cc` line 44 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng6S4Ld83bV9HAKiKQ0:-Ng6S4Ld83bV9HAKiKQ1:ba7bqyy) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/src/utils/graph/node.cc#L44)):*
> ```cpp
> 
> Node Graph::add_node() {
>   get_ptr()->add_node();
> ```

Return?
___
*[`lib/utils/graph/src/utils/graph/node.cc` line 48 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng6S33k54TrVptcO9yc:-Ng6S33l-8Gy4UhnqMRE:ba7bqyy) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/src/utils/graph/node.cc#L48)):*
> ```cpp
> 
> Node Graph::add_node_unsafe() {
>   get_ptr()->add_node_unsafe();
> ```

Return?
___
*[`lib/utils/graph/src/utils/graph/node.cc` line 52 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng6S5V6DtAprA0V7fyn:-Ng6S5V74L6sKXcQKvXV:ba7bqyy) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/src/utils/graph/node.cc#L52)):*
> ```cpp
> 
> Node Graph::remove_node_unsafe() {
>   get_ptr()->remove_node_unsafe();
> ```

Return?

**Review by wmdi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1170)* status: all files reviewed, 26 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/graph/include/utils/graph/algorithms.h` line 318 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-ZpeZ2CMnGpcUWYvR:-NgVMc8vC3oEjgFO8CfX:b-w34peh) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/algorithms.h#L318)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is this necessary? Shouldn't there just be 1 subgraph view?
</blockquote></details>

There are 4 subgraph views: closed, upward open, downward open, and open.
___
*[`lib/utils/graph/include/utils/graph/diedge.h` line 24 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-_1QF2uPuRCej7pta:-NgVMqTx507KkC_74V0R:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/diedge.h#L24)):*
> ```objc
>   Node src;
>   Node dst;
> };
> ```

Done.
___
*[`lib/utils/graph/include/utils/graph/labelled/label_interfaces.h` line 15 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-eSaY9hiMiFx1dr79:-NgVNNvH6ccXStzf3Odu:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/labelled/label_interfaces.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is this not just a specialization of `ILabel`?
</blockquote></details>

Done.
___
*[`lib/utils/graph/include/utils/graph/labelled/node_labelled.h` line 102 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng-gF2PEtmkFu8qd8n1:-NgVNqtb8Od0DE9cAPO6:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/labelled/node_labelled.h#L102)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

return?
</blockquote></details>

Done.
___
*[`lib/utils/graph/include/utils/graph/labelled/open_views.h` line 32 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng58F_GAfl9QDzsNV_h:-NgVOA5W7GBVIgykkxGB:b-2r5uvr) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/labelled/open_views.h#L32)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why this as opposed to `get_subgraph`?
</blockquote></details>

It should be equivalent to `get_subgraph<SubgraphView>`
___
*[`lib/utils/graph/include/utils/graph/labelled/standard_labelled.h` line 60 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng6Q3ho7y3YX9GoKMkT:-NgVOjQg6noMnGSnWd3z:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/include/utils/graph/labelled/standard_labelled.h#L60)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

static_assert? Did you mean static_cast?
</blockquote></details>

Done.
___
*[`lib/utils/graph/src/utils/graph/node.cc` line 44 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng6S4Ld83bV9HAKiKQ0:-NgVOzyMCs9UQCtwoqQf:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/src/utils/graph/node.cc#L44)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Return?
</blockquote></details>

Done.
___
*[`lib/utils/graph/src/utils/graph/node.cc` line 48 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng6S33k54TrVptcO9yc:-NgVP-BwD_g35-EXN8fN:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/src/utils/graph/node.cc#L48)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Return?
</blockquote></details>

Done.
___
*[`lib/utils/graph/src/utils/graph/node.cc` line 52 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-Ng6S5V6DtAprA0V7fyn:-NgVP-UT4uW_S-UtNEhd:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/34bc6c7dbf97faefaca387904fd2065a25ea6783/lib/utils/graph/src/utils/graph/node.cc#L52)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Return?
</blockquote></details>

Done.

**Comment by lockshaw** [comment]
@wmdi This can be closed as it was moved to #1189, right?

**Review by wmdi — COMMENTED** [review]
Yes. Only the reviews are required for graph improvement.

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-:-Nh8qmvy3FTmacuxBVE4:b-1a9am6)* status: all files reviewed, 26 unresolved discussions (waiting on @lockshaw)

**Comment by lockshaw** [comment]
So should I do another round of review on this? I don't remember what the status of this PR was...

**Review by wmdi — COMMENTED** [review]
I don't think so. This pr is to help the graph improvement pr.

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-:-NnMl1Ew0N8p1U3AyAZT:b-qhyimj)* status: all files reviewed, 26 unresolved discussions (waiting on @lockshaw)

**Comment by lockshaw** [comment]
Should it be closed then?

**Review by wmdi — COMMENTED** [review]
I think so

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1170#-:-NnXcJOR31RvKUuqeEOp:bafpgxy)* status: all files reviewed, 26 unresolved discussions (waiting on @lockshaw)

**Pull request closed without merging**
