### PR TITLE
Using AllReduce instead of Reduce + Replicate when tensor model parallelism is enabled

### PR DESCRIPTION
**Pull request by jiazhihao**
**Description of changes:**

This PR implements AllReduce as a new parallel operator in FlexFlow. When tensor model parallelism degree is larger than 1, the system will automatically use AllReduce instead of Reduce + Replicate for communications between GPUs.

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

### CODE REVIEW

**Review by goliaro — APPROVED** [review]
I think this PR is now ready to be merged. Let's see if CI passes.

**Comment by jiazhihao** [comment]
```
< 6. Wash your vegetables.
< 7. Wash your fruits.
< 8. Wash your meat.
< 9. Wash your eggs.
< 10. Wash your fish.
< 11. Wash your bread.
< 12. Wash your cereal.
< 13. Wash your milk.
< 14
\ No newline at end of file
---
> 6. Wear sunscreen.
> 7. Wear a helmet when riding a bike.
> 8. Wear a seat belt when riding in a car.
> 9. Wear a helmet when riding a bike.
> 10. Wear a seat belt when riding in a car.
> 11.
\ No newline at end of file
```

The above error is likely caused by floating point errors (since we now use ncclAllReduce instead of reduction + replicate to communicate between GPUs). @goliaro Do you think we should reduce the number of tokens to examine for half precision?

**Comment by goliaro** [comment]
> ```
> < 6. Wash your vegetables.
> < 7. Wash your fruits.
> < 8. Wash your meat.
> < 9. Wash your eggs.
> < 10. Wash your fish.
> < 11. Wash your bread.
> < 12. Wash your cereal.
> < 13. Wash your milk.
> < 14
> \ No newline at end of file
> ---
> > 6. Wear sunscreen.
> > 7. Wear a helmet when riding a bike.
> > 8. Wear a seat belt when riding in a car.
> > 9. Wear a helmet when riding a bike.
> > 10. Wear a seat belt when riding in a car.
> > 11.
> \ No newline at end of file
> ```
> 
> The above error is likely caused by floating point errors (since we now use ncclAllReduce instead of reduction + replicate to communicate between GPUs). @goliaro Do you think we should reduce the number of tokens to examine for half precision?

yeah, I think the half precision mismatch after a certain number of tokens shouldn't be a problem. We can just change the test to be a bit more permissive about this

**Comment by jiazhihao** [comment]
> yeah, I think the half precision mismatch after a certain number of tokens shouldn't be a problem. We can just change the test to be a bit more permissive about this

I like this idea.

**Comment by goliaro** [comment]
@jiazhihao right now however, there is an additional bug that I'm investigating. When running speculative inference, the latency is higher than that of incremental decoding using the big model only... Not sure if there is a simple issue with the machine views assigned to the small model, or something more tricky

**Comment by xinhaoc** [comment]
> @jiazhihao right now however, there is an additional bug that I'm investigating. When running speculative inference, the latency is higher than that of incremental decoding using the big model only... Not sure if there is a simple issue with the machine views assigned to the small model, or something more tricky
Hi @goliaro .I tried this command `/inference/incr_decoding/incr_decoding -ll:gpu 4 -ll:util 4 -ll:fsize 14000 -ll:zsize 30000 -llm-model llama -llm-weight ../inference/weights/llama_7B_half_weights/ -llm-config ../inference/models/configs/llama_7B.json -ssm-model llama -ssm-weight ../inference/weights/llama_190m_half_weights/ -ssm-config ../inference/models/configs/llama_160M.json -tokenizer ../inference/tokenizers/tokenizer.model -prompt ../inference/prompt/test.json -tensor-parallelism-degree 4` to run without fuse, the incr_decoding latency is 8269064.0 and spec_infer latency is 7337629.0

**Comment by goliaro** [comment]
> > @jiazhihao right now however, there is an additional bug that I'm investigating. When running speculative inference, the latency is higher than that of incremental decoding using the big model only... Not sure if there is a simple issue with the machine views assigned to the small model, or something more tricky
> > Hi @goliaro .I tried this command `/inference/incr_decoding/incr_decoding -ll:gpu 4 -ll:util 4 -ll:fsize 14000 -ll:zsize 30000 -llm-model llama -llm-weight ../inference/weights/llama_7B_half_weights/ -llm-config ../inference/models/configs/llama_7B.json -ssm-model llama -ssm-weight ../inference/weights/llama_190m_half_weights/ -ssm-config ../inference/models/configs/llama_160M.json -tokenizer ../inference/tokenizers/tokenizer.model -prompt ../inference/prompt/test.json -tensor-parallelism-degree 4` to run without fuse, the incr_decoding latency is 8269064.0 and spec_infer latency is 7337629.0

The slowdown I'm seeing happens when using pipeline parallelism (e.g. pipeline parallelism degree of 4 or 2). Not sure if we care about that scenario or not, since we will likely have tensor parallelism turned on?

**Comment by jiazhihao** [comment]
I think we can fix the performance issue later; just make sure that the SSMs are running on a single GPU. Let's merge this PR after passing CI

**Pull request merged**
