### PR TITLE
Allow passing parameters to `config.linux`

### PR DESCRIPTION
**Pull request by goliaro**
**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/895)

### CODE REVIEW

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/895)* status: all files reviewed, 1 unresolved discussion (waiting on @goliaro)

___
*[`config/config.linux` line 85 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/895#-NaQ4ubpBq9RaQDD-Y2L:-NaQ4ubpBq9RaQDD-Y2M:bmro9x5) ([raw file](https://github.com/flexflow/FlexFlow/blob/48df80e4b9467ce344152bda00e037c064e6f74a/config/config.linux#L85)):*
> ```
> }
> 
> if [ -n "$1" ] && [ "$1" != "get-docker-configs" ]; then
> ```

Not quite. The case I'm considering is running the command
```
$ ../config/config.linux -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
```
In both the new code and the current code, this will lead to passing the if condition and then attempting to echo (essentially) "$-DCMAKE_CXX_COMPILER_LAUNCHER=ccache", which is clearly not a valid variable and leads to an error. 

I think a good way around this is to essentially have an interface where you can pass a `--print-variable` flag to enable printing a variable, e.g., 
```
$ ../config/config.linux --print-var CUDA_PATH
/usr/lib/cuda
```
but if not passed, 
```
$ ../config/config.linux -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
<output of (run_cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache)>
```

Does that make sense?

**Comment by goliaro** [comment]
@lockshaw ok, it should work now!

**Review by goliaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/895)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lockshaw)

___
*[`config/config.linux` line 85 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/895#-NaQ4ubpBq9RaQDD-Y2L:-NaTgxgtDMtlBGG5c3Vf:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/48df80e4b9467ce344152bda00e037c064e6f74a/config/config.linux#L85)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Not quite. The case I'm considering is running the command
```
$ ../config/config.linux -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
```
In both the new code and the current code, this will lead to passing the if condition and then attempting to echo (essentially) "$-DCMAKE_CXX_COMPILER_LAUNCHER=ccache", which is clearly not a valid variable and leads to an error. 

I think a good way around this is to essentially have an interface where you can pass a `--print-variable` flag to enable printing a variable, e.g., 
```
$ ../config/config.linux --print-var CUDA_PATH
/usr/lib/cuda
```
but if not passed, 
```
$ ../config/config.linux -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
<output of (run_cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache)>
```

Does that make sense?
</blockquote></details>

Done.

**Review by lockshaw — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/895)* status: all files reviewed, 1 unresolved discussion (waiting on @goliaro)

___
*[`config/config.linux` line 91 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/895#-NaThJf719T5rKIzOriw:-NaThJf719T5rKIzOrix:b2x0jck) ([raw file](https://github.com/flexflow/FlexFlow/blob/25b399e7978ac4776f9ade12f630a89739dfce9f/config/config.linux#L91)):*
> ```
>     # to get the cmake config
>     echo "${!1}"
> elif [[ -z "$1" || "$1" != "get-docker-configs" ]]; then
> ```

Why is `get-docker-configs` not allowed here? (just out of curiosity--I don't see any code in this file that does anything with it)

**Review by goliaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/895)* status: all files reviewed, 1 unresolved discussion

___
*[`config/config.linux` line 91 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/895#-NaThJf719T5rKIzOriw:-NaU0ZCx29VePFhgETsd:beqoyoh) ([raw file](https://github.com/flexflow/FlexFlow/blob/25b399e7978ac4776f9ade12f630a89739dfce9f/config/config.linux#L91)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is `get-docker-configs` not allowed here? (just out of curiosity--I don't see any code in this file that does anything with it)
</blockquote></details>

`get-docker-configs` is used [here](https://github.com/flexflow/FlexFlow/blob/master/docker/build.sh#L113)

**Review by lockshaw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/895)* status: all files reviewed, 1 unresolved discussion

___
*[`config/config.linux` line 91 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/895#-NaThJf719T5rKIzOriw:-NaVJHfR8boInCMVzCWo:b-35m2zl) ([raw file](https://github.com/flexflow/FlexFlow/blob/25b399e7978ac4776f9ade12f630a89739dfce9f/config/config.linux#L91)):*
<details><summary><i>Previously, goliaro (Gabriele Oliaro) wrote…</i></summary><blockquote>

`get-docker-configs` is used [here](https://github.com/flexflow/FlexFlow/blob/master/docker/build.sh#L113)
</blockquote></details>

Yes, but where is the argument processing in this file that actually does something with it?

**Review by goliaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/895)* status: all files reviewed, 1 unresolved discussion

___
*[`config/config.linux` line 91 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/895#-NaThJf719T5rKIzOriw:-NbyUmDa8ZzdsEyS4XWV:bpknl1h) ([raw file](https://github.com/flexflow/FlexFlow/blob/25b399e7978ac4776f9ade12f630a89739dfce9f/config/config.linux#L91)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Yes, but where is the argument processing in this file that actually does something with it?
</blockquote></details>

There is no processing in this file, because we actually don't need to do anything with it, other than just avoid running cmake. Docker just sources this script to get the configs, and we want to make sure that the cmake configuration is not triggered in that phase

**Pull request merged**
