### PR TITLE
Support multi-GPU inference

### PR DESCRIPTION
**Pull request by jiazhihao**
**Description of changes:**

The LLAMA example now support multi-GPU inference using the following command
```
./llama -ll:gpu 4 -ll:fsize 14000 -ll:zsize 30000 --only-data-parallel
```

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

### CODE REVIEW

**Comment by jiazhihao** [comment]
I encountered a CUDA illegal memory access issue, which is caused by this kernel(https://github.com/flexflow/FlexFlow/blob/inference/src/ops/kernels/rms_norm_kernels.cu#L144-L146) since the issue went away after commenting out the kernel. 

@xinhaoc can you take a look at this issue when you get a chance. To reproduce: allocate a g4dn.12xlarge instance (with 4 GPUs), compile the LLAMA example, and run 
```
./examples/cpp/inference/LLAMA/LLAMA -ll:gpu 4 -ll:fsize 14000 -ll:zsize 30000 --only-data-parallel --profiling
```

**Comment by xinhaoc** [comment]
alright, let me take a loot at it.

**Comment by xinhaoc** [comment]
@jiazhihao I just found the bug is related the machine view in init_inference in rms_norm #702

**Comment by jiazhihao** [comment]
@xinhaoc Great. The LLAMA example now works on 4 GPUs. I have merged this PR to the inference branch.

**Pull request merged**
