### PR TITLE
Gather bug fix

### LINKED ISSUE #686: Alignment error in gather
The outputs of gather appears to differ from that of PyTorch/Keras in the following example. 

```python
r"""
Gather bug repro

To get flexflow outputs:
flexflow_python gather_bug_align.py  -ll:py 1 -ll:gpu 1 -ll:fsize 15000 \
     -ll:zsize 4000 --only-data-parallel -b 16

To check with keras/torch:
python gather_bug_align.py

"""


import numpy as np


def get_modified_idx(idx, hidden_shape):
    return idx.reshape(-1, 1).repeat(hidden_shape, 1).astype(np.int32)


def top_level_task():
    from flexflow import keras
    import flexflow.keras.optimizers

    intermediate_tensors = []

    bs = 16  # Set to the same number as -b argument to the script
    idx = np.random.randint(0, 14, (10, 16))
    mod_idx = get_modified_idx(idx, 8)

    inp_x = keras.layers.Input(shape=(15, 4))
    inp_idx = keras.layers.Input(mod_idx.shape, dtype="int32")  # b, 160, 8

    x = inp_x  # b, 15, 4

    x = keras.layers.Reshape((x.shape[1]*x.shape[2],))(x)  # b, 15*4
    x = keras.layers.Dense(15*8, use_bias=True)(x); intermediate_tensors.append(x)  # b, 15*8
    x = keras.layers.Reshape((inp_x.shape[1], 8))(x)  # b, 15, 8

    x = keras.backend.internal.gather(x, inp_idx, axis=1); intermediate_tensors.append(x) # b, 160, 8
    out = keras.layers.Reshape((10, 16, 8))(x) # b, 10, 16, 8

    model = flexflow.keras.models.Model([inp_x, inp_idx], out)

    opt = flexflow.keras.optimizers.SGD(learning_rate=0.01)
    model.compile(optimizer=opt, loss='mean_squared_error',
                  metrics=['mean_squared_error'])

    bs = model.ffconfig.batch_size
    x = [np.random.randn(16, 15, 4).astype(np.float32),
         mod_idx[None, ...].repeat(bs, 0).astype(np.int32)]
    y = np.random.randn(bs, 10, 16, 8).astype(np.float32)
    parameters = [l.get_weights(model.ffmodel)
                  for l in model.layers if hasattr(l, 'get_weights')]

    model.fit(x=x, y=y, epochs=1)

    tensor_vals = [t.ffhandle.get_tensor(model.ffmodel)
                   for t in intermediate_tensors]

    return bs, parameters, x, y, tensor_vals


def keras_task(bs, parameters, inps, y, tensor_vals):
    import tensorflow as tf
    import tensorflow.keras as keras
    from keras.layers import Dense, Concatenate, Input, Reshape, Multiply, Add

    bs = 16
    intermediate_tensors = []

    input_x = Input(shape=(15, 4), dtype="float32")
    inp_idx = inps[1][0, :, 0].reshape(10, 16)

    x = input_x

    x = Reshape((x.shape[1]*x.shape[2],))(x)
    x = Dense(15*8)(x); intermediate_tensors.append(x)
    x = Reshape((input_x.shape[1], 8))(x)
    x = tf.gather(x, inp_idx, axis=1); intermediate_tensors.append(x)

    model = keras.models.Model(input_x, intermediate_tensors)

    i = 0
    for l in model.layers:
        if not isinstance(l, Dense):
            continue
        try:
            l.set_weights(parameters[i])
        except ValueError:
            l.set_weights((parameters[i][0].T, parameters[i][1]))
        i += 1

    opt = keras.optimizers.SGD(learning_rate=0.01)
    model.compile(optimizer=opt, loss='mean_squared_error',
                  metrics=['mean_squared_error'])

    out = model(inps[0])
    for i in range(len(out)):
        print('Matching', i)
        if i == 1:
            e = out[i].numpy()  # Keras
            k = tensor_vals[i].reshape(*e.shape)  # Flexflow
            gather_in = out[0].numpy().reshape((16, 15, 8))
            import torch
            torch_idx = get_modified_idx(inp_idx, 8)[None, :].repeat(bs, 0)
            m = torch.gather(torch.tensor(gather_in), 1, torch.tensor(torch_idx).to(torch.long)).numpy()
            m = m.reshape(*e.shape)  # Torch

            '''
            An example of the difference        
            e[1][0][0] matches m[0][0][0] (i.e keras and torch implementations match)
            but these aren't equal to k[1][0][0] (flexflow)

            but e[0][0][0] == m[0][0][0] == k[0][0][0]
            '''
        np.testing.assert_allclose(
            tensor_vals[i].ravel(), out[i].numpy().ravel(),
            atol=1e-5, rtol=1.3e-6)


if __name__ == '__main__':
    import pickle
    import sys
    if len(sys.argv) > 1:
        t = top_level_task()
        pickle.dump(t, open('dump.pkl', 'wb'))
    else:
        t = pickle.load(open('dump.pkl', 'rb'))
        keras_task(*t)
```

### PR DESCRIPTION
**Pull request by jiazhihao**
**Description of changes:**

Fix a bug in gather forward and backward

**Related Issues:**

Linked Issues:
- Issue #686

Issues closed by this PR:
- Closes #686

**Before merging:**

- [x] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

### CODE REVIEW

**Comment by soumyac1999** [comment]
Thanks! This fixes the bug in gather. However, it probably introduces some other bug since the CI fails and also when running my full model, I get a similar error:
```
num_nodes = 1 num_gpus_per_node = 1
optimal_views.size = 49
terminate called after throwing an instance of 'std::runtime_error'
  what():  Operator type unsupported: -1008599040
Aborted
```

**Comment by soumyac1999** [comment]
Also, would we like to move the changes for reduce_mean to a different PR unless it is being used in gather?

**Comment by jiazhihao** [comment]
I will work on passing the CI tests. First, I would like to make sure this did fix the misalignment issue.

**Comment by soumyac1999** [comment]
Yes, it did fix the misalignment issues. Thanks!

**Comment by jiazhihao** [comment]
The error code is 143, which means
```
Exit Code 143 means that the container received a SIGTERM signal from the operating system, which asks the container to gracefully terminate, and the container succeeded in gracefully terminating (otherwise you will see Exit Code 137).
```

This seems irrelevant with this PR. @gabrieleoliaro any thoughts?

**Comment by jiazhihao** [comment]
So we have passed all tests. @soumyac1999 @lockshaw can one of you approve this PR?

**Review by gabrieleoliaro — APPROVED** [review]

**Pull request merged**
