### PR TITLE
new batch

### PR DESCRIPTION
**Pull request by xinhaoc**
**Description of changes:**

- [x] update batch config with the data structure in [doc](https://docs.google.com/document/d/1A94h6WObdqJzzXhGPq2enP2Ae_onrUNqGlq0QMVwaTg/edit?usp=sharing)
- [x] check it has same result with previous batch config using llama
- [x] check other models using new batch config
- [x] try to minimize the existing variables
- [ ] design BeamSearchBatchConfig and TreeVerifyBatchConfig
- [ ] request manager

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

### CODE REVIEW

**Review by gabrieleoliaro — APPROVED** [review]
I think we can merge this now, and finish the remaining TODOs in a follow-up PR. I'm wrapping up the fixes to the INFERENCE_TEST tests, and will merge those later tonight (hopefully) as well

**Comment by xinhaoc** [comment]
just leave a comment for future, the github CI issue of `The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.` may caused by some unknown internal error inside CI.

**Comment by jiazhihao** [comment]
I have merged this PR. I experienced similar issues with merging a PR to the master branch.

**Comment by xinhaoc** [comment]
yes it occasionally happens

**Pull request merged**
