### PR TITLE
enable PS for the NCCL branch

### PR DESCRIPTION
**Pull request by eddy16112**

### CODE REVIEW

**Comment by eddy16112** [comment]
How about change the `CommType type` in the `Parameter` class to static variable? Because all Parameter instances will have the same CommType.

**Comment by jiazhihao** [comment]
In the future, we want to have a mixture of multiple parameter synchronization methods: parameters replicated across all GPUs can use allreduce (e.g., NCCL) and parameters stored on a few devices can use the parameter server approach. Right now the commtype is hard coded when initializing an operator, but it will become an input argument before merging nccl back to master.

**Comment by jiazhihao** [comment]
The changes look good to me.

**Comment by eddy16112** [comment]
> In the future, we want to have a mixture of multiple parameter synchronization methods: parameters replicated across all GPUs can use allreduce (e.g., NCCL) and parameters stored on a few devices can use the parameter server approach. Right now the commtype is hard coded when initializing an operator, but it will become an input argument before merging nccl back to master.

It makes sense to me. I am going to modify the PR to allow enabling both NCCL and PS.

**Pull request merged**
