### PR TITLE
Initial tests for keras backend functions

### PR DESCRIPTION
**Pull request by soumyac1999**
**Description of changes:**
Initial tests for keras backend functions

**Related Issues:**

Linked Issues:
- Issue #418

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

### CODE REVIEW

**Comment by soumyac1999** [comment]
I am trying to use pytest for testing but am not able to get FlexFlow to work with native python. I followed the instructions in INSTALL.md, namely `export PYTHONPATH="${FF_HOME}/python; export FF_USE_NATIVE_PYTHON=1`.

Running the test with native python throws the following error:
```
OSError: cannot load library 'libflexflow_native_python.so': libflexflow_native_python.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libflexflow_native_python.so'
```
Command to run the test:
```
pytest
# or
python test_backend_functions.py
```

It works with the compiled `flexflow_python` as expected. Command:
```
../../../python/flexflow_python test_backend_functions.py -ll:py 1 -ll:gpu 1 -ll:fsize 8192 -ll:zsize 12192
```

**Comment by eddy16112** [comment]
> I am trying to use pytest for testing but am not able to get FlexFlow to work with native python. I followed the instructions in INSTALL.md, namely `export PYTHONPATH="${FF_HOME}/python; export FF_USE_NATIVE_PYTHON=1`.
> 
> Running the test with native python throws the following error:
> 
> ```
> OSError: cannot load library 'libflexflow_native_python.so': libflexflow_native_python.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libflexflow_native_python.so'
> ```
> 
> Command to run the test:
> 
> ```
> pytest
> # or
> python test_backend_functions.py
> ```
> 
> It works with the compiled `flexflow_python` as expected. Command:
> 
> ```
> ../../../python/flexflow_python test_backend_functions.py -ll:py 1 -ll:gpu 1 -ll:fsize 8192 -ll:zsize 12192
> ```

That is because `libflexflow_native_python.so` is not in the correct path. You can print the value of `flexflow_lib` in `flexflow_cffi.py`. `flexflow_lib` should be something like `path_to/libflexflow_native_python.so`, and then you can move the so file to the correct dir. 

We will have native python support in Legion soon, then I can create a PR to let FlexFlow direct use the native python from Legion.

**Comment by soumyac1999** [comment]
Thanks for your help, that helped fix the issue! 

For me, `libflexflow_native_python.so` gets created in `<FlexFlow dir>/build/python` while `flexflow_lib` was `<FlexFlow dir>/python/libflexflow_native_python.so`. I do not understand the build process well enough to know if I did something wrong or the file was not copied over to the expected path.

**Comment by soumyac1999** [comment]
@lockshaw, I think I will need help in figuring out how to get the tests to work with unittest/pytest. Or we could just use a bash script to run the tests (like in https://github.com/flexflow/FlexFlow/blob/master/tests/multi_gpu_tests.sh) for now. What do you think?

**Comment by gabrieleoliaro** [comment]
> I am trying to use pytest for testing but am not able to get FlexFlow to work with native python. I followed the instructions in INSTALL.md, namely `export PYTHONPATH="${FF_HOME}/python; export FF_USE_NATIVE_PYTHON=1`.
> 
> Running the test with native python throws the following error:
> 
> ```
> OSError: cannot load library 'libflexflow_native_python.so': libflexflow_native_python.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libflexflow_native_python.so'
> ```
> 
> Command to run the test:
> 
> ```
> pytest
> # or
> python test_backend_functions.py  -ll:gpu 1 -ll:fsize 8192 -ll:zsize 12192
> ```
> 
> It works with the compiled `flexflow_python` as expected. Command:
> 
> ```
> ../../../python/flexflow_python test_backend_functions.py -ll:py 1 -ll:gpu 1 -ll:fsize 8192 -ll:zsize 12192
> ```

@soumyac1999 sorry for the confusion, I forgot to update the native python section of the docs. If you are trying to use native python, you have the following two options:

1. if you install Flexflow (either with pip install or with make install), you will only need to set: `export FF_USE_NATIVE_PYTHON=1`, the PYTHONPATH is not needed
2. if you build FlexFlow without installing, on the other hand, in addition to `export FF_USE_NATIVE_PYTHON=1`, you will also need to set the following PYTHONPATH: `export PYTHONPATH="${FF_HOME}/python:${FF_HOME}/build/python"`

For more details on the various ways/settings related to the python interface, you can check out the description in PR #539 , or [this script](https://github.com/flexflow/FlexFlow/blob/master/tests/python_interface_test.sh), which is currently by a few workflows in CI

**Comment by soumyac1999** [comment]
Closing since outdated

**Pull request closed without merging**
