### PR TITLE
Repo refactor ci 

### PR DESCRIPTION
**Pull request by lambda7xx**
**Description of changes:**
- update the CI and currently we ignore the hip

**Related Issues:**

Linked Issues:
- Issue #1064

Issues closed by this PR:
- Closes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1083)

### CODE REVIEW

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1083)* status: all files reviewed, 3 unresolved discussions (waiting on @aquan9 and @lambda7xx)

___
*[`run.sh` line 0 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NdplszOBc3w92ipxoDG:-NdplszOBc3w92ipxoDH:bbhdepl) ([raw file](https://github.com/flexflow/FlexFlow/blob/9f935a195353178acec1a67d1ac73b0c6036f0e6/run.sh#L0)):*
Don't know how this file made it in but it should be removed
___
*[`.github/workflows/gpt-ci.yml-old` line 0 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-Ndpm6pp4NQ4m2_2Ogep:-Ndpm6pp4NQ4m2_2Ogeq:b-rvaht2) ([raw file](https://github.com/flexflow/FlexFlow/blob/9f935a195353178acec1a67d1ac73b0c6036f0e6/.github/workflows/gpt-ci.yml-old#L0)):*
Just remove--we have git history and `master`
___
*[`.github/workflows/shell-check.yml` line 12 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NdpmGJAEovnjPTTjKA3:-NdpmGJAEovnjPTTjKA4:b-39gdsx) ([raw file](https://github.com/flexflow/FlexFlow/blob/9f935a195353178acec1a67d1ac73b0c6036f0e6/.github/workflows/shell-check.yml#L12)):*
> ```YAML
>         uses: ludeeus/action-shellcheck@master
>         with:
>           shell: bash
> ```

Why? (not blocking, just curious)

**Comment by lambda7xx** [comment]
*[`.github/workflows/gpt-ci.yml-old` line  at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-Ndpm6pp4NQ4m2_2Ogep:-NfGkHf7EmmJtPszGoPB:b-6hryh3) ([raw file](https://github.com/flexflow/FlexFlow/blob/9f935a195353178acec1a67d1ac73b0c6036f0e6/.github/workflows/gpt-ci.yml-old#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Just remove--we have git history and `master`
</blockquote></details>

you mean we delete this file？

**Review by lockshaw — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1083)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aquan9)

___
*[`.github/workflows/gpt-ci.yml-old` line  at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-Ndpm6pp4NQ4m2_2Ogep:-NfGxWP428gnheAqUmEM:b2nhswy) ([raw file](https://github.com/flexflow/FlexFlow/blob/9f935a195353178acec1a67d1ac73b0c6036f0e6/.github/workflows/gpt-ci.yml-old#L)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

you mean we delete this file？
</blockquote></details>

Yes

**Review by lambda7xx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1083)* status: 8 of 10 files reviewed, all discussions resolved (waiting on @aquan9 and @lockshaw)

___
*[`run.sh` line  at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NdplszOBc3w92ipxoDG:-NfGk1A98Xw7IVM7a_3p:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9f935a195353178acec1a67d1ac73b0c6036f0e6/run.sh#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Don't know how this file made it in but it should be removed
</blockquote></details>

Done.

**Review by lockshaw — CHANGES_REQUESTED** [review]
From slack: 

> Let's disable "Build FlexFlow with CMake", "Build and Install FlexFlow in a Docker Container", "GPU CI Concierge", "pip-install", "Build FlexFlow with the Makefile", and everything under "gpu-ci" for now
> Those currently are expected to fail on repo refactor
> So for now only keep "clang-format", "Library CMake Build", and "Shellcheck"

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-:-NfPglfC2N4AVEXcPtF8:bwzs58b)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aquan9)

**Review by lambda7xx — COMMENTED** [review]
approve

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1083)* status: all files reviewed, 6 unresolved discussions (waiting on @aquan9 and @lambda7xx)

___
*[`.github/workflows/build.yml` line 0 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NfYFi9m6YeF88iOXjNy:-NfYFi9m6YeF88iOXjNz:b-m2xvzo) ([raw file](https://github.com/flexflow/FlexFlow/blob/f09f7fd7e38721b55981eafdeede28a4ff3578ef/.github/workflows/build.yml#L0)):*
Delete instead of commenting out
___
*[`.github/workflows/docker-build.yml` line 0 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NfYFkme5Mo_jVMT-ZY4:-NfYFkme5Mo_jVMT-ZY5:b-m2xvzo) ([raw file](https://github.com/flexflow/FlexFlow/blob/f09f7fd7e38721b55981eafdeede28a4ff3578ef/.github/workflows/docker-build.yml#L0)):*
Delete instead of commenting out
___
*[`.github/workflows/per-lib-check.yml` line 47 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NfYF_7v8ThqyUJzwhPE:-NfYF_7v8ThqyUJzwhPF:b3wzo48) ([raw file](https://github.com/flexflow/FlexFlow/blob/f09f7fd7e38721b55981eafdeede28a4ff3578ef/.github/workflows/per-lib-check.yml#L47)):*
> ```YAML
>           auto-activate-base: false
> 
>       # - name: Build lib ${{ matrix.library }}
> ```

Why was this removed? We still want the library checks
___
*[`.github/workflows/pip-install.yml` line 0 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NfYFRNx02OzIoLpsfeV:-NfYFRNx02OzIoLpsfeW:bhs726l) ([raw file](https://github.com/flexflow/FlexFlow/blob/f09f7fd7e38721b55981eafdeede28a4ff3578ef/.github/workflows/pip-install.yml#L0)):*
Delete, don't just comment out
___
*[`packaging/docker/build.sh` line 0 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NfYFFH3EYuE9k-pCV-1:-NfYFFH3EYuE9k-pCV-2:bhs726l) ([raw file](https://github.com/flexflow/FlexFlow/blob/f09f7fd7e38721b55981eafdeede28a4ff3578ef/packaging/docker/build.sh#L0)):*
Delete, don't just comment out
___
*[`packaging/docker/flexflow-environment/Dockerfile-old` line 0 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NfYFJRS32r3RNl5q5KW:-NfYFJRS32r3RNl5q5KX:b27e9zc) ([raw file](https://github.com/flexflow/FlexFlow/blob/4a6b2c9328180d905abbf53d0de166f964d662cc/packaging/docker/flexflow-environment/Dockerfile-old#L0)):*
Delete--we always have it in the git history

**Comment by lambda7xx** [comment]
*[`.github/workflows/per-lib-check.yml` line 47 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NfYF_7v8ThqyUJzwhPE:-NfbCex08R5GZH-ZShKI:bymbll0) ([raw file](https://github.com/flexflow/FlexFlow/blob/f09f7fd7e38721b55981eafdeede28a4ff3578ef/.github/workflows/per-lib-check.yml#L47)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why was this removed? We still want the library checks
</blockquote></details>

I comment these to pass check, otherwise

**Comment by lambda7xx** [comment]
*[`.github/workflows/per-lib-check.yml` line 47 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NfYF_7v8ThqyUJzwhPE:-NfbClTiDqkcleAEegMs:bisgytc) ([raw file](https://github.com/flexflow/FlexFlow/blob/f09f7fd7e38721b55981eafdeede28a4ff3578ef/.github/workflows/per-lib-check.yml#L47)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

I comment these to pass check, otherwise
</blockquote></details>

In file included from /home/runner/work/FlexFlow/FlexFlow/lib/op-attrs/include/op-attrs/datatype.h:4,

[652](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:653) from /home/runner/work/FlexFlow/FlexFlow/lib/op-attrs/include/op-attrs/parallel\_tensor\_shape.h:4,

[653](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:654) from /home/runner/work/FlexFlow/FlexFlow/lib/op-attrs/include/op-attrs/ops/aggregate.h:5,

[654](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:655) from /home/runner/work/FlexFlow/FlexFlow/lib/op-attrs/src/aggregate.cc:1:

[655](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:656)/home/runner/work/FlexFlow/FlexFlow/lib/utils/include/utils/fmt.h:39:54: error: static assertion failed: stack\_vector<test\_types::fmtable, 5> must be fmtable

[656](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:657) 39 | static\_assert(::FlexFlow::is\_fmtable<\_\_VA\_ARGS\_\_>::value, \\

[657](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:658) | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~

[658](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:659)/home/runner/work/FlexFlow/FlexFlow/lib/utils/include/utils/stack\_vector.h:312:1: note: in expansion of macro ‘CHECK\_FMTABLE’

[659](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:660) 312 | CHECK\_FMTABLE(stack\_vector<test\_types::fmtable, 5>);

[660](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:661) | ^~~~~~~~~~~~~

[661](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:662)make\[3\]: \*\*\* \[lib/op-attrs/CMakeFiles/op-attrs.dir/build.make:76: lib/op-attrs/CMakeFiles/op-attrs.dir/src/aggregate.cc.o\] Error 1

[662](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:663)make\[2\]: \*\*\* \[CMakeFiles/Makefile2:1874: lib/op-attrs/CMakeFiles/op-attrs.dir/all\] Error 2

[663](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:664)make\[1\]: \*\*\* \[CMakeFiles/Makefile2:1776: lib/runtime/CMakeFiles/runtime.dir/rule\] Error 2

[664](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:665)make: \*\*\* \[Makefile:687: runtime\] Error 2

[665](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:666)Error: Process completed with exit code 2.

**Review by lambda7xx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1083)* status: 12 of 18 files reviewed, 6 unresolved discussions (waiting on @aquan9 and @lockshaw)

___
*[`.github/workflows/build.yml` line  at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NfYFi9m6YeF88iOXjNy:-Nfa9fxNBBNdIY264h21:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f09f7fd7e38721b55981eafdeede28a4ff3578ef/.github/workflows/build.yml#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete instead of commenting out
</blockquote></details>

Done.
___
*[`.github/workflows/docker-build.yml` line  at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NfYFkme5Mo_jVMT-ZY4:-Nfa9jIG6HcdIbe8_vN_:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f09f7fd7e38721b55981eafdeede28a4ff3578ef/.github/workflows/docker-build.yml#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete instead of commenting out
</blockquote></details>

Done.
___
*[`.github/workflows/pip-install.yml` line  at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NfYFRNx02OzIoLpsfeV:-Nfa9ob5Ed7jy6LlQFjk:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f09f7fd7e38721b55981eafdeede28a4ff3578ef/.github/workflows/pip-install.yml#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete, don't just comment out
</blockquote></details>

Done.
___
*[`packaging/docker/build.sh` line  at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NfYFFH3EYuE9k-pCV-1:-Nfa9sURAyPTrrUx3eGN:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f09f7fd7e38721b55981eafdeede28a4ff3578ef/packaging/docker/build.sh#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete, don't just comment out
</blockquote></details>

Done.
___
*[`packaging/docker/flexflow-environment/Dockerfile-old` line  at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NfYFJRS32r3RNl5q5KW:-Nfa9aqC6fltu-z11Q43:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4a6b2c9328180d905abbf53d0de166f964d662cc/packaging/docker/flexflow-environment/Dockerfile-old#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete--we always have it in the git history
</blockquote></details>

Done.

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1083)* status: all files reviewed, 1 unresolved discussion (waiting on @aquan9 and @lambda7xx)

___
*[`.github/workflows/per-lib-check.yml` line 47 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NfYF_7v8ThqyUJzwhPE:-Nfd7NeBEbxD4gCy3UGH:b6hdz71) ([raw file](https://github.com/flexflow/FlexFlow/blob/f09f7fd7e38721b55981eafdeede28a4ff3578ef/.github/workflows/per-lib-check.yml#L47)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

In file included from /home/runner/work/FlexFlow/FlexFlow/lib/op-attrs/include/op-attrs/datatype.h:4,

[652](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:653) from /home/runner/work/FlexFlow/FlexFlow/lib/op-attrs/include/op-attrs/parallel\_tensor\_shape.h:4,

[653](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:654) from /home/runner/work/FlexFlow/FlexFlow/lib/op-attrs/include/op-attrs/ops/aggregate.h:5,

[654](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:655) from /home/runner/work/FlexFlow/FlexFlow/lib/op-attrs/src/aggregate.cc:1:

[655](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:656)/home/runner/work/FlexFlow/FlexFlow/lib/utils/include/utils/fmt.h:39:54: error: static assertion failed: stack\_vector<test\_types::fmtable, 5> must be fmtable

[656](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:657) 39 | static\_assert(::FlexFlow::is\_fmtable<\_\_VA\_ARGS\_\_>::value, \\

[657](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:658) | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~

[658](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:659)/home/runner/work/FlexFlow/FlexFlow/lib/utils/include/utils/stack\_vector.h:312:1: note: in expansion of macro ‘CHECK\_FMTABLE’

[659](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:660) 312 | CHECK\_FMTABLE(stack\_vector<test\_types::fmtable, 5>);

[660](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:661) | ^~~~~~~~~~~~~

[661](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:662)make\[3\]: \*\*\* \[lib/op-attrs/CMakeFiles/op-attrs.dir/build.make:76: lib/op-attrs/CMakeFiles/op-attrs.dir/src/aggregate.cc.o\] Error 1

[662](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:663)make\[2\]: \*\*\* \[CMakeFiles/Makefile2:1874: lib/op-attrs/CMakeFiles/op-attrs.dir/all\] Error 2

[663](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:664)make\[1\]: \*\*\* \[CMakeFiles/Makefile2:1776: lib/runtime/CMakeFiles/runtime.dir/rule\] Error 2

[664](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:665)make: \*\*\* \[Makefile:687: runtime\] Error 2

[665](https://github.com/flexflow/FlexFlow/actions/runs/6363039127/job/17278411470?pr=1083#step:7:666)Error: Process completed with exit code 2.
</blockquote></details>

That's a build error, which is the whole point of running these (because it's in op-attrs it's currently not mandatory that it pass). Re-enabling these is correct 
___
*[`packaging/docker/flexflow-environment/Dockerfile-old` line  at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NfYFJRS32r3RNl5q5KW:-Nfd7qqE2a_PMm2pkCiF:bh4o9hf) ([raw file](https://github.com/flexflow/FlexFlow/blob/4a6b2c9328180d905abbf53d0de166f964d662cc/packaging/docker/flexflow-environment/Dockerfile-old#L)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm still seeing the file -- I think you forgot to delete `Dockerfile-old`

**Review by lambda7xx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1083)* status: all files reviewed, 1 unresolved discussion (waiting on @aquan9 and @lockshaw)

___
*[`packaging/docker/flexflow-environment/Dockerfile-old` line  at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NfYFJRS32r3RNl5q5KW:-NfdDMBpAJu1ZoPSlTh6:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4a6b2c9328180d905abbf53d0de166f964d662cc/packaging/docker/flexflow-environment/Dockerfile-old#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I'm still seeing the file -- I think you forgot to delete `Dockerfile-old`
</blockquote></details>

Done.

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1083)* status: all files reviewed, 1 unresolved discussion (waiting on @aquan9 and @lambda7xx)

___
*[`.github/workflows/per-lib-check.yml` line 48 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1083#-NfdF3gQAYVvoNMOxfu9:-NfdF3gQAYVvoNMOxfuA:b-na35se) ([raw file](https://github.com/flexflow/FlexFlow/blob/04bab53181553f936160d4696e8a9598e110ae04/.github/workflows/per-lib-check.yml#L48)):*
> ```YAML
> 
>       - name: Build lib ${{ matrix.library }}
>         # run: |
> ```

Why did you comment this again? This should be uncommented

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1083)* status: all files reviewed, 1 unresolved discussion (waiting on @aquan9 and @lambda7xx)

**Review by lockshaw — DISMISSED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1083)* status: all files reviewed, 1 unresolved discussion (waiting on @aquan9 and @lambda7xx)

**Review by lockshaw — APPROVED** [review]
> Reviewed 10 of 11 files at r10, 3 of 3 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1083)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aquan9)

**Pull request merged**
