### PR TITLE
op-attrs is_valid and shape inference functionality

### PR DESCRIPTION
**Pull request by stelleg**
**Description of changes:**
Fixing up is_valid and shape inference implementations and tests for repo-refactor.

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1014)

### CODE REVIEW

**Review by lockshaw — COMMENTED** [review]
Tests for `ConcatAttrs::is_valid`?

> Reviewed 6 of 6 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1014#-:-Ndq6F480vt4pAlfjyrZ:bz6lwv)* status: all files reviewed, 5 unresolved discussions (waiting on @stelleg)

___
*[`lib/op-attrs/include/op-attrs/ops/concat.h` line 17 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1014#-Ndq5vs-31xKiQptDKXK:-Ndq5vs-31xKiQptDKXL:beb9vix) ([raw file](https://github.com/flexflow/FlexFlow/blob/290e4c92dd569f00590864c99b3bfaf846f5afe3/lib/op-attrs/include/op-attrs/ops/concat.h#L17)):*
> ```objc
> 
> FF_VISITABLE_STRUCT(ConcatAttrs, axis);
> CHECK_VALID_OP_ATTR(ConcatAttrs);
> ```

Especially with visitable types it's nice to use functions instead to keep the actual data definition easier to read



_Suggestion:_
```objc
struct ConcatAttrs {
  ff_dim_t axis;
};

FF_VISITABLE_STRUCT(ConcatAttrs, axis);
CHECK_VALID_OP_ATTR(ConcatAttrs);

bool is_valid(ConcatAttrs const &, std::vector<ParallelTensorShape> const &inputs);
```
___
*[`lib/op-attrs/src/concat.cc` line 7 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1014#-Ndq4uQ6DSgRxVRw5_P_:-Ndq4uQ6DSgRxVRw5_Pa:bbxpiob) ([raw file](https://github.com/flexflow/FlexFlow/blob/290e4c92dd569f00590864c99b3bfaf846f5afe3/lib/op-attrs/src/concat.cc#L7)):*
> ```cpp
> bool ConcatAttrs::is_valid(
>     std::vector<ParallelTensorShape> const &input) const {
>   bool valid = true;
> ```

Tensor shape validity should be checked somewhere else (as it's common for all of the attrs--an attr is only valid if all of its input shapes are valid) so this can be removed. Useful checks might be things like "is the number of arguments greater than 0" and "are the shapes actually concatable along the given dimension". That said, implementing shape inference (i.e. `get_output_shape`) is much more important currently than implementing `is_valid`
___
*[`lib/op-attrs/src/parallel_tensor_shape.cc` line 40 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1014#-Ndq5lj56vgGbm_4VfWG:-Ndq5lj56vgGbm_4VfWH:b-qm0876) ([raw file](https://github.com/flexflow/FlexFlow/blob/290e4c92dd569f00590864c99b3bfaf846f5afe3/lib/op-attrs/src/parallel_tensor_shape.cc#L40)):*
> ```cpp
> }
> 
> bool ParallelTensorShape::is_valid() {
> ```

Why was this added? (also why not `const`?)
___
*[`lib/op-attrs/test/test_valid.cc` line 8 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1014#-Ndq5TLUEJHHoUecA9Pz:-Ndq5TLUEJHHoUecA9Q-:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/258e4b3944a6dd9b92579dcefd8b832add1db20e/lib/op-attrs/test/test_valid.cc#L8)):*
> ```cpp
> using namespace FlexFlow;
> 
> TEST_CASE("gather_valid") {
> ```





_Suggestion:_
```cpp
TEST_CASE("GatherAttrs::is_valid") {
```
___
*[`lib/op-attrs/test/test_valid.cc` line 14 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1014#-Ndq5euaDpC_zZg11mY7:-Ndq5euaDpC_zZg11mY8:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/258e4b3944a6dd9b92579dcefd8b832add1db20e/lib/op-attrs/test/test_valid.cc#L14)):*
> ```cpp
>   TensorDims tds({2,2}); 
>   ParallelTensorShape p(tds, DataType::FLOAT); 
>   RC_ASSERT(g.is_valid(p, p));  
> ```





_Suggestion:_
```cpp
  CHECK(g.is_valid(p, p));
```

**Comment by stelleg** [comment]
@lockshaw Added shape inference for the following ops: 
```
lib/op-attrs/src/cast.cc
lib/op-attrs/src/combine.cc
lib/op-attrs/src/concat.cc
lib/op-attrs/src/dropout.cc
lib/op-attrs/src/element_binary.cc
lib/op-attrs/src/element_unary.cc
lib/op-attrs/src/flat.cc
lib/op-attrs/src/reduction.cc
```

Let me know if there are others if you need pushed through.

Cheers,
George

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1014)* status: all files reviewed, 11 unresolved discussions (waiting on @stelleg)

___
*[`lib/op-attrs/src/cast.cc` line 8 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1014#-NfPeiXqCTHldK7TLNdO:-NfPeiXqCTHldK7TLNdP:b-hbrjpy) ([raw file](https://github.com/flexflow/FlexFlow/blob/31a8f2dbcc85bbe1b017d99419c90768bb6a54bf/lib/op-attrs/src/cast.cc#L8)):*
> ```cpp
>                                      ParallelTensorShape const &input) {
>   ParallelTensorShape output = input;
>   output.data_type = attrs.dtype;
> ```

return?
___
*[`lib/op-attrs/src/concat.cc` line 18 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1014#-NfPewPT7kYKEvoS8eiA:-NfPewPT7kYKEvoS8eiB:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/31a8f2dbcc85bbe1b017d99419c90768bb6a54bf/lib/op-attrs/src/concat.cc#L18)):*
> ```cpp
>                      std::vector<ParallelTensorShape> const &inputs) {
>   ParallelTensorShape output = inputs[0];
>   for (auto &i : inputs) {
> ```





_Suggestion:_
```cpp
  for (ParallelTensorShape const &i : inputs) {
```
___
*[`lib/op-attrs/src/concat.cc` line 19 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1014#-NfPf4EDEMwGJLjSv6wn:-NfPf4EDEMwGJLjSv6wo:bsj97hj) ([raw file](https://github.com/flexflow/FlexFlow/blob/31a8f2dbcc85bbe1b017d99419c90768bb6a54bf/lib/op-attrs/src/concat.cc#L19)):*
> ```cpp
>   ParallelTensorShape output = inputs[0];
>   for (auto &i : inputs) {
>     output.at(attrs.axis).size += i.at(attrs.axis).size;
> ```

It might be clearer to use `sum` from `containers.h` here instead
___
*[`lib/op-attrs/src/dropout.cc` line 8 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1014#-NfPfE3F990L9w-ph-b7:-NfPfE3F990L9w-ph-b8:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/31a8f2dbcc85bbe1b017d99419c90768bb6a54bf/lib/op-attrs/src/dropout.cc#L8)):*
> ```cpp
>                                      ParallelTensorShape const &input) {
>   ParallelTensorShape output = input;
>   return output;
> ```





_Suggestion:_
```cpp
  return input;
```
___
*[`lib/op-attrs/src/element_binary.cc` line 22 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1014#-NfPg8ByE1AWuxO5EwGb:-NfPg8ByE1AWuxO5EwGc:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/31a8f2dbcc85bbe1b017d99419c90768bb6a54bf/lib/op-attrs/src/element_binary.cc#L22)):*
> ```cpp
>     } else {
>       assert(false && "Operands could not be broadcast together");
>       exit(0);
> ```





_Suggestion:_
```cpp
      throw mk_runtime_error("Operands could not be broadcast together: in1={} in2={}", in1, in2);
```
___
*[`lib/op-attrs/src/element_binary.cc` line 23 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1014#-NfPfyyA4ag50gPxMsZf:-NfPfyyA4ag50gPxMsZg:b-qdapu5) ([raw file](https://github.com/flexflow/FlexFlow/blob/31a8f2dbcc85bbe1b017d99419c90768bb6a54bf/lib/op-attrs/src/element_binary.cc#L23)):*
> ```cpp
>       assert(false && "Operands could not be broadcast together");
>       exit(0);
>     }
> ```

Is there really not a clearer way to rewrite this?



_Code quote:_
```cpp
  ParallelTensorShape output = in1.num_dims() >= in2.num_dims() ? in1 : in2;
  for (int i = 0; i < output.num_dims(); i++) {
    if (i >= in1.num_dims()) {
      output.at(ff_dim_t(i)) = in2.at(ff_dim_t(i));
    } else if (i >= in2.num_dims()) {
      output.at(ff_dim_t(i)) = in1.at(ff_dim_t(i));
    } else if (in1.at(ff_dim_t(i)).size == in2.at(ff_dim_t(i)).size) {
      output.at(ff_dim_t(i)) = in1.at(ff_dim_t(i));
    } else if (in1.at(ff_dim_t(i)).size == 1) {
      output.at(ff_dim_t(i)) = in2.at(ff_dim_t(i));
    } else if (in2.at(ff_dim_t(i)).size == 1) {
      output.at(ff_dim_t(i)) = in1.at(ff_dim_t(i));
    } else {
      assert(false && "Operands could not be broadcast together");
      exit(0);
    }
```
___
*[`lib/op-attrs/src/element_unary.cc` line 8 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1014#-NfPfI4c-CNttOEIgLMr:-NfPfI4c-CNttOEIgLMs:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/31a8f2dbcc85bbe1b017d99419c90768bb6a54bf/lib/op-attrs/src/element_unary.cc#L8)):*
> ```cpp
>                                      ParallelTensorShape const &in) {
>   ParallelTensorShape out = in;
>   return out;
> ```





_Suggestion:_
```cpp
  return in;
```
___
*[`lib/op-attrs/src/flat.cc` line 26 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1014#-NfPfSXq6siVX9m-0a2J:-NfPfSXq6siVX9m-0a2K:bk4bt3i) ([raw file](https://github.com/flexflow/FlexFlow/blob/31a8f2dbcc85bbe1b017d99419c90768bb6a54bf/lib/op-attrs/src/flat.cc#L26)):*
> ```cpp
>       input.at(ff_dim_t(Input::WIDTH)).size;
>   output_shape.at(ff_dim_t(Output::CHANNEL)).degree =
>       input.at(ff_dim_t(Input::CHANNEL)).degree;
> ```

Generalize this to arbitrary dimensions, not just 4



_Code quote:_
```cpp
  output_shape.at(ff_dim_t(Output::CHANNEL)).size =
      input.at(ff_dim_t(Input::CHANNEL)).size *
      input.at(ff_dim_t(Input::HEIGHT)).size *
      input.at(ff_dim_t(Input::WIDTH)).size;
  output_shape.at(ff_dim_t(Output::CHANNEL)).degree =
      input.at(ff_dim_t(Input::CHANNEL)).degree;
```
___
*[`lib/op-attrs/src/reduction.cc` line 7 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1014#-NfPfdPTDBSPDZs4opuz:-NfPfdPTDBSPDZs4opv-:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/31a8f2dbcc85bbe1b017d99419c90768bb6a54bf/lib/op-attrs/src/reduction.cc#L7)):*
> ```cpp
> ParallelTensorShape get_output_shape(ReductionAttrs const &attrs,
>                                      ParallelTensorShape const &input_shape) {
>   ParallelTensorShape output(input_shape.dims, input_shape.data_type);
> ```





_Suggestion:_
```cpp
  ParallelTensorShape output = input;
```

**Comment by reyna-abhyankar** [comment]
Move to #1183

**Pull request closed without merging**
