### PR TITLE
[Keras] Surface up rsqrt in keras.backend.internal

### LINKED ISSUE #611: Add sqrt op or surface up rsqrt

### PR DESCRIPTION
**Pull request by soumyac1999**
**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #611 

Issues closed by this PR:
- Closes #611 

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

### CODE REVIEW

**Comment by soumyac1999** [comment]
Discussion item: keras.backend does not have a rsqrt but we are adding one in keras.backend.internal (which is not expected to be used by users). Are we okay with this?

**Comment by lockshaw** [comment]
Does `keras.backend.internal` exist in Keras? If so it might be nice to have some flexflow-specific import like `keras.backend.flexflow` or something like that

**Comment by soumyac1999** [comment]
`keras.backend,internal` doesn't exist in Keras. We had added it since keras.backend only has functions and we needed classes for those. (Discussion in the last few comments of #468). I don't have strong preferences with either backend.internal or backend.flexflow. Let me know what you think and I'll update accordingly.

**Comment by soumyac1999** [comment]
An alternative is to add a sqrt op since keras.backend.sqrt exists. I'm not too keen on doing this right now given there are other higher priority things and rsqrt works.

**Comment by lockshaw** [comment]
`backend.internal` is fine then

**Review by lockshaw — CHANGES_REQUESTED** [review]
Can you add a basic test model?

**Review by lockshaw — APPROVED** [review]

**Pull request merged**
