### PR TITLE
Update CUDA toolchain version

### PR DESCRIPTION
**Pull request by oOTigger**
Update Flake files to support Sapling CUDA environment

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1399)

### CODE REVIEW

**Review by lockshaw — CHANGES_REQUESTED** [review]
You're failing CI because you dropped the recent changes to the flake.nix file introduced for coverage stuff

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1399#-:-NzAJNbFACIficBcwVMU:burn7nk)* status: all files reviewed, 1 unresolved discussion (waiting on @oOTigger)

___
*[`flake.nix` line 124 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1399#-NzAJU2oDcndlRu8A0PA:-NzAJU2oDcndlRu8A0PB:b-qwjq7p) ([raw file](https://github.com/flexflow/FlexFlow/blob/aeee8efecb0d612aaea17bd02a6db57edf0c110e/flake.nix#L124)):*
> ```Nix
>               jq
>               gh
>               lcov # for code coverage
> ```

Removing this creates a problem, should be added back in

**Review by oOTigger — COMMENTED** [review]
fixed

**Review by oOTigger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1399)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lockshaw)

___
*[`flake.nix` line 124 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1399#-NzAJU2oDcndlRu8A0PA:-NzBavSY4jHUeQETWZlc:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/aeee8efecb0d612aaea17bd02a6db57edf0c110e/flake.nix#L124)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Removing this creates a problem, should be added back in
</blockquote></details>

Done.

**Review by lockshaw — CHANGES_REQUESTED** [review]
This needs the flake.lock file too

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1399#-:-NzBhnOu2O3UT7-qBDMz:bgowrnh)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oOTigger)

**Review by oOTigger — COMMENTED** [review]
added

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1399#-:-NzDDyWe6gzAmNnIDG8d:b-7tfmjp)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @oOTigger)

**Review by oOTigger — COMMENTED** [review]
added flake.lock file

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1399#-:-NzDECkn4EN2gEGFObFB:b-wytzl9)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @oOTigger)

**Review by oOTigger — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1399)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oOTigger)

**Review by lockshaw — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1399)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oOTigger)

**Review by lockshaw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1399)* status: all files reviewed, 4 unresolved discussions (waiting on @oOTigger)

___
*[`flake.nix` line 32 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1399#-NzElWZT05Y-V7EtAFi_:-NzElWZT05Y-V7EtAFia:b-gydp52) ([raw file](https://github.com/flexflow/FlexFlow/blob/fa0ae2c89e4b4d585032e8d3127857dff14e60f5/flake.nix#L32)):*
> ```Nix
>       stdenv = pkgs.cudaPackages.backendStdenv;
>       mkShell = pkgs.mkShell.override {
>         # stdenv = pkgs.cudaPackages.backendStdenv;
> ```

Don't comment things out, remove;
___
*[`flake.nix` line 33 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1399#-NzElYN1CCZUhW0awPfD:-NzElYN1CCZUhW0awPfE:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/fa0ae2c89e4b4d585032e8d3127857dff14e60f5/flake.nix#L33)):*
> ```Nix
>       mkShell = pkgs.mkShell.override {
>         # stdenv = pkgs.cudaPackages.backendStdenv;
>         stdenv = stdenv;
> ```





_Suggestion:_
```Nix
  inherit stdenv;
```
___
*[`flake.nix` line 38 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1399#-NzElUlOEDj0J5xt6D-T:-NzElUlOEDj0J5xt6D-U:b-gydp5f) ([raw file](https://github.com/flexflow/FlexFlow/blob/fa0ae2c89e4b4d585032e8d3127857dff14e60f5/flake.nix#L38)):*
> ```Nix
>     {
>       packages = {
>         # legion = pkgs.callPackage ./.flake/pkgs/legion.nix { };
> ```

Don't comment things out, remove.
___
*[`flake.nix` line 99 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1399#-NzElPqU8fulI1m1TkUN:-NzElPqU8fulI1m1TkUO:bfrw6co) ([raw file](https://github.com/flexflow/FlexFlow/blob/411bc12dd47a8fe6fff3c434061cfae28f88dd88/flake.nix#L99)):*
> ```Nix
>               cudaPackages.cuda_cudart
>               tl-expected
>               lcov # for code coverage
> ```

You removed `lcov` again

**Review by oOTigger — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1399)* status: all files reviewed, 4 unresolved discussions (waiting on @oOTigger)

**Review by oOTigger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1399)* status: all files reviewed, 4 unresolved discussions (waiting on @lockshaw)

___
*[`flake.nix` line 32 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1399#-NzElWZT05Y-V7EtAFi_:-NzKv7Dx1rIyRnjh3n2_:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/fa0ae2c89e4b4d585032e8d3127857dff14e60f5/flake.nix#L32)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Don't comment things out, remove;
</blockquote></details>

Done.
___
*[`flake.nix` line 33 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1399#-NzElYN1CCZUhW0awPfD:-NzKv81z02icQWST8PWX:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/fa0ae2c89e4b4d585032e8d3127857dff14e60f5/flake.nix#L33)):*
> ```Nix
>       mkShell = pkgs.mkShell.override {
>         # stdenv = pkgs.cudaPackages.backendStdenv;
>         stdenv = stdenv;
> ```

Done.
___
*[`flake.nix` line 38 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1399#-NzElUlOEDj0J5xt6D-T:-NzKv8o09mqBBPuTM9EW:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/fa0ae2c89e4b4d585032e8d3127857dff14e60f5/flake.nix#L38)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Don't comment things out, remove.
</blockquote></details>

Done.
___
*[`flake.nix` line 99 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1399#-NzElPqU8fulI1m1TkUN:-NzKv9OVBejlAf0qb-c3:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/411bc12dd47a8fe6fff3c434061cfae28f88dd88/flake.nix#L99)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

You removed `lcov` again
</blockquote></details>

Done.

**Review by lockshaw — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1399)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oOTigger)

**Pull request closed without merging**
