### PR TITLE
Ci update

### LINKED ISSUE #855: Per lib build checks in CI

### PR DESCRIPTION
**Pull request by aquan9**
**Description of changes:**
Add format checking back into repo-refactor. 
I updated the list of directories that it checks, and broke up the directories in lib into separate checks for a little bit more speed. 

I disabled fail-fast so that you can get a thorough report of everything that is incorrectly formatted. 

**Related Issues:**

Linked Issues:
- Issue #855

Issues closed by this PR:
N/A

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

N/A

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/898)

### CODE REVIEW

**Review by lockshaw — CHANGES_REQUESTED** [review]
If this PR isn't going to include build, can you remove the "Closes" part so it doesn't close that issue until it's actually fixed?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/898#-:-NaTT2ub6SBjCLl-r2Q3:byriexm)* status: all files reviewed, 10 unresolved discussions (waiting on @aquan9)

___
*[`.github/workflows/clang-format-check.yml` line 11 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/898#-NaTQ0Qq1wZFP2CmHwHo:-NaTQ0Qq1wZFP2CmHwHp:bgw9d7q) ([raw file](https://github.com/flexflow/FlexFlow/blob/880accad85788c1ea12f8977f6c5f8501d34303e/.github/workflows/clang-format-check.yml#L11)):*
> ```YAML
>       matrix:
>         path:
>           - check: "lib/compiler"
> ```

Why is `lib` broken up into subdirectories instead of just checking `lib/`
___
*[`.github/workflows/clang-format-check.yml` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/898#-NaTQKMZA7JJ5XsoULJ6:-NaTQKMZA7JJ5XsoULJ7:buq8puv) ([raw file](https://github.com/flexflow/FlexFlow/blob/880accad85788c1ea12f8977f6c5f8501d34303e/.github/workflows/clang-format-check.yml#L13)):*
> ```YAML
>           - check: "lib/compiler"
>           - check: "lib/ffi"
>           - check: "lib/fmt"
> ```

Should not be included (this actually shouldn't 
___
*[`.github/workflows/clang-format-check.yml` line 17 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/898#-NaTPlsD7UmgNVsVESyN:-NaTPlsD7UmgNVsVESyO:b364ppu) ([raw file](https://github.com/flexflow/FlexFlow/blob/880accad85788c1ea12f8977f6c5f8501d34303e/.github/workflows/clang-format-check.yml#L17)):*
> ```YAML
>           - check: "lib/op-attrs"
>           - check: "lib/pcg"
>           - check: "lib/runtime/ffi"
> ```

Why is runtime broken up into these subdirectories?
___
*[`.github/workflows/clang-format-check.yml` line 22 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/898#-NaTPozc0zYgXmp7Fvz_:-NaTPozc0zYgXmp7Fvza:b-4co7xi) ([raw file](https://github.com/flexflow/FlexFlow/blob/880accad85788c1ea12f8977f6c5f8501d34303e/.github/workflows/clang-format-check.yml#L22)):*
> ```YAML
>           - check: "lib/runtime/test"
>           - check: "lib/substitutions"
>           - check: "lib/triton"
> ```

`triton` should be ignored (it's third-party code)
___
*[`.github/workflows/clang-format-check.yml` line 24 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/898#-NaTSoiG11fCgeopt5NE:-NaTSoiG11fCgeopt5NF:bc0x4op) ([raw file](https://github.com/flexflow/FlexFlow/blob/880accad85788c1ea12f8977f6c5f8501d34303e/.github/workflows/clang-format-check.yml#L24)):*
> ```YAML
>           - check: "lib/triton"
>           - check: "lib/utils"
>           - check: "python"
> ```

Ignore `python` directory as it will eventually be removed in `repo-refactor`
___
*[`.github/workflows/clang-format-check.yml` line 25 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/898#-NaTQB6U-T_fohPogJ6g:-NaTQB6U-T_fohPogJ6h:bh0e7n3) ([raw file](https://github.com/flexflow/FlexFlow/blob/880accad85788c1ea12f8977f6c5f8501d34303e/.github/workflows/clang-format-check.yml#L25)):*
> ```YAML
>           - check: "lib/utils"
>           - check: "python"
>           - check: "scripts"
> ```

I don't think there are any C/C++ programs in `scripts`
___
*[`.github/workflows/clang-format-check.yml` line 29 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/898#-NaTSa2X2caBQnZymeLr:-NaTSa2X2caBQnZymeLs:b-oqx6xl) ([raw file](https://github.com/flexflow/FlexFlow/blob/880accad85788c1ea12f8977f6c5f8501d34303e/.github/workflows/clang-format-check.yml#L29)):*
> ```YAML
>           - check: "examples"
>           - check: "bindings"
>           - check: "config"
> ```

I don't think there are any C/C++ programs in `config`
___
*[`.github/workflows/clang-format-check.yml` line 30 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/898#-NaTSe4l9GYn5jyR-7Iu:-NaTSe4l9GYn5jyR-7Iv:b-y921c1) ([raw file](https://github.com/flexflow/FlexFlow/blob/880accad85788c1ea12f8977f6c5f8501d34303e/.github/workflows/clang-format-check.yml#L30)):*
> ```YAML
>           - check: "bindings"
>           - check: "config"
>           - check: "deps"
> ```

`deps` is third-party code and should not be checked
___
*[`.github/workflows/clang-format-check.yml` line 31 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/898#-NaTSiE3023ZMZ6H1Kpm:-NaTSiE3023ZMZ6H1Kpn:botpcno) ([raw file](https://github.com/flexflow/FlexFlow/blob/880accad85788c1ea12f8977f6c5f8501d34303e/.github/workflows/clang-format-check.yml#L31)):*
> ```YAML
>           - check: "config"
>           - check: "deps"
>           - check: "packaging"
> ```

I don't think there are any C/C++ programs in `packaging`
___
*[`.github/workflows/clang-format-check.yml` line 32 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/898#-NaTSlPF0EzXDaDOTbEA:-NaTSlPF0EzXDaDOTbEB:bhqdd6z) ([raw file](https://github.com/flexflow/FlexFlow/blob/880accad85788c1ea12f8977f6c5f8501d34303e/.github/workflows/clang-format-check.yml#L32)):*
> ```YAML
>           - check: "deps"
>           - check: "packaging"
>           - check: "substitutions"
> ```

There aren't any C/C++ programs in `substitutions`

**Review by lockshaw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/898)* status: all files reviewed, 10 unresolved discussions (waiting on @aquan9)

___
*[`.github/workflows/clang-format-check.yml` line 11 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/898#-NaTQ0Qq1wZFP2CmHwHo:-NaTTHxgBCr07cxMR95s:bxgp216) ([raw file](https://github.com/flexflow/FlexFlow/blob/880accad85788c1ea12f8977f6c5f8501d34303e/.github/workflows/clang-format-check.yml#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is `lib` broken up into subdirectories instead of just checking `lib/`
</blockquote></details>

Just realized you mentioned this in the PR description, but I'm not sure I understand how this speeds things up--are the different checks done in parallel?

**Comment by aquan9** [comment]
Different checks appear to be executed as separate tasks in parallel, and when I was watching them the directories in lib are the ones that took the longest which is why I broke it up into separate checks. I'll remove the set of directories that you mentioned don't need to be checked.

**Comment by aquan9** [comment]
Here is the documentation for CI job matrices that describes their parallelization approach: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

**Review by lockshaw — APPROVED** [review]

**Pull request merged**
