### PR TITLE
Implementations for methods for machine_views and associated modules 

### PR DESCRIPTION
**Pull request by Marsella8**
**Description of changes:**

Implemented NOT_IMPLEMENTED() functions within `machine_view.cc`, `strided_rectangle.cc`, `strided_rectangle_sides.cc`, `device_id.cc`.

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1429)

### CODE REVIEW

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1429)* status: all files reviewed, 7 unresolved discussions (waiting on @Marsella8)

___
*[`lib/pcg/src/strided_rectangle.cc` line 24 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1OyGDKEvaQDHs-565f:-O1OyGDL6mlHENamN5Lx:b-gq191x) ([raw file](https://github.com/flexflow/FlexFlow/blob/4928c9e52dd83db9b762259e102acc3107bfa521/lib/pcg/src/strided_rectangle.cc#L24)):*
> ```cpp
> num_points_t get_num_points(StridedRectangle const &rect) {
>   int num = 1;
>   for (StridedRectangleSide const &side : rect.sides) {
> ```

Replace with `product` from `utils/containers.h`?
___
*[`lib/pcg/src/pcg/machine_view.cc` line 79 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1OyXOE27KKDfFSqBPv:-O1OyXOE27KKDfFSqBPw:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/4928c9e52dd83db9b762259e102acc3107bfa521/lib/pcg/src/pcg/machine_view.cc#L79)):*
> ```cpp
>   }
>   assert(get_device_type(start) == DeviceType::GPU);
>   return make_1d_machine_view(unwrap_gpu(start), num_points, stride);
> ```





_Suggestion:_
```cpp
  } else {
    assert(get_device_type(start) == DeviceType::GPU);
    return make_1d_machine_view(unwrap_gpu(start), num_points, stride);
  }
```
___
*[`lib/pcg/src/pcg/machine_view.cc` line 108 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1OyeOa1nmLu-PORrMG:-O1OyeOa1nmLu-PORrMH:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/4928c9e52dd83db9b762259e102acc3107bfa521/lib/pcg/src/pcg/machine_view.cc#L108)):*
> ```cpp
>   }
>   assert(get_device_type(start) == DeviceType::GPU);
>   return make_1d_machine_view(unwrap_gpu(start), interval_size, stride);
> ```





_Suggestion:_
```cpp
  } else {
    assert(get_device_type(start) == DeviceType::GPU);
    return make_1d_machine_view(unwrap_gpu(start), interval_size, stride);
}
```
___
*[`lib/pcg/test/src/test_machine_view.cc` line 22 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1Oz7w69lxicV3Wz2ZN:-O1Oz7w69lxicV3Wz2ZO:b-vba4ov) ([raw file](https://github.com/flexflow/FlexFlow/blob/4928c9e52dd83db9b762259e102acc3107bfa521/lib/pcg/test/src/test_machine_view.cc#L22)):*
> ```cpp
>     device_id_t start_cpu{cpu_id_t{3}};
> 
>     MachineView gpu_mv{start_gpu, rect};
> ```

Split gpu and cpu processing into subcases--the "declare a whole bunch of stuff, then run a whole bunch of tests on it" makes testcases rather hard to read. It's a lot more readable if the declarations are closer to and associated with their uses
___
*[`lib/pcg/test/src/test_machine_view.cc` line 25 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1Oyr3H2OijgONlUfjK:-O1Oyr3H2OijgONlUfjL:b7ou1kq) ([raw file](https://github.com/flexflow/FlexFlow/blob/4928c9e52dd83db9b762259e102acc3107bfa521/lib/pcg/test/src/test_machine_view.cc#L25)):*
> ```cpp
>     MachineView cpu_mv{start_cpu, rect};
> 
>     CHECK(make_1d_machine_view(
> ```

Can you wrap these in subcases with names that clarify the differences between all these different checks? (if it's testing overloads, for example, it could be `SUBCASE("<the function signature>")`)
___
*[`lib/pcg/test/src/test_strided_rectangle.cc` line 12 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1OzSnt5uwD3N6uJ4xB:-O1OzSnt5uwD3N6uJ4xC:b1sm12a) ([raw file](https://github.com/flexflow/FlexFlow/blob/4928c9e52dd83db9b762259e102acc3107bfa521/lib/pcg/test/src/test_strided_rectangle.cc#L12)):*
> ```cpp
>     StridedRectangleSide result =
>         strided_side_from_size_and_stride(side_size_t{7 * 5}, 5);
>     CHECK(result == side);
> ```

Separate test case (or at least a separate subcase)



_Code quote:_
```cpp
    StridedRectangleSide result =
        strided_side_from_size_and_stride(side_size_t{7 * 5}, 5);
    CHECK(result == side);
```
___
*[`lib/pcg/test/src/test_strided_rectangle.cc` line 24 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1OzVJE8Sjf_MgZ_uPS:-O1OzVJE8Sjf_MgZ_uPT:bxguhxm) ([raw file](https://github.com/flexflow/FlexFlow/blob/4928c9e52dd83db9b762259e102acc3107bfa521/lib/pcg/test/src/test_strided_rectangle.cc#L24)):*
> ```cpp
> 
>     CHECK(get_num_dims(rect) == 3);
>     CHECK(get_side_at_idx(rect, ff_dim_t{0}) == s0);
> ```

At the very least subcases for different functions

**Review by Marsella8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1429)* status: all files reviewed, 7 unresolved discussions (waiting on @lockshaw)

___
*[`lib/pcg/src/strided_rectangle.cc` line 24 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1OyGDKEvaQDHs-565f:-O1rUSJh03BdwJpeFZZG:b8nzs1p) ([raw file](https://github.com/flexflow/FlexFlow/blob/4928c9e52dd83db9b762259e102acc3107bfa521/lib/pcg/src/strided_rectangle.cc#L24)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Replace with `product` from `utils/containers.h`?
</blockquote></details>

Changed (`rect.sides` is of type FFOrdered so direct application of `transform` is not possible, let me know if this is preferrable).
___
*[`lib/pcg/src/pcg/machine_view.cc` line 79 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1OyXOE27KKDfFSqBPv:-O1rWEyMD4llKh0qr4U0:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4928c9e52dd83db9b762259e102acc3107bfa521/lib/pcg/src/pcg/machine_view.cc#L79)):*
> ```cpp
>   }
>   assert(get_device_type(start) == DeviceType::GPU);
>   return make_1d_machine_view(unwrap_gpu(start), num_points, stride);
> ```

Done.
___
*[`lib/pcg/src/pcg/machine_view.cc` line 108 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1OyeOa1nmLu-PORrMG:-O1rWTx88fNYhwUdnb21:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4928c9e52dd83db9b762259e102acc3107bfa521/lib/pcg/src/pcg/machine_view.cc#L108)):*
> ```cpp
>   }
>   assert(get_device_type(start) == DeviceType::GPU);
>   return make_1d_machine_view(unwrap_gpu(start), interval_size, stride);
> ```

Done.
___
*[`lib/pcg/test/src/test_machine_view.cc` line 22 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1Oz7w69lxicV3Wz2ZN:-O1rYI6J3riYUy4C092C:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4928c9e52dd83db9b762259e102acc3107bfa521/lib/pcg/test/src/test_machine_view.cc#L22)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Split gpu and cpu processing into subcases--the "declare a whole bunch of stuff, then run a whole bunch of tests on it" makes testcases rather hard to read. It's a lot more readable if the declarations are closer to and associated with their uses
</blockquote></details>

Done.
___
*[`lib/pcg/test/src/test_machine_view.cc` line 25 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1Oyr3H2OijgONlUfjK:-O1rZb6QEF0vYcTcZmaV:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4928c9e52dd83db9b762259e102acc3107bfa521/lib/pcg/test/src/test_machine_view.cc#L25)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can you wrap these in subcases with names that clarify the differences between all these different checks? (if it's testing overloads, for example, it could be `SUBCASE("<the function signature>")`)
</blockquote></details>

Done.
___
*[`lib/pcg/test/src/test_strided_rectangle.cc` line 12 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1OzSnt5uwD3N6uJ4xB:-O1rabbh72cxHW6FsVsz:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4928c9e52dd83db9b762259e102acc3107bfa521/lib/pcg/test/src/test_strided_rectangle.cc#L12)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Separate test case (or at least a separate subcase)
</blockquote></details>

Done.
___
*[`lib/pcg/test/src/test_strided_rectangle.cc` line 24 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1OzVJE8Sjf_MgZ_uPS:-O1raY2O82TCKx5NEY94:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4928c9e52dd83db9b762259e102acc3107bfa521/lib/pcg/test/src/test_strided_rectangle.cc#L24)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

At the very least subcases for different functions
</blockquote></details>

Done.

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1429)* status: all files reviewed, 9 unresolved discussions (waiting on @Marsella8)

___
*[`lib/pcg/src/strided_rectangle.cc` line 24 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1OyGDKEvaQDHs-565f:-O1ycCEQDePFiUN5p2Oa:b6yvi3j) ([raw file](https://github.com/flexflow/FlexFlow/blob/4928c9e52dd83db9b762259e102acc3107bfa521/lib/pcg/src/strided_rectangle.cc#L24)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

Changed (`rect.sides` is of type FFOrdered so direct application of `transform` is not possible, let me know if this is preferrable).
</blockquote></details>

It's defined here: https://github.com/flexflow/FlexFlow/blob/repo-refactor/lib/op-attrs/include/op-attrs/dim_ordered/transform.h
___
*[`lib/pcg/test/src/test_machine_view.cc` line 12 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1ydPcg6bNj4Dn011_6:-O1ydPch3zSQfdZyO1hM:bjjk36f) ([raw file](https://github.com/flexflow/FlexFlow/blob/c84d80235b384ad09954cd0b5c70a6ce75563db0/lib/pcg/test/src/test_machine_view.cc#L12)):*
> ```cpp
>     gpu_id_t start(1);
>     MachineView mv{device_id_t{start}, rect};
>     CHECK(num_dims(mv) == 2);
> ```

Subcases?
___
*[`lib/pcg/test/src/test_machine_view.cc` line 24 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1yd_qo0Uh8HP6seSmt:-O1yd_qo0Uh8HP6seSmu:b-wp3qj1) ([raw file](https://github.com/flexflow/FlexFlow/blob/c84d80235b384ad09954cd0b5c70a6ce75563db0/lib/pcg/test/src/test_machine_view.cc#L24)):*
> ```cpp
>     SUBCASE("make_1d_machine_view(gpu_id_t start, gpu_id_t stop, int stride)") {
>       CHECK(make_1d_machine_view(
>                 start_gpu, device_id_t{gpu_id_t(1 + 7 * 5)}, 5) == gpu_mv);
> ```

Follow this pattern where possible for clarity, apply to the subcases below



_Suggestion:_
```cpp
      MachineView result = make_1d_machine_view(start_gpu, device_id_t{gpu_id_t(1 + 7 * 5)}, 5);
      MachineView correct = gpu_mv;
      CHECK(result == correct);
```
___
*[`lib/pcg/test/src/test_strided_rectangle.cc` line 6 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1yd0jQBB_qutlEZsrG:-O1yd0jR8nyA2OcW5FYq:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/c84d80235b384ad09954cd0b5c70a6ce75563db0/lib/pcg/test/src/test_strided_rectangle.cc#L6)):*
> ```cpp
> 
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("get_side_size(StridedRectangleSide s)") {
> ```





_Suggestion:_
```cpp
  TEST_CASE("get_side_size(StridedRectangleSide)") {
```
___
*[`lib/pcg/test/src/test_strided_rectangle.cc` line 11 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1yd2uR1JH3D4lN8f0U:-O1yd2uR1JH3D4lN8f0V:bv8tp29) ([raw file](https://github.com/flexflow/FlexFlow/blob/c84d80235b384ad09954cd0b5c70a6ce75563db0/lib/pcg/test/src/test_strided_rectangle.cc#L11)):*
> ```cpp
>     CHECK(get_side_size(side) == side_size_t{7 * 5});
>   }
>   TEST_CASE("Make StridedRectangleSide from size and stride") {
> ```

If you're testing a function, just put the function name



_Suggestion:_
```cpp
  TEST_CASE("strided_side_from_size_and_stride") {
```
___
*[`lib/pcg/test/src/test_strided_rectangle.cc` line 12 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1yd7a61C38Uu6LYtpX:-O1yd7a61C38Uu6LYtpY:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/c84d80235b384ad09954cd0b5c70a6ce75563db0/lib/pcg/test/src/test_strided_rectangle.cc#L12)):*
> ```cpp
>   }
>   TEST_CASE("Make StridedRectangleSide from size and stride") {
>     StridedRectangleSide side{num_points_t{10}, 3};
> ```





_Suggestion:_
```cpp
    StridedRectangleSide correct{num_points_t{10}, 3};
```
___
*[`lib/pcg/test/src/test_strided_rectangle.cc` line 25 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1ycpot8kvn8xFbtWq9:-O1ycpouAr68lw2rc9jN:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/c84d80235b384ad09954cd0b5c70a6ce75563db0/lib/pcg/test/src/test_strided_rectangle.cc#L25)):*
> ```cpp
>     StridedRectangle rect{{s0, s1, s2}};
> 
>     SUBCASE("number of dimensions") {
> ```





_Suggestion:_
```cpp
    SUBCASE("get_num_dims") {
```
___
*[`lib/pcg/test/src/test_strided_rectangle.cc` line 28 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1yctef1WCbcjYZb94r:-O1ycteg99ocujdZg2-q:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/c84d80235b384ad09954cd0b5c70a6ce75563db0/lib/pcg/test/src/test_strided_rectangle.cc#L28)):*
> ```cpp
>       CHECK(get_num_dims(rect) == 3);
>     }
>     SUBCASE("number of points") {
> ```





_Suggestion:_
```cpp
   SUBCASE("get_num_points") {
```
___
*[`lib/pcg/test/src/test_strided_rectangle.cc` line 31 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1ycwp63RfH0d0l4AuC:-O1ycwp63RfH0d0l4AuD:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/c84d80235b384ad09954cd0b5c70a6ce75563db0/lib/pcg/test/src/test_strided_rectangle.cc#L31)):*
> ```cpp
>       CHECK(get_num_points(rect) == num_points_t{7 * 8 * 10});
>     }
>     SUBCASE("each side is correctly stored") {
> ```





_Suggestion:_
```cpp
  SUBCASE("get_side_at_idx")
```

**Review by Marsella8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1429)* status: 5 of 8 files reviewed, 9 unresolved discussions (waiting on @lockshaw)

___
*[`lib/pcg/src/strided_rectangle.cc` line 24 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1OyGDKEvaQDHs-565f:-O20msbs6MbUANAlU18d:bt2vr1b) ([raw file](https://github.com/flexflow/FlexFlow/blob/4928c9e52dd83db9b762259e102acc3107bfa521/lib/pcg/src/strided_rectangle.cc#L24)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

It's defined here: https://github.com/flexflow/FlexFlow/blob/repo-refactor/lib/op-attrs/include/op-attrs/dim_ordered/transform.h
</blockquote></details>

Fixed.
___
*[`lib/pcg/test/src/test_machine_view.cc` line 12 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1ydPcg6bNj4Dn011_6:-O20nHIR3L76K-7L7je1:bb6un1j) ([raw file](https://github.com/flexflow/FlexFlow/blob/a4bf20d10f33a0d72667b91f6c5b514ad229da20/lib/pcg/test/src/test_machine_view.cc#L12)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Subcases?
</blockquote></details>

Done
___
*[`lib/pcg/test/src/test_machine_view.cc` line 24 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1yd_qo0Uh8HP6seSmt:-O20oEDOAtx2a9LWhg6o:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/a4bf20d10f33a0d72667b91f6c5b514ad229da20/lib/pcg/test/src/test_machine_view.cc#L24)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Follow this pattern where possible for clarity, apply to the subcases below
</blockquote></details>

Done.
___
*[`lib/pcg/test/src/test_strided_rectangle.cc` line 6 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1yd0jQBB_qutlEZsrG:-O20omhr3CCZEQk305Uu:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/a4bf20d10f33a0d72667b91f6c5b514ad229da20/lib/pcg/test/src/test_strided_rectangle.cc#L6)):*
> ```cpp
> 
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("get_side_size(StridedRectangleSide s)") {
> ```

Done.
___
*[`lib/pcg/test/src/test_strided_rectangle.cc` line 11 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1yd2uR1JH3D4lN8f0U:-O20okVC89fbbF0Q4kTA:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/a4bf20d10f33a0d72667b91f6c5b514ad229da20/lib/pcg/test/src/test_strided_rectangle.cc#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

If you're testing a function, just put the function name
</blockquote></details>

Done.
___
*[`lib/pcg/test/src/test_strided_rectangle.cc` line 12 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1yd7a61C38Uu6LYtpX:-O20ojyT0knab3KQpqGt:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/a4bf20d10f33a0d72667b91f6c5b514ad229da20/lib/pcg/test/src/test_strided_rectangle.cc#L12)):*
> ```cpp
>   }
>   TEST_CASE("Make StridedRectangleSide from size and stride") {
>     StridedRectangleSide side{num_points_t{10}, 3};
> ```

Done.
___
*[`lib/pcg/test/src/test_strided_rectangle.cc` line 25 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1ycpot8kvn8xFbtWq9:-O20oj7S3rAgHTi8HkdI:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/a4bf20d10f33a0d72667b91f6c5b514ad229da20/lib/pcg/test/src/test_strided_rectangle.cc#L25)):*
> ```cpp
>     StridedRectangle rect{{s0, s1, s2}};
> 
>     SUBCASE("number of dimensions") {
> ```

Done.
___
*[`lib/pcg/test/src/test_strided_rectangle.cc` line 28 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1yctef1WCbcjYZb94r:-O20oi8869HDV4xJBupC:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/a4bf20d10f33a0d72667b91f6c5b514ad229da20/lib/pcg/test/src/test_strided_rectangle.cc#L28)):*
> ```cpp
>       CHECK(get_num_dims(rect) == 3);
>     }
>     SUBCASE("number of points") {
> ```

Done.
___
*[`lib/pcg/test/src/test_strided_rectangle.cc` line 31 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1429#-O1ycwp63RfH0d0l4AuC:-O20oibO0B9CQsctSCA2:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/a4bf20d10f33a0d72667b91f6c5b514ad229da20/lib/pcg/test/src/test_strided_rectangle.cc#L31)):*
> ```cpp
>       CHECK(get_num_points(rect) == num_points_t{7 * 8 * 10});
>     }
>     SUBCASE("each side is correctly stored") {
> ```

Done.

**Review by lockshaw — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1429)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marsella8)

**Pull request merged**
