### PR TITLE
Repository restructuring

### PR DESCRIPTION
**Pull request by lockshaw**
**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

### CODE REVIEW

**Comment by lockshaw** [comment]
@virena FYI

**Comment by eric-zheng** [comment]
Great to see this refactor of the repo structure which also cleans up old code. It's also good to see that we are going to use spdlog for logging. Just a note that from my past experience, spdlog may significantly increase the compilation time (not necessarily in ff though).

**Comment by lockshaw** [comment]
> Great to see this refactor of the repo structure which also cleans up old code. It's also good to see that we are going to use spdlog for logging. Just a note that from my past experience, spdlog may significantly increase the compilation time (not necessarily in ff though).

Any reason why? We're not using the header-only version so it should only even contribute on the first build

**Comment by virena** [comment]
Closes #440

**Comment by lockshaw** [comment]
Moving to #622

**Pull request closed without merging**
