### PR TITLE
Disable CUDA hijack in Legion

### PR DESCRIPTION
**Pull request by eddy16112**
TODOs:

- [ ] Implement cuda event pool
- [x] Make sure the index launcher of NCCL calls is set to concurrent
- [ ] Make sure we have cudaFree for each cudaMalloc
- [x] Wait for the `Realm::Cuda::get_task_cuda_stream();` to be merged into Legion master branch. 
- [x] update nccl to the latest version.

### CODE REVIEW

**Comment by jiazhihao** [comment]
We should have a discussion with Sean and the Legion team to know their plan for merging realm/cuda-task-stream to master.

**Comment by jiazhihao** [comment]
Currently depending on changes to the Legion CUDA subsystem.

**Comment by lockshaw** [comment]
@jiazhihao Can we not merge it to the `flexflow` legion branch so this issue is not blocked?

**Comment by jiazhihao** [comment]
My understanding is that the implementation was incomplete, so we didn't merge it to the `flexflow` branch of the legion repo. @eddy16112 may know the status. I think this is not blocking any development effort from our end, right?

**Comment by eddy16112** [comment]
The work is done. However, there are `cudaMalloc` and `cudaFree` within tasks, so for better performance, it is better to have our own memory pool, or use realm's create_instance call.

**Comment by jiazhihao** [comment]
> The work is done. However, there are `cudaMalloc` and `cudaFree` within tasks, so for better performance, it is better to have our own memory pool, or use realm's create_instance call.

We are replacing all `cudaMalloc` with realm's instance creation. Do you think the PR is ready to be merged?

My understanding is that cuda hijack will be disabled by default. How do we re-enable it?

**Comment by eddy16112** [comment]
> > The work is done. However, there are `cudaMalloc` and `cudaFree` within tasks, so for better performance, it is better to have our own memory pool, or use realm's create_instance call.
> 
> We are replacing all `cudaMalloc` with realm's instance creation. Do you think the PR is ready to be merged?
> 
> My understanding is that cuda hijack will be disabled by default. How do we re-enable it?

I think it is better to test it with our CI before merging it. Why do you want to re-enable hijack, given that the latest nccl does not work with hijack?

**Comment by jiazhihao** [comment]
> Why do you want to re-enable hijack, given that the latest nccl does not work with hijack?

I was thinking about offering backward compatibility. You are right that if the newest NCCL does not work with cuda hijack, we should always disable that and remove the `CUDA_HIJACK` related marcos

**Comment by eddy16112** [comment]
Currently, the non-cuda-hijack should be the same as cuda hijack if we use `Realm::Cuda::get_task_cuda_stream()`. Even with hijack, calls like `cudaMalloc` and `cudaCreateEvent` will be redirect to the corresponding cuda driver APIs, we will also need memory and event pool even with hijack.

**Comment by jiazhihao** [comment]
I have tested this PR in the inference branch as well. FlexFlow works with the latest NCCL but produces incorrect results. @eddy16112 Any idea what the issue might be?

**Comment by eddy16112** [comment]
Not sure if it is a Legion issue. I have updated the flexflow branch with the latest control replication branch. Can you try to change remove this line https://github.com/flexflow/FlexFlow/blob/a7a6a1d11392494c41443568b3777d85b72a0ce9/src/runtime/cuda_helper.cu#L20? Without this line, we call cuCtxSync after each cuda task.

**Comment by jiazhihao** [comment]
I observed the same error after commenting out that line.

**Comment by eddy16112** [comment]
Can you try to enable this section? https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/realm/cuda/cuda_module.cc#L1629-1631
Maybe you can just remove the ifdef

**Comment by jiazhihao** [comment]
The issue remains after forcing GPU stream synchronization. I have tested using a single GPU and a single GPU stream and seen the same incorrect output. (i.e., the issue exists with a single GPU and a single stream).

**Comment by eddy16112** [comment]
Then it should be the issue of flexflow.

**Comment by eddy16112** [comment]
@goliaro I have update the nccl cmake, such that we can use the nccl from conda. Do you think if we still need the prebuild nccl from flexflow-third-party?

**Comment by goliaro** [comment]
> @goliaro I have update the nccl cmake, such that we can use the nccl from conda. Do you think if we still need the prebuild nccl from flexflow-third-party?

so the conda nccl already supports all gpu archs by default? if so, I think we can remove the dependency on the flexflow-third-party pre-built version. We will just need to update the conda files and README to ensure users install nccl before building FF

**Review by goliaro — APPROVED** [review]

**Pull request merged**
